### ISSUE TITLE
Update for readme?

### ISSUE THREAD

**Issue by tvannahl** [RetroPie/EmulationStation#105]
As far as I understand it all the links to emulationstation.org or petrockblog/RetroPie-Setup are opsolete, right?

I am currently trying to get my head around the development process and so I am currently a bit lost. Both petrockblog/RetroPie-Setup and Retropie/RetroPie-Setup are currently receiving updates, Retropie/Emulationstation recommends petrockblog/RetroPie-Setup which is a fork of Retropie/RetroPie-Setup but Retropie should be "your" place to work, right?

**Comment by joolswills** [comment]
This is a fork specifically for RetroPie. The main RetroPie github is https://github.com/RetroPie/RetroPie-Setup - petrockblog is a person fork for development.

Read me is out of date, but I don't have time to rewrite it right now (it's a low priority compared to other things I have on). I also don't want to give the impression that this is the official Emulation Station. It's one of a few forks.

**Comment by joolswills** [comment]
I made a quick edit removing some of the information from the README. This should suffice for now.

**Comment by tvannahl** [comment]
Looks much clearer now. Thank you!
