### ISSUE TITLE
Match ES load screen same as splashscreen

### ISSUE THREAD

**Issue by smartroad** [RetroPie/EmulationStation#11]
I was wondering if it would be possible to match the ES load screen with the retrofits splashscreen. Having some text saying that emulation station is loading.

Just think it would add some continuity with the retrofit boot sequence. I know that ES loads an SVG for its boot screen so this whole idea may be pointless (or it is just pointless lol)

**Comment by gizmo98** [comment]
You can convert jpg to svg. I would suggest it does not look good ;-)
