### ISSUE TITLE
"Failed to open BO for returned DRI2 buffer", when autostart emulationstation

### ISSUE THREAD

**Issue by Max13** [RetroPie/EmulationStation#110]
First of all, something implicit has to be explicit: `emulationstation` seems to have to be started from a desktop manager terminal, or else you'll get an SDL error and nothing else.

After having installed a fresh Debian 8.7, then RetroPie, then Basic Install, then enabled `emulationstation` autostart, I reboot the machine, and when it started, ES splashscreen showed up, retropie menu came and after 1 or 2 secs, it crashed showing this message (followed by "it's likely a bug in the X server that will lead to a crash soon).

After a fresh install, it happens when autostart, when starting manually ES from terminal (by starting `emulationstation`), and even when starting `rpie` which seems to be the same as autostart (`gnome-terminal --full-screen --hide-menubar -e emulationstation`). After that crash, if I try to start it again by either method, it crashes gnome, logging me out and showing that extensions are disabled.

Then, I installed EmulationStation Kid mode. Autostart still fails, but strangely, starting `emulationstation` from a terminal seems to launch it normally, same as "rpie"... it's like at first start, something that `emulationstation` depends on is starting AFTER ES, it crashes, but at the second start it's ok because the dependency is already there?

Is it a known bug or issue? Or did I do something wrong?

Platform: [Jaguarboard](http://jaguarboard.org/index.php/products/product_show/jaguarboard-industry-first-x86-based.html) (An X86 Raspberry-like board)
- Booting via EFI, Debian 8.7-amd64, freshly installed with gnome.
- ES and ES kid installed using RetroPie-Setup scripts.

**Comment by joolswills** [comment]
I don't have that hardware, but it all works fine on my x86_64 machine running Ubuntu. Could be some graphics driver or something on your system.

**Comment by Max13** [comment]
Well well... Sometimes it loads and crash, sometimes it loads correctly.

Anyway, I planned to reinstall it from scratch. Thank you
