### ISSUE TITLE
Fast scrolling on detail and video view gamelist causes black boxes to show.

### ISSUE THREAD

**Issue by KazanTheMan** [RetroPie/EmulationStation#120]
The issue can be easily replicated by viewing a detail or video gamelist, and holding up or down to scroll rapidly through the list. The issue occurs from as few as 5 games being scrolled through in this manner, but can take up to 15 before it shows. It does not always occur, but will occur probably 3 out of 4 times. From what I can tell, the boxes are generally static for that system view until refreshed via theme change, debug shortcut, or ES is restarted. It seems like the boxes are related to the metadata content on the screen. I can replicate the box pattern fairly reliably based on the game I start with when I hold the up/down buttons.

[Screenshot 01](http://imgur.com/BU8xxgG) [Screenshot 02](http://imgur.com/t0mIVwW) [Screenshot 03](http://imgur.com/4bgFHhH) [Screenshot 04](http://imgur.com/YxqTp6p) Notice in the first two screenshots it's the same bug instance (no refresh/reload), but the two games have different missing metadata tags and this causes the boxes to move or not appear depending on which game is highlighted. The third image is what it looks like when the issue happens in the extreme, and the fourth is what the theme should look like. Using debug mode to highlight text boxes with Ctrl+T does not highlight the boxes created by this bug, despite it seemingly being related to text fields. The only actual text field that is affected is the description box.

I have been able to replicate this bug on both Windows 10 running ES 2.1.5rp, and on a RaspberryPi 3 Model B running RetroPie 4.2.2 - last updated on April 15th 2017 from source, running ES 2.1.6rp. It is not isolated to my theme, SimpleBigArt and Carbon are also affected, though it is very difficult to tell on Carbon because of how dark the theme is. [Screenshot 04](https://i.imgur.com/QurXD5L.jpg) Interestingly, themes that are not affected are all themes that hide their metadata text fields below the screen limits, as the artifacts only seem to render below existing text fields.

The issue also does not seem to be caused by image density or filesize, or an image/text overlap bug; I made a modified version of my theme with all image tags removed and still experienced the issue. [Screenshot 05](http://imgur.com/duTH2SM) Unfortunately, there was no useful output to es_log that I could find in any given instance, mostly just a lot of missing image files for my system folders: [pastebin](https://pastebin.com/a2m2apfm)

**Comment by shantigilbert** [comment]
I can confirm, this also happens to me, but I always though it was because I am running it on an unsupported device.  I run ES on a Amlogic s905 device using the tronkyfran theme.

**Comment by joolswills** [comment]
reference: https://retropie.org.uk/forum/topic/9787/es-gamelist-scroll-bug-black-boxes-appear-when-rapidly-scrolling-through-the-game-list

**Comment by pjft** [comment]
I believe this is solved now?

**Comment by joolswills** [comment]
Yep. Thanks.
