### ISSUE TITLE
Cmake fails in Ubuntu

### ISSUE THREAD

**Issue by cmcginty** [RetroPie/EmulationStation#121]
I can't even get past cmake on step?

```
Looking for bcm_host.h
bcm_host.h not found
Looking for libMali.so
libMali.so not found
-- Looking for FreeImage...
-- Checking for module 'freeimage'
--   No package 'freeimage' found
-- Found FreeImage: optimized;/usr/lib/x86_64-linux-gnu/libfreeimage.so;debug;/usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   date_time
--   locale
-- VLC library found
CMake Error at external/CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /home/panther/EmulationStation/external/pugixml

  does not contain a CMakeLists.txt file.
```

**Comment by joolswills** [comment]
You need to do `git submodule update --init --recursive`

**Comment by hex007** [comment]
Clone the repository using this:

`git clone --depth 1 --recurse-submodules https://github.com/RetroPie/EmulationStation`

**Comment by pjft** [comment]
Had the same problem today, joolswills 's comment pretty much solved it for me.

Can you confirm whether this still persists, or otherwise close?

Thanks.

**Comment by joolswills** [comment]
I guess it needs mentioning in the README.md but that's so out of date. TBH as the retropie fork, the focus has not been on this being any official fork and doing the documentation, but I guess we could add a bit to the docs.

**Comment by pjft** [comment]
I don't know enough about cmake, and my make days are long behind me. 

Is there a way to get cmake or make to actually fetch and update the repository prior to generating the makefile?

**Comment by joolswills** [comment]
probably, but it's not usual to use cmake to do repo stuff like that imho. Closing this as original issue is fixed.
