### ISSUE TITLE
Sort by other meta data fields

### ISSUE THREAD

**Issue by MotaDan** [RetroPie/EmulationStation#124]
Right now you can only sort by name, rating, play date, and play count. I would like to be able to sort by the other fields like players, release date, genre, developer, publisher.

**Comment by Darknior** [comment]
If possible it will be a great update :)
Number of players, publisher, etc can help :)

**Comment by jrassa** [comment]
There is a existing pull request #115 to add the ability to filter by most of these.

**Comment by MotaDan** [comment]
I just extended the sort methods that were already there. I don't conflict with #115, but if it's redundant mine can just be tossed.

**Comment by joolswills** [comment]
I think we can have both - sort != filter. Will comment on the PR.
