### ISSUE TITLE
Zoom to Image in Slide Transition Broken in Video Preview

### ISSUE THREAD

**Issue by TMNTturtleguy** [RetroPie/EmulationStation#127]
Since video previews have been introduced, the slide transition no longer zooms properly to the "md_video" or "md_image" in a theme upon launching a game when in a Video View only.   When you go to a system with video previews and launch a rom, you zoom to the middle. The only exception is with the arcade system. This actually will zoom in on the video.  If you enter a system without video previews present, or the "detailed view" and an art image is shown, the view will zoom into the center of that image when launching a game. I have tested this on several themes along with carbon with video support as updated from the retropie script. Same exact results, even on the arcade system.

I also have an old version of Carbon backed up on my machine before video was implemented. When i use this theme that does not have video in the theme code, all systems properly zoom into the image. Thus, there is something wrong with the code for video view support. The only question is why does this behave properly on the arcade system only?

**Comment by pjft** [comment]
I'll take a look at this, hopefully. Thanks for reporting it.
