### ISSUE TITLE
Z index default ordering problem.

### ISSUE THREAD

**Issue by ruckage** [RetroPie/EmulationStation#141]
I think there may be an error with the default z-ordering in the latest  ES with z-index support.
If you check my theme (Nes-Mini) most of the metadata is not showing - presumably hidden behind some of the images.

I'll work on a fix for my themes but thought you should be made aware as I guess this was unintended and it could potentially break other themes as well.

**Comment by jrassa** [comment]
I will be submitting the fix shortly.  The default z-index values were not being set properly for some of the elements in detail view.

**Comment by ruckage** [comment]
Thanks, I've just tested the new version and the issue is resolved.
