### ISSUE TITLE
Nestopia Warning Error

### ISSUE THREAD

**Issue by LodanZark** [RetroPie/EmulationStation#147]
`= = = = = = = = = = = = = = = = = = = = =
Installing 'lr-nestopia' : NES emu - Nestopia (enhanced) port for libretro
= = = = = = = = = = = = = = = = = = = = =

‘/home/pi/RetroPie-Setup/tmp/build/lr-nestopia/libretro/nestopia_libretro.so’ -> ‘/opt/retropie/libretrocores/lr-nestopia/nestopia_libretro.so’
‘/home/pi/RetroPie-Setup/tmp/build/lr-nestopia/NstDatabase.xml’ -> ‘/opt/retropie/libretrocores/lr-nestopia/NstDatabase.xml’
‘/home/pi/RetroPie-Setup/tmp/build/lr-nestopia/README.md’ -> ‘/opt/retropie/libretrocores/lr-nestopia/README.md’
/home/pi
Could not successfully install NES emu - Nestopia (enhanced) port for libretro (/home/pi/RetroPie-Setup/tmp/build/lr-nestopia/README.unix not found).

Log ended at: Sun 28 May 23:48:24 UTC 2017
Total running time: 0 hours, 4 mins, 53 secs`

[rps_2017-05-28_234331.log.gz](https://github.com/RetroPie/EmulationStation/files/1034610/rps_2017-05-28_234331.log.gz)

**Comment by hex007** [comment]
This doesn't look like a EmulationStation issue. Kindly report it on "RetroPie-Setup" repo and close this issue.

https://github.com/RetroPie/RetroPie-Setup

**Comment by HerbFargus** [comment]
No, any perceived issued should be posted on the forum first.

**Comment by LodanZark** [comment]
oops I though was in RetroPie-Setup, I posted in wrong section sorry
