### ISSUE TITLE
Zoom in transition on game launch is now broken

### ISSUE THREAD

**Issue by pjft** [RetroPie/EmulationStation#151]
Just bisected it, and narrowed it down to this commit:

```
commit de643bb1140d75b6a8605f79866c4f1f2a7340e3
Author: jrassa
Date:   Tue May 30 22:41:41 2017 -0400

    use clip rects to prevent views overflow onto other views
```

@jrassa - any thoughts on this?

If I comment out the clip rectangles on the IGameList.cpp file, it works as previously, but I suspect that defeats the purpose of this particular change?

From what I gather, it seems that the rectangle clipping is not using the right (potentially moving) center for the zoom in animation and respective clipping.

Would love your perspective here, as I don't want to break whatever you did.

Thanks!

**Comment by joolswills** [comment]
@pjft Thanks.

**Comment by jrassa** [comment]
@pjft I am looking into a fix.

**Comment by jrassa** [comment]
@pjft The way the zoom animation works is that it draws the view progressively larger.  The previous change that I made did not account for this, so as the view became larger, the clip rect stayed the same size which caused it to only draw a progressively smaller portion of the view.  I was able to extract the current scale factor from the transform and apply it to the clip rect.

**Comment by pjft** [comment]
Great - glad it was an easy-ish fix for you! :)


- Paulo Tavares
