### ISSUE TITLE
Misaligned text / selector bar on some themes

### ISSUE THREAD

**Issue by joolswills** [RetroPie/EmulationStation#164]
@jrassa

Since https://github.com/RetroPie/EmulationStation/pull/157 / 3a98bd38471bd2ae3fff2ad67b92bd3ed9b9c171 some themes have Misaligned text / selector bar. Eg Metapixel.

Do these themes just need updating or is there an issue with the fixes ?

https://retropie.org.uk/forum/topic/11148/certain-themes-suddenly-started-misaligning-text-selections-in-emulationstation

**Comment by hex007** [comment]
If this is fixed, please close the issue.
