### ISSUE TITLE
Overscan config won't save.

### ISSUE THREAD

**Issue by robertvaliant** [RetroPie/EmulationStation#165]
I'm running retropie and emulationstation on a raspberry pi 3 and a really old flatscreen tv/monitor (hdmi to vga cable). I had an overscan issue originally and fixed it in the emulationstation raspi-config option settings. It was fine but at some point it switched back to hiding about a centimetre of the right side of the screen (The UI also went a bit crazy and crashed around the same time but that seemed to fix itself after hard powering off and on a few times). I can fix the overscan issue each time by going back into the raspi-config settings and switching overscan on and rebooting but every time I shut down (rebooting is fine), it reverts back to overscan off.

I have tried changing the config.txt by either adding a # at the start, or a 0 or 1 at the end of the line then saving but again, but each time, powering on changes it back. 

I'm fairly new to this. Until now I've been able to fix issues with just the front end so be gentle with me when it comes to the command line. Either way, 
I'd be truly grateful to anyone who knows how to fix this as it's annoying to have to reboot each time to correct the overscan. Thanks in advance.

**Comment by robertvaliant** [comment]
Fixed!

I am such a bellend. The problem was I hadn't fixed the aspect ratio in the retropie video settings. 

So there you go.  If you keep needing to fix overscan, therein might lie your solution.

**Comment by joolswills** [comment]
Glad it's sorted. For future reference please use the RetroPie forum for help rather than this bugtracker.

**Comment by robertvaliant** [comment]
Oh. Sorry. Like I said, I'm new to this. 


⁣Sent from BlueMail ​
