### ISSUE TITLE
Emulationstation Splash screen now black, should be white.

### ISSUE THREAD

**Issue by agentmith** [RetroPie/EmulationStation#171]
Just did an update and noticed the ES splashscreen changed to black, as well as the background for the controller sync splash changing colors. Please let me know if there is a way to revert back to the original colors. Thanks.

**Comment by hex007** [comment]
The recent versions have moved from White background to Black background. You can see what files have changed in the commit and compile ES from edited source.

https://github.com/RetroPie/EmulationStation/blob/004243bb764132655a22fa538d0b85c233103364/es-core/src/Window.cpp#L231

You can switch from :
`Renderer::drawRect(0, 0, Renderer::getScreenWidth(), Renderer::getScreenHeight(), 0x000000FF);`

to :
`Renderer::drawRect(0, 0, Renderer::getScreenWidth(), Renderer::getScreenHeight(), 0xFFFFFFF);`
