### ISSUE TITLE
sliders in settings causes auto scroll.

### ISSUE THREAD

**Issue by atom10** [RetroPie/EmulationStation#176]
Targeting with gamepad to any slider setting causes auto scrolling.
https://youtu.be/UsTGoQF-_p0
noticed: ES on retropie rpi3

**Comment by pjft** [comment]
Thanks.

I believe we have this narrowed down and with a solution hypothesis.

Can you just confirm that this does not happen on the "UI Settings" Menu,
though?

https://retropie.org.uk/forum/topic/11190/i-think-i-found-a-bug-with-the-vram-limit-and-volume-sliders

Best.


- Paulo Tavares

**Comment by atom10** [comment]
Yes, it does not happen on ui settings. Only when slider is betwen other options. And whats is weird it only effects gamepads, keyboard is perfectly fine.

**Comment by pjft** [comment]
Yeah, not all gamepads either, that's why it's been somewhat elusive.

We'll tweak that, certainly.


- Paulo Tavares

**Comment by pjft** [comment]
Should be fixed, confirmed in the forums. Can be closed.

**Comment by atom10** [comment]
building from source takes forever but i'll tell if it works as fast i can.
Thank you very much for fix!

**Comment by pjft** [comment]
Thanks. You may need to exit ES in order to build it successfully.

Best.


- Paulo Tavares

**Comment by atom10** [comment]
Always stuck at: [100%] building cxx(...) ViewController.cpp.o. Seems like out of free ram or something. will try later but if at forum it worked then seems that thread can be closed.

**Comment by pjft** [comment]
Huh. Happening here as well.

Stats:

PID     Name              VIRT     RES
17095 root      20   0  416540 384216      0 D   3.2 51.0   0:40.32 cc1plus


17078 root      20   0  398060 300056      0 D   3.1 39.9   0:42.27 cc1plus

I'm trying now to increase rpSwap for the ES compilation.

If it crashes, you may for the time being exit with Ctrl-C, then navigate
to ~/RetroPie-Setup/tmp/build/emulationstation and try to run "sudo make".
I'll report back later.


- Paulo Tavares

**Comment by pjft** [comment]
There's a binary for this now, FYI!


- Paulo Tavares
