### ISSUE TITLE
Input devices should be supported de facto without need to mapping it buttons on boot

### ISSUE THREAD

**Issue by dantheman213** [RetroPie/EmulationStation#18]
Keyboard should be supported de facto without need to mapping buttons on boot. If you don't have a controller plugged in to do something other than play (e.g. configuring, setting up, transferring roms, etc) then it should work without a problem.

The same is true to for a controller. Should be able to map in the top 10 most popular USB controllers and map buttons automatically with an option to override in the GUI.

Obvious controllers/gamepads that should be supported with pre-defined mappings from the getgo
* Xbox 360 controller
* PS3 controller
* Wii controller
* SNES-like USB gamepad

**Comment by joolswills** [comment]
It takes only a minute or two to configure inputs - our whole system is designed around this - replacing the auto configuration stuff we had before. What you propose sounds like a step backwards imho.

**Comment by smartroad** [comment]
The thing I find tedious is the whole 'press and hold any key to skip'. I wish there was a way to skip once you had inputted the basic directions and AB buttons :grin:

**Comment by joolswills** [comment]
I agree that could be useful

**Comment by joolswills** [comment]
I would add though, that this only needs to be done once. updating emulationstation should no longer clear out old configs, so as long as you keep your controllers, it shouldn't be too annoying :)

**Comment by dantheman213** [comment]
@joolswills You should really reconsider. The whole point of using an RPi with a USB gaming controller and plugging it into my TV is that I don't want to deal with "desktop-like" qualities. I want to be able to plug-and-play. Remember that the whole spirit of the RetroPie project is to recreate a classic gaming experience. I don't recall having to reconfigure a controller every single time I plug in a new controller. I also don't remmeber having to configure my settings with a keyboard or being thrown out of the console's GUI to a command-line... just because this is a developer project doesn't mean it shouldn't be user friendly or provide the vintage factor for the *very* reason why we're playing it in the first place.

It's very frustrating to have to sit their and configure my Xbox 360 controller for PSX games and then switch over to my SNES-like USB gamepad to play NES/SNES games. Not to mention if I want to plug in a keyboard to do editing I have to remap everything.

The button mapping process also sucks and is cumbersome so every time you have to switch it is very frustrating.

--Dan

**Comment by joolswills** [comment]
You only have to configure each controller once.

Our current system is far more flexible - we don't want to go back to how things were - there were lots of issues. Based on the controller config we also configure inputs for various systems. Alo, what about cases where you have 6 controllers all with the same ids etc, but different layouts ?

**Comment by dantheman213** [comment]
@joolswills It doesn't appear to be that user friendly to me. Every time I unplug one controller and plug in another I have to sit there and do the process over again.... surely these devices have unique device IDs and/or unique properties to help identify them? The top controllers like the Xbox 360 really should be plug and play from the get go. 99% of people using this is going to be using that controller only another handful. Why frustrate people with keyboard and Xbox 360 mappings at the very least since it's already given how you want to map these devices. You can provide an override later, in the settings.

**Comment by joolswills** [comment]
some cheap clones do share device name/ids sometimes - at least we had this problem before afair.

You only have to configure each controller once. 

Please use the forum if you wish to discuss this further with other users. You may find that many like it how it is now.
