### ISSUE TITLE
Audio volume in start menu don't change volume in videos preview

### ISSUE THREAD

**Issue by slipenbois** [RetroPie/EmulationStation#187]
Hello 

even when you set audio to 0% the video volume stay the same.

I know omx player and sounds played by emulationstation are different things but maybe add a second option for video volume? (Or merge them don't know what is the best option.)

**Comment by pjft** [comment]
Correct. At the moment you can only have video audio on or off.

This is something that can be looked in, for sure.

Thanks.

**Comment by Darknior** [comment]
Yes ... like i already ask it to you @pjft it is a problem ....
I wish you will fix it too

**Comment by hex007** [comment]
@pjft Are you working on this or should I get to it ?

**Comment by pjft** [comment]
I'm not working on this at the moment. I'm happy if you want to take it. If
not, I'll pick it up in the coming weeks. My time has been mostly on the
collections work these past few weeks.

I believe you're also busy with the J2ME work, so it's up to you :)

Thanks. Have a good weekend.

**Comment by hex007** [comment]
@pjft Yea it seems simple enough to do.

J2ME looks like a dead end. Who know might work out too.

**Comment by meleu** [comment]
Looks like this issue was fixed by #220 and can be closed.
