### ISSUE TITLE
Provide GUI option to run embedded FTP/HTTP servers for easy rom/save transfer

### ISSUE THREAD

**Issue by dantheman213** [RetroPie/EmulationStation#19]
There should be an option in the Retropie GUI that allows for enabling an embedded web server and/or FTP server that can run quickly to allow for no-nonsense ROM or game save transfer for non-technical people or lazy technical people.

**Comment by joolswills** [comment]
This is the wrong bugtracker - feature requests for RetroPie should be posted https://github.com/RetroPie/RetroPie-Setup - but you would do better to discuss on the forum first. In this case, we already support sftp / samba shares and have a usbmount script, so I don't see why we need additional protocols.

**Comment by dantheman213** [comment]
@joolswills again I think you fail to see the "convenience" of having plug-and-play support for everything. This should be treated like a console or embedded device. You're treating it like a full Linux workstation.. If I'm gaming on my TV on a controller I don't want to deal with any of that...

**Comment by HerbFargus** [comment]
Perhaps you may have better luck checking out recalbox as their emphasis is on user friendliness. Retropie has more of an emphasis on customisation.

**Comment by joolswills** [comment]
I would add that RetroPie is not just a premade image - it is primarily a et of scripts that installs stuff on top of an existing distribution - ie. it installs on top of Wheey, Jessie, OSMC, Ubuntu etc. Even the code for adjusting autostart has about 3 implementations and doesn't support all cases. If we were a single set system it would be easier to treat it like a console or embedded device, but that isn't the case.
