### ISSUE TITLE
input configuration window is not shown until all buttons are mapped

### ISSUE THREAD

**Issue by bysreg** [RetroPie/EmulationStation#191]
repro step:
- install fresh retro pie
- run emulationstation
- The program asks for the user to hold any key to start. Using keyboard, hold any key
- After several seconds, "keyboard" text fades in, but nothing happens
- after pressing different keys, the input configuration window suddenly pops up showing all the inputs are mapped to the different keys i just pressed.

**Comment by joolswills** [comment]
Please use the forum first for help. Not seen this behaviour on my system. Maybe a hardware issue.

**Comment by hex007** [comment]
@bysreg If you do post this on the forum, post the link here so those interested can follow up the conversation
