### ISSUE TITLE
Folders in PSX roms do not display game metadata

### ISSUE THREAD

**Issue by wolfgangrumpf** [RetroPie/EmulationStation#197]
Playstation games placed inside a folder to contain the cue and bin file(s) do not display the game metadata (e.g. image, description) when the folder is selected in emulation station. The metadata MAY be displayed if the folder is navigated into but not always.

I have been able to reproduce this every time I create a new RetroPie system (currently I've made about 5).

**Comment by pjft** [comment]
Known issue, likely duplicate of another one currently open. I have fixed
it, but haven't submitted it yet as it's part of the collections work.
Thanks for reporting.

**Comment by wolfgangrumpf** [comment]
Let me know if you need a beta- tester for the fix.  :)

**Comment by pjft** [comment]
If you don't mind testing the custom collections piece as well, would love
to hear if it's sorted for good. :)

https://retropie.org.uk/forum/topic/11805/

Installation instructions:

https://retropie.org.uk/forum/topic/11805/please-test-creating-custom-collections/42

Do leave feedback there.
