### ISSUE TITLE
PowerSaver Instant mode is not saved

### ISSUE THREAD

**Issue by hex007** [RetroPie/EmulationStation#198]
Changing to instant mode does not get saved so setting reverts after restart. Revisiting menu saves it though.

**Comment by pjft** [comment]
Are you saving the transition and animations disabling when setting
instant?
If not, maybe on load it loads those settings and it overrides the instant
setting?

**Comment by hex007** [comment]
@pjft I noticed this long ago but since Instant was mostly experimental I did not bother much. I have added a PR #199 that fixes this and exposes a method that you can call after Play next slider is used to change timeout. Please check the PR for further details.
