### ISSUE TITLE
Page up / Page down dont work until a restart

### ISSUE THREAD

**Issue by joolswills** [RetroPie/EmulationStation#2]
When configuring controls - page up / page down wont work until a restart.

I may look into this myself, but putting here so it doesn't get forgotten.

**Comment by MattWatt** [comment]
I'm finding that the left and right shoulder buttons (not the trigger) no longer do the paging.  Unfortunately I discovered that the triggers are mapped to paging.  I'd prefer the behavior I had with 2.6 and would rather have the shoulder buttons mapped to paging.

Perhaps this is an issue with the new somewhat confusing controller configuration in the latest emulation station?  I find the "top" and "bottom" wording to be ambiguous.  As far as I can recall they've always been referred to as "shoulder" and "trigger".  I still believe I configured them with the correct interpretation, but paging is tied to the triggers.

**Comment by joolswills** [comment]
You will need to manually edit the ES configuration to change it (without affecting retroarch) - it all depends on your controller also - on my controller i configure left bottom / right bottom to the two shoulder buttons (I don't have triggers).

No need to be be confused - is it clearly illustrated on the wiki with controller images- https://github.com/RetroPie/RetroPie-Setup/wiki/First-Installation

**Comment by joolswills** [comment]
I do agree that perhaps the naming is not ideal, but there are no plans to change this currently.

**Comment by joolswills** [comment]
If you consider the ps3 controller it makes more sense.

**Comment by kwtaylor** [comment]
I ran into this issue and created a pull request to fix it #53 ... not sure if this is the kind of fix you had in mind. I feel like maybe the "onfinish" mechanism could be overhauled as it's a bit cryptic at the moment.

**Comment by kwtaylor** [comment]
Oh boy I just looked at the image in the wiki and I've also had "top" and "bottom" backwards all this time! For me, LT/RT always stood for "trigger" not "top" and "LB/RB" always stood for "button."

**Comment by joolswills** [comment]
the naming is confusing, but it's some work to change it all (lots of image reworking etc). Perhaps something we should consider though.

**Comment by joolswills** [comment]
I have made a PR to rename Bottom -> Shoulder and top ->trigger

https://github.com/RetroPie/EmulationStation/pull/54

does that sound better ?
