### ISSUE TITLE
Export game saves to Google Drive or Dropbox

### ISSUE THREAD

**Issue by dantheman213** [RetroPie/EmulationStation#20]
Export game saves to Google Drive or Dropbox! Allow for easy syncing if you want to play games on another emulator on another device.

**Comment by Ravian2002** [comment]
that's quite handy

**Comment by joolswills** [comment]
I believe this functionality is outside of the EmulationStation frontend - but can be achieved via some scripting or a fuse mount etc. Pull requests for adding cloud functionality to RetroPie-Setup welcome (we may already have a ticket open).
