### ISSUE TITLE
Input/output error when sshing into retropie

### ISSUE THREAD

**Issue by alaxmofo12** [RetroPie/EmulationStation#201]
Idk if someone has had this problem but everytime I ssh into retropie in list a bunch of input/output errors

**Comment by hex007** [comment]
Your SD card is probably dying. I/O errors on SD cards means you cannot do anything to recover the damaged sections. Best bet is to make a backup of all your important data on the card ad buy a new one.

Try running this on your Linux PC with said sdcard plugged in and partitions mounted and post the output.
`sudo fsck /dev/mmcblk0p2`

This is not an error of EmulationStation so you can close this issue.

**Comment by alaxmofo12** [comment]
Last login: Thu Aug  3 02:51:44 2017 from android-b74ac3a5f51bbe15.netgear.com
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Take on Me 3 (1999) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Star Wars - The Empire Strikes Back (1983) (Parker Bros).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Snafu (1981) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Back in the USSR (1999) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Closing Time (2001) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Copacabana (1999) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Creep (1999) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Nut March (1999) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Nut Reed (1999) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Nut Trep (1999) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Nut Waltz (1999) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Secret Agent Man (1999) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Take on Me 6 (1999) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Song Player - Too Sexy (1999) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Space Armada (1981) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Space Battle (1979) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Space Cadet (1982) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Space Hawk (1981) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Space Spartans (1981) (Mattel) [!].int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Spiker! - Super Pro Volleyball (1988) (Intv Corp).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Spirit V1.0 (2003) (Arnauld Chevallier).bin': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Stadium Mud Buggies (1988) (Intv Corp).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Stampede (1982) (Activision) [!].int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Star Strike (1981) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Stonix Beta1.1 (2003) (Arnauld Chevallier).bin': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Stonix Beta1.2 (2003) (Arnauld Chevallier).bin': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Street (1981) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Sub Hunt (1981) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Super Cobra (1983) (Konami).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Super Masters! (1982) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Super Pro Decathlon (1988) (Intv Corp).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Super Pro Football (1986) (Intv Corp).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Super Soccer (1983) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Swords and Serpents (1982) (Imagic) [!].int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Takeover (1982) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Tennis (1980) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Tetris (2000) (Joseph Zbiciak).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Thunder Castle (1982) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Tower of Doom (1986) (Intv Corp).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Triple Action (1981) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Triple Challenge (1986) (Intv Corp).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/TRON - Deadly Discs (1981) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/TRON - Deadly Discs - Deadly Dogs (1987) (Intv Corp).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/TRON - Maze-A-Tron (1981) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/TRON - Solar Sailer (1982) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Tropical Trouble (1982) (Imagic) [!].int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Truckin\' (1983) (Imagic) [!].int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Turbo (1983) (Coleco).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Tutankham (1983) (Parker Bros).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/U.S. Ski Team Skiing (1980) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/USCF Chess (1981) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Utopia (1981) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Vectron (1982) (Mattel).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Venture (1982) (Coleco).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/White Water! (1983) (Imagic) [!].int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/World Cup Football (1985) (Nice Ideas).int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/World Series Major League Baseball (1983) (Mattel) [!].int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/World Series Major League Baseball (1983) (Mattel) [b1].int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Worm Whomper (1983) (Activision) [!].int': Input/output error
find: `/home/pi/RetroPie/roms/intellivision/Zaxxon (1982) (Coleco).int': Input/output error

**Comment by alaxmofo12** [comment]
That's what it shows in ssh, but not on the command line when I push f4

**Comment by hex007** [comment]
@alaxmofo12 This is definitely related to ES but not an ES bug per say. ES is unable to find the rom file or most likely the sectors where the file is located is corrupt. Can you delete the folder on SD card, copy all files back again in the folder and test again? If it works then the SD card is dying. If it doesnt work still then your gamelists have wrong location of files

**Comment by alaxmofo12** [comment]
I forgot I had just intellevision ROMs on a usb stick. Cause I got a package of some sort that made it so I can expand the storage to a usb as well, and I tested with intellevision ROMs, and the load all weird but still show up. So idk what's going on.

**Comment by hex007** [comment]
Please use the Retropie forums for such issues. This is only to track ES code issues.

Try removing the gamelist for Intellevision and try again.

Make a post on the forums, post the link here and close this issue.

**Comment by joolswills** [comment]
Closing as not related to Emulation Station.
