### ISSUE TITLE
Black screen when pressing buttons or directions quickly after exiting a game.

### ISSUE THREAD

**Issue by RWoof** [RetroPie/EmulationStation#217]
I've noticed in the latest upgrade of Retropie/Emulationstation that if I exit a rom (doesn't seem to be system dependent but I mostly play arcade games) and while the screen is still black quickly press either left/right to change to another system or B to go back to the system screen the screen does not continue to fade to visible from black and stays black. I can still navigate and launch roms as normal, I think it's just that the quick button press after returning from a game interrupts the fade sequence and leaves the screen black. It seems to happen for me in any setting (fade, slide, instant). I hope it can be fixed!

**Comment by pjft** [comment]
Can you disable power savings in the other settings menu and see if it
still happens? Just to check if it's an animation stopping halfway through.
If that's not the case, do send over a video. Thanks!

**Comment by hex007** [comment]
@pjft PS is disabled by default so unless @RWoof has specifically enabled it, it should not be causing this bug.

**Comment by pjft** [comment]
You're right. Maybe he would have updated to the interim version first,
where it was enabled by default though, but well spotted.

**Comment by hex007** [comment]
Even I am facing the same problem if I follow the instruction (Linux x64). PS is disabled so it is not related to PS. I have made a video demonstrating the bug. In the first try I press Left/Right as soon as I close the emulator. In the second try I dont press any keys after closing the Emulator. 

https://youtu.be/S9x2RImazeE

**Comment by pjft** [comment]
Thanks for confirming!

I know it may be a bit time consuming, but if you can easily replicate it,
would you have the chance to bisect it? Happy to help with instructions
there - I imagine that if you can do it on Linux it's faster to compile and
get to the root.

If not, it's perfectly fine as well.

Thanks!

**Comment by RWoof** [comment]
Sorry for the slow reply, I seem to have the issue with all power saving modes.

**Comment by hex007** [comment]
@RWoof Please disable PS and try to replicate the bug. If the bug exists while PS is disabled then it is bound to happen when PS is enabled too as t is not related to PS. 

@pjft I shall have a look tomorrow.

**Comment by pjft** [comment]
Thanks, and sorry for the trouble.

I actually think this may have been happening for a _long_ time, now, reading the description. I'm almost positive I ran into it once as well, but didn't think too much of it - probably thought it was a one off glitch, as I couldn't really replicate it.

If that's the case, we may be chasing the wrong thing, but rather might be easier to treat this as a new bug.

I'd probably try to checkout and compile an older version, say v2.1.6 (commit e740e58004ec054e21f493fbb83e6f26433aa3d3) and see if it's good there. If it's already broken there, then just stop and treat it as something that needs to be fixed, but wasn't introduced recently.

Anyway, the steps for it are:

Step 1:
```
git clone --recursive https://github.com/RetroPie/EmulationStation.git ES-bisect
cd ES-bisect
git bisect start
git bisect bad
git bisect good e740e58004ec054e21f493fbb83e6f26433aa3d3
```

and then, the following:

Step 2:
```
cmake .
make
./emulationstation
```

and then test and exit ES.

Step 3:
After testing, if it works well, run

```
git bisect good
```

If it has the problem, run

```
git bisect bad
```

and then repeat steps 2 and 3, to create a new binary, and attempt to narrow down what exact change caused this.

It shouldn't take more than a few repetitions of these, but it can still take a bit as compiling can take some time, so we definitely thank you in advance.

At the end it will tell you what commit caused it, so you can send it back to us.

Thank you.

**Comment by hex007** [comment]
@pjft I went back to v2.2.1 and the bug is still present. This points to an old bug.

**Comment by pjft** [comment]
Thanks for checking!


- Paulo Tavares

**Comment by hex007** [comment]
@pjft I have found what is causing this bug. When exiting the game ES shows and animation that translates. If this translation is disturbed the frame gets stuck in y direction. Depending on when the key is pressed you should be able to see this clearly. I will dive into the code later today.

**Comment by pjft** [comment]
Oh, great finding. You may be on the right track here.

Best of luck! Let me know if I can help.
