### ISSUE TITLE
Error with USB sound card when using Alsa for omxplayer & splash videos.

### ISSUE THREAD

**Issue by RWoof** [RetroPie/EmulationStation#218]
I have a USB sound card on my raspberry pi in my mini arcade cabinet because the speakers are not HDMI and the audio jack on the pi is terrible. I noticed my video splash screens were not playing any sound so I corrected that by editing /etc/init.d/asplashscreen and the line launching omxplayer to change -o both to -o alsa:hw:1,0

This fixes the sound but leaves an annoying error message after every boot that SDL could not be initialized by ALSA because the device or resource is busy. I'm assuming this is because alsa is in use playing my splash video as emulationstation is loading. I'm not sure if there is a way to hide or fix this error message? Other than the message, everything seems to function as it should, it's just annoying that the error text shows for a few seconds on the screen during the first time I launch a game after rebooting the pi.

Better support for USB sound cards would be much appreciated!

**Comment by hex007** [comment]
This is not technically a bug. It's an annoyance and will be treated as such. It is not high on priority list. 

Please post your es_settings.conf file.

You should also change `Settings > Sound Settings > OMX PLAYER AUDIO DEVICE`  to ALSA:HW:1,0

**Comment by RWoof** [comment]
I have my audio device already set as you described, here is my file contents as requested, thank you very much for the quick reply!

<?xml version="1.0"?>
<bool name="BackgroundJoystickInput" value="false" />
<bool name="CaptionsCompatibility" value="true" />
<bool name="DrawFramerate" value="false" />
<bool name="EnableSounds" value="true" />
<bool name="MoveCarousel" value="true" />
<bool name="ParseGamelistOnly" value="false" />
<bool name="QuickSystemSelect" value="true" />
<bool name="SaveGamelistsOnExit" value="true" />
<bool name="ScrapeRatings" value="true" />
<bool name="ScreenSaverControls" value="true" />
<bool name="ScreenSaverOmxPlayer" value="true" />
<bool name="ShowHelpPrompts" value="false" />
<bool name="ShowHiddenFiles" value="false" />
<bool name="ShowNetwork" value="false" />
<bool name="SortAllSystems" value="false" />
<bool name="StretchVideoOnScreenSaver" value="false" />
<bool name="UseCustomCollectionsSystem" value="true" />
<bool name="VideoAudio" value="true" />
<bool name="VideoOmxPlayer" value="true" />
<int name="MaxVRAM" value="100" />
<int name="ScraperResizeHeight" value="0" />
<int name="ScraperResizeWidth" value="400" />
<int name="ScreenSaverTime" value="60000" />
<string name="AudioDevice" value="Speaker" />
<string name="CollectionSystemsAuto" value="all,favorites,recent" />
<string name="CollectionSystemsCustom" value="" />
<string name="GamelistViewStyle" value="automatic" />
<string name="OMXAudioDev" value="alsa:hw:1,0" />
<string name="PowerSaverMode" value="default" />
<string name="Scraper" value="TheGamesDB" />
<string name="ScreenSaverBehavior" value="black" />
<string name="ScreenSaverGameInfo" value="start &amp; end" />
<string name="ThemeSet" value="ComicBook_4-3_SE-Wheelart" />
<string name="TransitionStyle" value="instant" />

**Comment by hex007** [comment]
@RWoof For posting code use three ` symbol followed by language (xml here) to start code block and three ` to end for proper formatting

**Comment by RWoof** [comment]
```xml
<?xml version="1.0"?>
<bool name="BackgroundJoystickInput" value="false" />
<bool name="CaptionsCompatibility" value="true" />
<bool name="DrawFramerate" value="false" />
<bool name="EnableSounds" value="true" />
<bool name="MoveCarousel" value="true" />
<bool name="ParseGamelistOnly" value="false" />
<bool name="QuickSystemSelect" value="true" />
<bool name="SaveGamelistsOnExit" value="true" />
<bool name="ScrapeRatings" value="true" />
<bool name="ScreenSaverControls" value="true" />
<bool name="ScreenSaverOmxPlayer" value="true" />
<bool name="ShowHelpPrompts" value="false" />
<bool name="ShowHiddenFiles" value="false" />
<bool name="ShowNetwork" value="false" />
<bool name="SortAllSystems" value="false" />
<bool name="StretchVideoOnScreenSaver" value="false" />
<bool name="UseCustomCollectionsSystem" value="true" />
<bool name="VideoAudio" value="true" />
<bool name="VideoOmxPlayer" value="true" />
<int name="MaxVRAM" value="100" />
<int name="ScraperResizeHeight" value="0" />
<int name="ScraperResizeWidth" value="400" />
<int name="ScreenSaverTime" value="60000" />
<string name="AudioDevice" value="Speaker" />
<string name="CollectionSystemsAuto" value="all,favorites,recent" />
<string name="CollectionSystemsCustom" value="" />
<string name="GamelistViewStyle" value="automatic" />
<string name="OMXAudioDev" value="alsa:hw:1,0" />
<string name="PowerSaverMode" value="default" />
<string name="Scraper" value="TheGamesDB" />
<string name="ScreenSaverBehavior" value="black" />
<string name="ScreenSaverGameInfo" value="start & end" />
<string name="ThemeSet" value="ComicBook_4-3_SE-Wheelart" />
<string name="TransitionStyle" value="instant" />
```

**Comment by joolswills** [comment]
You can edit your posts on github btw - the earlier post could

**Comment by joolswills** [comment]
keyboard fail. I will edit your earlier post - you can edit earlier posts on github - rather than reposting.

**Comment by hex007** [comment]
@RWoof Can you run ES from ssh and paste the error log that you see? It would help sort what problem you are having.

**Comment by RWoof** [comment]
I took a pic of it before, the error message luckily was there when exiting emulationstation.

![img_2513](https://user-images.githubusercontent.com/25894191/29644306-56dd0d7a-8832-11e7-99ed-9163df6ac6ca.JPG)

**Comment by hex007** [comment]
@RWoof try this command and paste the output

`aplay -l`

**Comment by RWoof** [comment]
**** List of PLAYBACK Hardware Devices ****
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by hex007** [comment]
@RWoof Your config is on point. The only possible problem causing this is your splash screen is running when ES loads up. 

The solution that I use on my system (Pizero + USB audio) is to kill omx player before ES is loaded. You can try that by editing the startup script which launches ES on boot and make it kill omxplayer. That should take care of your problem.

**Comment by RWoof** [comment]
If I do this however it would kill my video splash as it's playing as soon as Emulationstation begins to load, correct? That might be more of an issue for me than the error message at this stage.

I was wondering if there is a way to prevent ES trying to re-initialize Alsa as it loads if it is already in use or perhaps a way to allow multiple processes to use Alsa at the same time? Sorry if these are not intelligent questions, I'm fairly new to this!

**Comment by hex007** [comment]
I dont think that is possible presently. If Alsa is busy it will not initialize. Adding a method to reinit it on failure will yield errors in loop if wrong device is selected.

Another side effect of this is Gamelist scroll sounds are not available.

What you can do is change device and change it back to reinit the ALSA, which is not ideal either.

**Comment by RWoof** [comment]
Thank you very much for your help!

**Comment by hex007** [comment]
You can close the issue if you are okay with it.
