### ISSUE TITLE
Video screensaver doesn't trigger on Instant PS

### ISSUE THREAD

**Issue by pjft** [RetroPie/EmulationStation#223]
Hi @hex007 .

Sorry for the trouble.

I was testing #222 this morning and I didn't manage to get the video screensaver to trigger on the Instant PS mode - at least on OMX Player.

I know we had tested a build where that was working, but I was checking the code and nothing seems to have been changed from what was committed for the fix, so I'm at a loss.

I also tested the current live build (2.6.0) and couldn't seem to trigger the video screensaver (once again, only tested with OMX) with the Instant transition, so I'm supposing something changed in the code between our last test and the committed code.

It's not urgent, but just wanted to give you the heads up. 

Unfortunately I'm unable to investigate further or test anything related to ES for the next few weeks as I'm moving countries in a few weeks and I just literally shipped the Pi with the house contents for the moving company to take them.

Hope this helps.

**Comment by hex007** [comment]
@pjft I forced VSS with OMX player with PS disabled and it doesnt work. Something has broken ES with omx.

@joolswills When was the binary last updated?

**Comment by joolswills** [comment]
18/08

**Comment by pjft** [comment]
I compiled the most recent code and it wasn't working either, so I'm not
sure it's a binary thing.

The code also doesn't seem to be that changed from the PS fixes commit, so
my guess is that we missed something.

How's it with VLC?

**Comment by hex007** [comment]
@pjft  I think you should change the title.

I have not tried using VLC. 

It runs as expected if I run omx using ssh while ES is running

**Comment by pjft** [comment]
Sorry, maybe I'm not being clear. I submitted this because this was
happening in the main binary, not on my code only.

That being said if you can't replicate it it might certainly be something
on my end.

**Comment by hex007** [comment]
I tested it on my Pi3 and seems to work well with 2.6.0

**Comment by pjft** [comment]
Sounds good. Do close it then, or I'll close it later. I won't have my Pi
for the next few weeks, so I'll reopen afterwards if it does happen.

Thanks.

Either way, I'd definitely appreciate your review on that PR, in case I did
mess something up there.

Cheers.

**Comment by hex007** [comment]
@joolswills can you close this issue?

**Comment by pjft** [comment]
Just to confirm, though, I'm not talking about triggering it via select as that defeats the purpose of the PS behavior:)

I'm referring to having let it wait for the timeout, in instant mode, and the video screensaver not having been triggered. 

That being said, it could certainly be something on my end, so no worries. Sorry about the false alarm.

**Comment by hex007** [comment]
Yes I tested it with timeout.
