### ISSUE TITLE
Wanted: Origin and Aligment for <helpsystem>

### ISSUE THREAD

**Issue by EctoOne** [RetroPie/EmulationStation#224]
Since <origin> was added for carousel lately, i wonder if it would be possible to add it for <helpsystem> as well. And to be able to fully center it dynamically when switching between systemview and basic-/detailed-/videoview it would be nice if <aligment> could also be added.

**Comment by Koerty** [comment]
Moved this here from your topic on the forum : 

datetime

(to have the same properties as the other metadata fields)

    backgroundColor - type: COLOR;
    origin - type: NORMALIZED_PAIR.
    alignment - type: STRING.

textlist

    backgroundColor - type: COLOR;

helpsystem

    backgroundColor - type: COLOR;
    origin - type: NORMALIZED_PAIR.
    alignment - type: STRING.

**Comment by Koerty** [comment]
@EctoOne What do you mean by "alignement" for the helpsystem ? You can already set the origin to "1 0" to align the helpsystem to the right.

**Comment by jrassa** [comment]
@Koerty, by alignment, I believe he is referring the alignment of elements within the HelpComponent.  I believe currently they are rendered from the left edge of the component flowing right.  Functionally it would be similar to the the alignment option on TextComponent and allow the theme to specifiy either "left", "right", or "center".

**Comment by EctoOne** [comment]
Yeah, I thought that the help system is an element that can be resized, but I just looked at the themes.md and noticed that it has no options to do that. So I don't know if it is possible to add that.
I only cared for origin back then because It was annoying to center the help system over and over again when I was trying different fonts.

Since we are speaking about missing options, I recently tried to work on a theme and noticed that we can't rotate the gamelist and videos.
The image I wanted to use as background was some sort of comic page but it has no straight lines within the panels, so it looked really weird with the straight components.

**Comment by Koerty** [comment]
But if you align all the text to the right within the help prompt, then it will look like the text is associated to the button on its right, which is misleading for the user.

**Comment by EctoOne** [comment]
It obviously should align the icons too not just the text. Example: If I set origin and position to 1 1 on something like the gamelist with alignment set to left, there will always be some space on the right side. I assume that will be the same if I set the origin of the helpsystem to 1 1, but I might be wrong since I have no idea how the helpsystem is rendered, especially since it is different for the carousel and the other views. If you could confirm that it properly aligns with origin 1 1, the request for alignment is obsolete.
Thanks for looking into this and adding origin already.

**Comment by EctoOne** [comment]
Sounds like the size (width in this case) is dynamic then, good. I guess alignment is unnecessary then, thanks!
