### ISSUE TITLE
Omxplayer snaps showing on top of theme.

### ISSUE THREAD

**Issue by RWoof** [RetroPie/EmulationStation#228]
Unlike the default video player, when omxplayer is enabled it seems to play video snaps on top of the theme background images while viewing the game list  rather than under. This means themes like magazine madness that normally show snaps inside tv monitors will not look right.

**Comment by Darknior** [comment]
Yes it's normal, you don't read the forum before posting here.
We can't do nothing for this at this time, i you want to use this theme, use VLC player.
