### ISSUE TITLE
Fontsize of menu's too large for smaller screens

### ISSUE THREAD

**Issue by zigurana** [RetroPie/EmulationStation#234]
So, I am using ES on an old 1024x768 LCD monitor, and some menus simply do not fit.
Worst case example:
![font_issue](https://user-images.githubusercontent.com/6103768/29889698-6a067b00-8dc5-11e7-9524-92fdd1f44260.png)

Ideally, two things happen: 
1) we would implement a more optimal font size detection, derived from the actual screen size / aspect ratio.
2) we have another look at the menus, to see if we can simplify the strings used there.

**Comment by hex007** [comment]
#232 Can you try this?

**Comment by pjft** [comment]
Figures as much. Thanks for testing that on that screen ratio. Darn that's
an ugly menu.

See if @hex007 's proposal helps, but either way happy to revisit those
strings, and even font size for those.

Thanks.

**Comment by hex007** [comment]
I have modified the Menu sizes so those strings should not create a problem now. 

@zigurana I think you are behind on commits on master.

**Comment by zigurana** [comment]
gah! merged 15 hours ago... Let me check

**Comment by zigurana** [comment]
@hex007 You are correct! Good work man!
(Still considering different strings for that menu though...)
