### ISSUE TITLE
Emulationstation crashes when entering system menu

### ISSUE THREAD

**Issue by xTeixeira** [RetroPie/EmulationStation#237]
Emulationstation crashes when entering the rom list screen for any installed system.
Tested this in 2 different computers running Ubuntu Gnome 17.04 with emulationstation installed from retropie installer as per usual retropie installation. Both computers using the nvidia proprietary driver (version 375 installed directly from Ubuntu repos).
I've installed the emulationstation-kids fork from retropie installer and the crashes don't happen there.
I've noticed that if I've just booted the PC up, the rom list will sometimes load, but emulationstation then crashes when I press B to go back to the main menu.
I also tested with Openbox, in case it was gnome's fault, and the crash happens anyway.
I'm attaching a stack trace of the crash.
[stacktrace.txt](https://github.com/RetroPie/EmulationStation/files/1267886/stacktrace.txt)

**Comment by joolswills** [comment]
When did you last update ?

**Comment by xTeixeira** [comment]
About 3 days ago, as far as I can remember, is it already fixed?

**Comment by joolswills** [comment]
Yes. Best to update first before opening a ticket.

**Comment by xTeixeira** [comment]
I see. I'll close this then, sorry for the misunderstanding.

**Comment by joolswills** [comment]
Please can you update and verify though - just in case it's not the same issue.

**Comment by xTeixeira** [comment]
Sure. As soon as I get the chance, which should be in about 5 hours when I get off from work.
