### ISSUE TITLE
Scraping takes forever

### ISSUE THREAD

**Issue by johnjelinek** [RetroPie/EmulationStation#25]
When I scrape, it takes forever loading the next item, this is the error:
```
lvl0:   GamesDBRequest - Error parsing XML.
        Start-end tags mismatch
```

**Comment by johnjelinek** [comment]
Note: if I pick `THEARCHIVE` scraper, ES crashes.

**Comment by smartroad** [comment]
I have been unable to get to http://thegamesdb.net/ so that could be part of the issue? If you browse to the site I get 'Website is offline' errors

**Comment by joolswills** [comment]
Yeh the website is offline. This would be best posted to the forum first - note that we are unlikely to do any work on the ES scraper - sselph's scraper is a lot quicker so that is recommended (may also be non working is the gamesdb is down)

**Comment by johnjelinek** [comment]
How do I use sselph's scraper?



—

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-setup/wiki/scraper

**Comment by johnjelinek** [comment]
Great, thanks.



—

**Comment by joolswills** [comment]
I will leave this open for any one else to reference. Hopefully the site will come back soon.
