### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by KitchUK** [RetroPie/EmulationStation#26]
In noticed that the font within emulation station has jagged edges on random lines and seemingly random letters (this is without any boxart). 

Anyone know what is causing this?

**Comment by HerbFargus** [comment]
Font is defined by the theme, not emulationstation. Post a screenshot to show what you're trying to explain

**Comment by joolswills** [comment]
I guess its just to do with the rendering. We have no plans for overhauling core functionality in ES on this fork btw.

**Comment by joolswills** [comment]
Closing due to no feedback.
