### ISSUE TITLE
Cap FPS to 60

### ISSUE THREAD

**Issue by hex007** [RetroPie/EmulationStation#272]
Currently FPS is not capped. If running ES on a proper computer then FPS reaches sky high. Capping FPS might reduce cpu usage too.

![screenshot from 2017-10-27 10-48-58](https://user-images.githubusercontent.com/1689246/32129837-7a1574d4-bb41-11e7-9f4e-1ad4c32a75d9.png)

**Comment by joolswills** [comment]
Are you not able to enable vsync ? Runs at 60fps on my Linux PC (screen refresh rate). Don't think it needs to be capped unless there are some systems that can't do vsync ?

**Comment by psyke83** [comment]
Normal vsync should now be enabled by default for all, so this should only be a problem with "--vsync off". If you cap the framerate for vsync off, 60fps may be the wrong rate depending on the monitor/TV configuration.

I did some research, and the problem with "late swap tearing" was that GLES doesn't support the extensions to implement the feature (GLX_EXT_swap_control_tear or WGL_EXT_swap_control_tear.).

See: https://wiki.libsdl.org/SDL_GL_SetSwapInterval

Poking around the source, it seems that the above function may not report an error condition when attempting to set late swap tearing in a GLES context (but the X11 OGL and Windows OGL drivers do). 

Even the SDL2 GLES tests don't even try to set it:
Compare: https://github.com/RetroPie/SDL-mirror/blob/master/test/testgl2.c#L292
To: https://github.com/RetroPie/SDL-mirror/blob/master/test/testgles2.c#L574

**Comment by psyke83** [comment]
The above was more relevant to a Pi, but the same issue could have manifested on a Linux desktop if building against GLES or if your GL driver doesn't support late swap tearing but SDL_GL_SetSwapInterval was also giving an erroneous return code.

Try updating your source and make sure it includes this commit: https://github.com/RetroPie/EmulationStation/commit/cdda38d05ba6e23041da1af4d5c4cbda2c78c605

**Comment by pjft** [comment]
For the record, I think @hex007 mentioned in the forums that he noticed this after updating his video drivers, on a Linux set up. May be unrelated but thought I'd mention it.

**Comment by hex007** [comment]
I installed NVidia drivers on my Linux x64 and noticed this problem. Removing the drivers restored it to 60fps. @joolswills Do you have nvidia graphics on your linux system for comparison?

**Comment by joolswills** [comment]
no.

**Comment by psyke83** [comment]
@hex007 

I saw your forum post. Can you try reverting https://github.com/RetroPie/EmulationStation/pull/270?

If that's the problem, we could change the code so that it only tries to set late swap tearing if it's using GL, so it won't break the Pi. I'm setting up a temporary vmware to try an x64 build (but only against the vmware 3d driver, and I don't have nvidia hardware).

**Comment by tomaz82** [comment]
Could it be your nvidia linux drivers forcing vsync to always off? Then it doesn't matter what ES tries to do, it will stay off.

**Comment by hex007** [comment]
@psyke83 I reverted to 10 commits back and it still looks same. I am guessing @tomaz82 's idea might be possible. I am using fedora linux and if it works as expected on Ubuntu I cannot complain.

**Comment by psyke83** [comment]
Well, I'm seeing the same problem on VMWare Player with latest master branch -- but I don't think it's related to the two recent vsync-related commits. I'm testing with Debian stretch, so perhaps it's an issue with the default SDL 2.0.6. I'll try stable or a few revisions before to see if I can see a difference & will let you know if I find anything.

**Comment by borestad** [comment]
![image](https://user-images.githubusercontent.com/286455/39591339-bfec71d2-4f03-11e8-8da3-90f87ee17692.png)

This is me, running on Ubuntu 18.04. Skyhigh cpu and currently have seen tops of over 1300fps ...this really needs to be capped somehow.

**Comment by tomaz82** [comment]
It already is, it's called v-sync, either you have that off in options, or your drivers force it off.
