### ISSUE TITLE
Lubuntu 16.04 compilation problem

### ISSUE THREAD

**Issue by emersonnovais** [RetroPie/EmulationStation#284]
Hi, guys. I download this version and tried to compile in Lubuntu 16.04 and the make canot compile. My terminal output is below. I checked the needed required packages and they are all up to date. I don't know what to do. Help, please:

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so  
-- Looking for FreeImage...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'freeimage'
--   No package 'freeimage' found
-- Found FreeImage: optimized;/usr/lib/x86_64-linux-gnu/libfreeimage.so;debug;/usr/lib/x86_64-linux-gnu/libfreeimage.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   date_time
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.47.0") 
-- Checking for module 'libvlc>=1.0.0'
--   Found libvlc, version 2.2.2
-- VLC library found
-- Found VLC: /usr/include/vlc  
-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.1.0") 
CMake Error at external/CMakeLists.txt:5 (add_subdirectory):
  The source directory

    /home/retrocon-os/Downloads/emulationstation_master2/EmulationStation-master/external/pugixml

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!

**Comment by pjft** [comment]
When you use git clone you need to use the --recursive flag, or you need to initialize the sub modules now.

**Comment by emersonnovais** [comment]
pjft, thanks for information. It's worked. The new EmulationStation is so good than the repository version.

**Comment by pjft** [comment]
Which particular repository? They should be the same, unless you're referring to the development version?

**Comment by emersonnovais** [comment]
Is the Ubuntu repository version. The package is very old and is based on the original version of Aloshi from four years ago. I tried your version just because is updated. The Recalbox version seems to be discontinued and are very good mainly the option of change the emulator on own EmulationStation interface but I haven't found none information about how to configure it.
