### ISSUE TITLE
[Experimental_build] "Jump to the letter" feature it's missing in the Kiosk mode

### ISSUE THREAD

**Issue by LodanZark** [RetroPie/EmulationStation#286]
I'm using this commit version: f8a297ff516eed178e1fac7ef233c340ad1c1f17 and the feature "jump to the letter" it's missing in the kiosk mode (probably it's missing in kids mode as well)

**Comment by zigurana** [comment]
See #282

**Comment by LodanZark** [comment]
Awesome work, it solved my issue and improved a lot my experience ;) thank you very much
I will close this ticket
