### ISSUE TITLE
Implement HDMI CEC remote support

### ISSUE THREAD

**Issue by majokkoSleepover** [RetroPie/EmulationStation#288]
This enhancement has already been mentioned on the ES github [issue 421](https://github.com/Aloshi/EmulationStation/issues/421), and also @dillbyrne came out with something pretty neat.

Implementing HDMI CEC remote support would provide a better out of box experience  IMHO.

**Comment by danielandross** [comment]
Plus 1. When I start emustation only to get to kodi for media playback i do not want to connect a gamepad only to select kodi.

**Comment by clironpean** [comment]
Plus 1. It would be perfect !

**Comment by jrassa** [comment]
implemented in #292 and #300
