### ISSUE TITLE
Deleting game while in custom group causes SegFault

### ISSUE THREAD

**Issue by redneckmatt** [RetroPie/EmulationStation#289]
**Problem definition:**
Deleting a game from the system from inside a custom collection causes the interface to crash. Repeatable.

Code current as of 11/6/2017

**Problem recreation inside EmulationStation:**
- create custom collection
- add game to this custom collection
- complete adding games to collection
- navigate to collection
- open the Options menu for the game you wish to fully delete
- select "Edit this game's metadata"
- navigate down to "Delete"
   (At this point normally you would see the game disappear in the background, and the next game would be selected. This doesn't happen, and you're still left in the options screen.)
- exit out of the options menu via "B" on the controller (or whichever key you have mapped)
- EmulationStation will crash and a Segmentation Fault will be shown on the command line.

**Other specifics:**
- there were other games in the collection, and it wasn't the first or last entry in the collection
- the game wasn't listed in favorites

**Comment by pjft** [comment]
Thanks for the thorough description.

The moment you say

> exit out of the options menu via "B" on the controller (or whichever key you have mapped)

and then it crashes, I'm pretty much sure that the issue will be in us trying to get or set a cursor that's no longer valid. I tested and debugged plenty of such scenarios, which exhibited similar behavior, hence my gut feeling about it.

I'll take this on as soon as reasonably possible - apologies for the trouble here, and thank you very much for taking the time to report this.

**Comment by pjft** [comment]
Thanks.

There must be a problem with `CollectionSystemManager::deleteCollectionFiles(FileData* file)`, as that was put there precisely for that particular use case.

I'll try to look into that.

**Comment by pjft** [comment]
Hi.

I just submitted a PR that should fix this.

Do you have a way to test #290 and see if it no longer happens?

**Comment by pjft** [comment]
Thanks @joolswills for the quick turnaround.

In that case, @redneckmatt could you install the ES dev version and check whether it's fixed? I'd like to confirm that this fix addresses the exact issue you were having, which I think I narrowed down but want to make sure I'm not fixing something else :)

Have a good evening everyone.

**Comment by redneckmatt** [comment]
Loaded up the dev branch via the emulationstation menu.
Reads as Emulationstation v2.7.0RP

For a game that has been previously scraped:
- added a game to the custom collection
- closed editing the custom collection
- deleted the game
 dumped to terminal.

`terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 4294967295) >= this->size() (which is 1)
Aborted`


If the game had NOT been scraped, it deletes as expected with no errors.

**Comment by pjft** [comment]
Hm. And that didn't happen prior to this change, I take it? That sounds like a substantially different problem, for which I have little to no idea about. That I'll have to dig into a bit more. 

Can you share a bit more detail around how/when exactly does it crash? Is it the same as before, when exiting the menu? Does the have disappear from the list?

Thanks.

**Comment by redneckmatt** [comment]
Referencing the original post, prior to this change it was a drop to a segfault. Now there is an error message being shown.

I hadn't tested deleting a non-scraped game from a collection before.

**Comment by pjft** [comment]
Thanks, and apologies but I need a bit more to work with. What you're saying is that prior to the change, deleting a scraped game resulted in a segfault and now results in this message you posted, is that it?

You had mentioned that the deleted game wasn't being removed from the list, and the next one selected. Is that still the case?

Thanks.

**Comment by pjft** [comment]
Interesting. 

I cannot replicate that in this new version, unless it is the last game in a system - then I get the exact same message. That is a different error, though, and happened before as well when you deleted the last game from a system.

If that's not what you're experiencing, can you create a video from your phone and send it over, so I can try to see what I may be missing?

Thanks.
