### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by WXDFever** [RetroPie/EmulationStation#291]
Hello, guys. I am a newbie for retropie and I am just wondering if ES can support video preview in emulator selection memu.

For example as the picture below:

![example](https://user-images.githubusercontent.com/29010142/32534412-6a378e5a-c490-11e7-8897-df14e6ba4ed8.jpg)

can the picture in red frame replaced by a video?

I am just a newbie, not sure if it's a silly question. Thanks in advance

**Comment by joolswills** [comment]
You should use the RetroPie forum for support.
