### ISSUE TITLE
Controller in Windows - Shoulder buttons and Trigger Buttons

### ISSUE THREAD

**Issue by altiereslima** [RetroPie/EmulationStation#296]
Shoulder buttons do not perform page up/down actions in Windows. Also when setting the controller by pressing the button LEFT TRIGGER or RIGHT TRIGGER  it recognizes it as two commands.

**Comment by emersonnovais** [comment]
I have the same problem too. The tags of page up and page down is not recorded in the es_input.cfg file. I had to set it manualy adding the tags

		<input name="pagedown" type="button" id="5" value="1" />
		<input name="pageup" type="button" id="4" value="1" />

being that the buttons corresponds my shoulders button.

**Comment by altiereslima** [comment]
Change "pageup" by "leftshoulder" and  "pagedown" by "rightshoulder" in DateTimeComponent.cpp and InputManager.cpp, fixes the page up/down actions in Windows.

**Comment by cmitu** [comment]
Should be fixed in https://github.com/RetroPie/EmulationStation/pull/631.
