### ISSUE TITLE
parenthesis removal and other tweaks

### ISSUE THREAD

**Issue by joolswills** [RetroPie/EmulationStation#3]
The current behaviour of ES is to remove content in parenthesis in rom names. I believe this is confusing, and would be better to display the full name - especially when you have region info in rom names (or set information as with mame). I believe recalbox fork of ES also has changed this.

it's a one-liner, so wanted to make sure you are happy for me to do this.

I'd like to make other changes too - such as look into enabling gameslist refresh without a restart, and so on.

I will do them as pull requests if people are interested to review them/get notifications before merge.

@petrockblog @herbfargus

**Comment by joolswills** [comment]
Unfortunately it looks like ES is truly dead for now, and is getting fragmented with forks, which is a shame. I hope we can at some point we can push stuff upstream but for now, it looks like we are on our own.

**Comment by HerbFargus** [comment]
Tis unfortunate but I guess gives us the liberty to customise it for our needs until its picked back up again. The above fixes sound valid to me.
