### ISSUE TITLE
Swap left analog and D-Pad

### ISSUE THREAD

**Issue by Protected** [RetroPie/EmulationStation#302]
How about a "hotkey" combination for swapping left analog and D-Pad (press again to swap back to normal) without having to manually reconfigure the entire controller? It would be a godsend for controllers that have the D-pad at the bottom. For example, if playing a SNES game, swap the D-pad into the analog stick so it's in a comfortable position. If playing PSX, put the actual analog back into the analog stick.

Hope this is the right place to make this suggestion!

**Comment by pjft** [comment]
I think there are reasons for that not to be the case, but there's an option in the RetroPie-Setup configuration editor that does what you need - it sets the analog joystick to also send dpad inputs. 

https://retropie.org.uk/forum/topic/5609/use-analogue-as-digital-controls

I have it set for all cores, and disable it for PSX and N64.

**Comment by Protected** [comment]
Got it, thanks a lot!
