### ISSUE TITLE
Implement a Full kiosk mode, completely hiding the start and select menus

### ISSUE THREAD

**Issue by SerjTargarien** [RetroPie/EmulationStation#304]
Hi, this is not an issue per se but a request, so if it doesn't belong here it can be deleted.

It would be great, now that kid and kiosk mode are implemented, to have a "full kiosk"  mode so no EmulationStation settings or search menu can be accessed whatsoever. I ask for this specifically for people who have modified their pi with a soft-shutdown button and can turn off the system that way. That way EmulationsStation only acts as a way to select the games, as you can go back to it or turn of the system by pressing physical buttons in the case, and you get a perfect system for kids and non-techy adults alike. Also, now that we have a way to start EmulationStation directly in one system this would be a great way to create really easy to use per system miniconsoles. 

Would it be too difficult to implement? Too niche of an audience to do it? Let me know what you think.

**Comment by hex007** [comment]
The correct place for discussions is the forums -> https://retropie.org.uk/forum/
