### ISSUE TITLE
A suggestion maybe

### ISSUE THREAD

**Issue by WXDFever** [RetroPie/EmulationStation#307]
Hello, guys. Not sure if this is the right place to ask, I am a newbie for retropie and I am just wondering if ES can support video preview in emulator selection memu in future.

![emulator select](https://user-images.githubusercontent.com/29010142/32871871-8387524e-cabe-11e7-816f-180daed1fefc.jpg)

can the picture in red frame replaced by a video in future version of ES?
Thanks in advance

**Comment by WXDFever** [comment]
Well, I know Attract Mode(AM) can support this, but I don't like AM, it's not as friendly as ES, lol

**Comment by Jakobud** [comment]
Themes can support videos. I'm not sure how but I've seen it in the documentation.

**Comment by hex007** [comment]
Kindly submit suggestions on the forums  https://retropie.org.uk/forum/

@joolswills Can be closed?
