### ISSUE TITLE
Scraping Failure: NES/SNES

### ISSUE THREAD

**Issue by darklightindigo** [RetroPie/EmulationStation#312]
Received multiple reports on TGDB forums that scraping NES and SNES titles returns no results. Tracked back to apparent regression during boost cleanup 2-3 weeks ago.

https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/scrapers/GamesDBScraper.cpp

It can’t be a coincidence that lines 40 and 66 used curly brace openers instead of open-parentheses for the acronyms:
40 { NINTENDO_ENTERTAINMENT_SYSTEM, “Nintendo Entertainment System { NES)” },
…
66 { SUPER_NINTENDO, “Super Nintendo { SNES)” },
_________________________________________
To correctly parse the strings, line 40 should be
`{ NINTENDO_ENTERTAINMENT_SYSTEM, “Nintendo Entertainment System (NES)” },`

Whereas line 66 should be
`{ SUPER_NINTENDO, “Super Nintendo (SNES)” },`

**Comment by tomaz82** [comment]
Good find! I'll fix it right away.

**Comment by tomaz82** [comment]
https://github.com/RetroPie/EmulationStation/pull/313

**Comment by darklightindigo** [comment]
Thank you!  Everyone at TGDB will be happy to hear this.  :smile:
