### ISSUE TITLE
Crash after remove last game in Favorites list

### ISSUE THREAD

**Issue by leosmeira** [RetroPie/EmulationStation#317]
terminate called after throwing an instance of 'std::out_of_range'
  what(): vector::_M_range_check: __n (which is 4294967295) >= this->size() (which is 1)
Aborted

**Comment by pjft** [comment]
Thanks.

Can you check if it happens in 2.6.5? There's a similar report here:

https://retropie.org.uk/forum/topic/14491/crash-removing-favourite

so want to check whether it'd be the same or not.

Thanks.

**Comment by leosmeira** [comment]
I tested now and the same error occurred in v2.6.5.

Tested in: v2.7.3RP and v2.6.5

**Comment by pjft** [comment]
Huh. Thank you. Maybe you'd want to join that thread, as it might be that steeeb misremembered that.

I'll look into that shortly, hopefully.

**Comment by xadox-1st** [comment]
Same for me.
