### ISSUE TITLE
Themes page says use RetroPie config.

### ISSUE THREAD

**Issue by 00sivan** [RetroPie/EmulationStation#327]
I know this is the RetroPie page, but it's pretty much all that comes up in search anymore because it's so popular. Building ES on Windows would be easier if the RetroPie themes page offered links to the themes rather than only making them available inside the RetroPie config which is not available for Windows. Thanks for sharing!

**Comment by jrassa** [comment]
@00sivan All of the themes listed on the RetroPie theme page can be downloaded directly from their respective github pages using the "Download ZIP" option under the "Clone or download" button.  Also, you can check out [RetroCake](https://retropie.org.uk/forum/topic/13828/retropie-like-script-for-windows-7-8-and-10-retrocake), which is a set up scripts for Windows that functions similar to RetroPie and has the ability to install themes.

**Comment by 00sivan** [comment]
Amazing. Thank you. I will check it out.
