### ISSUE TITLE
Ability to hide files

### ISSUE THREAD

**Issue by wolf-sigma** [RetroPie/EmulationStation#33]
Hello,

I wanted the ability to hide files, so I added this feature to a fork of upstream 2.0.1a. If this is of interest for the RetroPie fork, I can do a cherry-picked PR.

https://github.com/t3hi3x/EmulationStation/commit/196d9175c38da86f778e6a1af4fc8abb09270eea

It works in a few ways:
- Under "Edit Metadata" there is an option to hide the file - it will disappear when hit Save
- It then adds a `<hidden>true</hidden>` tag to gamelist.xml
- You can then show the hidden files by putting a `<bool name="ShowHiddenFiles" value="true" />` in es_settings.cfg

Thoughts?

**Comment by zigurana** [comment]
I like it!
Which was exactly the reason I implemented something very similar in my Kid friendly ES: https://github.com/RetroPie/RetroPie-Setup/wiki/Child-friendly-EmulationStation
:-)

**Comment by brettwgreen** [comment]
Round it off by adding a menu item in the Emulation Station - UI settings to turn Show Hidden Files on/off so users don't have to manually edit the es_settings.cfg to get the hidden games back.

**Comment by t3hi3x** [comment]
At this point, I think it's good enough for an MVP. However, if this gets committed to RetroPie, I'd be willing to reconsider :)

**Comment by t3hi3x** [comment]
I got bored and just added it. Was pretty easy:

https://github.com/Herdinger/EmulationStation/commit/8486646ca9d8ddace187932ce8d66dc37471481c

**Comment by brettwgreen** [comment]
It's a useful feature... I hope they pull it. I'm too lazy to do my own build :)

**Comment by hex007** [comment]
@zigurana @joolswills Is this of any interest? I can submit a PR if it is else this can be closed as there has been no updates on this for more than a year.

**Comment by Darknior** [comment]
Yes if it can be merge with the officiel build it can be really cool for me too :)
Hide file like on Kid friendly ES is really important i think.

**Comment by pjft** [comment]
@wolf-sigma Are you planning on submitting the PR to the RetroPie fork?

**Comment by zigurana** [comment]
Functionality equivalent to what was requested here has been introduced with #252. I believe this van be closed?

**Comment by jrassa** [comment]
implemented in #252
