### ISSUE TITLE
Feature Request: Expose name of selected game as "md_name" text element

### ISSUE THREAD

**Issue by wesmckiel** [RetroPie/EmulationStation#330]
While the title of the selected game is highlighted in the game list, it would also make a strong design element in the layout of the basic, detailed, or video views. It makes sense to place the single most significant piece of data regarding the game (it's title) in a prominent framing position relative to all the other information.

At any rate, I keep wanting to use the game name as a piece of metadata, just like "genre" or "publisher", and it isn't an option (as far as I know).

**Comment by hex007** [comment]
Please share ideas on Forums. This is an issue tracker for EmulationStation only
