### ISSUE TITLE
Error: Controller Xarcade-to-Gamepad Device not configured

### ISSUE THREAD

**Issue by cgmartin** [RetroPie/EmulationStation#332]
_(I'm unsure which component is responsible for retroarch-joypad configurations, so if this isn't the correct project please let me know and I'll close/move this issue.)_

I am using the [Xarcade2Jstick](https://github.com/petrockblog/Xarcade2Jstick) service to register an XArcade Tankstick as two gamepad (udev) devices. When I "Configure Inputs" to add both gamepads, the controls work fine within the EmulationStation UI (and retroarch menus), but when launching any mame libretro core, I see a notification message: "Controller Xarcade-to-Gamepad Device (0/0) not configured", and the gamepads are not usable in MAME.

I noticed that after EmulationStation configured inputs, it wrote the following files to this path:
```
arcade:/opt/retropie/configs/all/retroarch-joypads$ ls
android  configure  dinput  hid  linuxraw  Makefile  parport  qnx  sdl2  udev  x  
"Xarcade-to-Gamepad Device 1.cfg"  "Xarcade-to-Gamepad Device 2.cfg"  xinput
```

...and when relaunching the mame game with verbose runcommand logging:
```
[INFO] [udev]: Plugged pad: Xarcade-to-Gamepad Device 1 (0:0) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event14) supports 0 force feedback effects.
[INFO] [Autoconf]: 195 profiles found.
[INFO] [Autoconf]: no profiles found for Xarcade-to-Gamepad Device 1 (0/0).
[INFO] [udev]: Plugged pad: Xarcade-to-Gamepad Device 2 (0:0) on port #1.
[INFO] [udev]: Pad #1 (/dev/input/event15) supports 0 force feedback effects.
[INFO] [Autoconf]: 195 profiles found.
[INFO] [Autoconf]: no profiles found for Xarcade-to-Gamepad Device 2 (0/0).
[INFO] [Joypad]: Found joypad driver: "udev".
```

EmulationStation v2.7.4RP

**Comment by cgmartin** [comment]
I was able to get it working by moving the two "Xarcade-to-Gamepad Device *.cfg" files into the `/opt/retropie/configs/all/retroarch-joypads/udev/` folder. 

I am unsure which system writes these joypads cfg files, but there may be a bug there or in the path mapping of config profiles when launching a core.

**Comment by cmitu** [comment]
This doesn't look like an ES issue, but a RetroArch configuration one.
