### ISSUE TITLE
Enhancements to scraping/gamelist utility

### ISSUE THREAD

**Issue by johnmanko** [RetroPie/EmulationStation#335]
Here are a few enhancements to the scraping utility that I think are worth adding.

On the scraping menu, add the following option:
* Auto Select Exact Matches & Skip Conflicts (This option will auto-select a result when it's name is an exact match for the search term, and it will skip that game in any other case.  This is great for unattended scraping where you want to come back only have to worry about resolving true conflicts.)

Utilities to add:
* Rename game files using gamelist/scrape name (should allow system selection, maybe disable arcade/fba/neogeo systems)
* Remove orphaned gamelist entries (should allow system selection)
* Remove orphaned downloaded images  (should allow system selection)

**Comment by joolswills** [comment]
Please use the forum for feature requests as detailed when opening an issue.
