### ISSUE TITLE
Hidden feature not working?

### ISSUE THREAD

**Issue by duiz** [RetroPie/EmulationStation#339]
I noticed in the latest Windows build that there is a new Hidden toggle. However when choosing Yes on hidden, the games still remain in the gamelist.

**Comment by emersonnovais** [comment]
duiz, I have the same issue with the Linux version.

**Comment by Darknior** [comment]
You must change your ES MODE to KIOSK or KID to hide the games you have selected.
In NORMAL mode you can see all the games.
