### ISSUE TITLE
Runtime Customizable Help Labels/SVGs?

### ISSUE THREAD

**Issue by Jakobud** [RetroPie/EmulationStation#340]
So, the help text at the bottom of the screen is good and helpful. But they are hard coded, right? You can't customize them right?

I'm asking because I have a RetroPie setup with only an NES controller. There is no X or Y or Shoulder Buttons. But the help text still refers to them.

It would be amazingly convenient to be able to custom the labels just by editing a CFG or something.

At one time I had a Genesis controller hooked up to my RetroPie for Genesis games. When I had friends play it they were super confused on why the Emulation Station buttons were "wrong". I tried to explain to them that even though it says "Select" use this button instead, etc. It was honestly a bit frustrating to use if you aren't familiar with ES.

I think that if you are going to give people the ability to remap controllers to use whatever buttons they want, then you need to give people the option to change the labels and button SVGs that are used. I think even if you use retropie-setup.sh to swap the A/B buttons for ES, I don't think it even swaps the buttons labels does it? The system could really use some more user-friendliness in this area. I don't know C++ but if I did I would contribute where I could.

**Comment by jrassa** [comment]
@Jakobud You can now override any of the button svgs by placing them in %home%/.emulationstation/resources

You can reference the files and directory structure [here](https://github.com/RetroPie/EmulationStation/tree/master/resources).

This will allow you to replace the button svgs with ones that match the controller you are using.

> I'm asking because I have a RetroPie setup with only an NES controller. There is no X or Y or Shoulder Buttons. But the help text still refers to them.

There isn't currently anyway to remove individual items from the help bar.  If you really want to remove them, the recommended option is to disable the help bar and then modify the theme you are using to have it rendered a customized help bar.

**Comment by Jakobud** [comment]
Great! Interesting... so are resources different depending on the theme?

**Comment by EctoOne** [comment]
No, you can only change them globally. Like @jrassa said, you can make your own help bar and add it to you theme. Some themes have a custom bar (I have at last seen one before but I'm not sure which theme it was).

**Comment by Jakobud** [comment]
Okay so in the resources I see stuff like "button_a.svg". How do I change for example what button starts the game?

**Comment by CookiePLMonster** [comment]
I can sadly confirm that it's either not working correctly or it's not documented well enough. It appears that .svg files from `%home%/.emulationstation/resources/ ` are not used.

I have not previewed the code, mind you, just based on the instructions given above.

**Comment by ExpatUK** [comment]
I _can_ confirm that it is working correctly as intended.

Reference files/folder structure:
/opt/retropie/supplementary/emulationstation/resources/help

Overwriteable by user:
/opt/retropie/configs/all/emulationstation/resources/help

This is wonderful for easily swapping in my PS3 glyphs :)

**Comment by joolswills** [comment]
thanks.
