### ISSUE TITLE
Favorites Only Lists "False" as Option

### ISSUE THREAD

**Issue by andrewvaughan** [RetroPie/EmulationStation#349]
I have confirmed on three separate RetroPie installations using EmulationStation.  When attempting to filter by Favorites, the only option is "False" resulting in only showing games that are _not_ a favorite.

A "True" option needs to be added (or, better yet, an option that provides better User Experience like "Favorited" and "Unfavorited").

**Comment by zigurana** [comment]
The filtering shows all available values, are you sure that any of your games have a favorites = true tag in their Metadata description?

**Comment by zigurana** [comment]
The filtering shows all available values, are you sure that any of your games have a favorites = true tag in their Metadata description?

**Comment by zigurana** [comment]
The filtering shows all available values, are you sure that any of your games have a favorites = true tag in their Metadata description?

**Comment by pjft** [comment]
Thank you Daniel. Indeed that is the case. 

If you feel this is the case, could you share your EmulationStation version, and send over via pastebin your es_config.txt file and one example of a gamelist where that occurs?

Thank you.

**Comment by andrewvaughan** [comment]
Thanks all,

I am using Emulation Station version `2.7.4RP` on a RaspberryPi 3.  I can send over the `es_config.txt` and gamelist, if needed, but believe the issues is reproducable with the following steps:

> 1. Start with an Emulation Station game library that has *no* Favorites currently stored
> 2. Press controller HotKey button > `FILTER GAMELIST` > `FAVORITES`
> 
> "Favorites" shows only `False` at this point.  I believe this is intended (even if poorly labeled); however:
>
> 3. Exit the menus
> 4. Press the controller `Y` button to store a selected game as a Favorite
> 5. Repeat steps **1** and **2**
>
> At this point, the Favorites list *still* only shows `False` as an option.  I do not believe this is intended; however, if you:
>
> 6. Exit the menus
> 7. Navigate to the previously-favorited game
> 8. Press the controller Hotkey button > `EDIT THIS GAME'S METADATA`
> 9. Scroll down to confirm that `Favorites` was already set to `On`, and hit `Save`
> 10. Exit the menus
> 11. Repeat step **4** and you will see that `FAVORITES` now can be sortable by `TRUE`

This leads me to believe that there is some type of caching or update bug in the way the Favorites shortcut in the menu updates the game's metadata.  Having to re-enter the metadata and save it after using the Favorite shortcut *does* make the Favorites option selectable.

It should be noted that the game's metadata is properly being updated - if I select `False` after using the game shortcut, the game disappears from my library.  This seems to be isolated to the menu needing to be updated after the first Favorite is added from the menu shortcut.

Happy to send other files if it will help, but wanted to see if this would work first.  I also have `SAVE METADATA ON EXIT` set to `OFF`, so make sure you set that as well (otherwise, I would imagine restarting the system would also appropriately set the `Favorites`).

**Comment by pjft** [comment]
Thanks. So, this effectively reduces the behavior to "the index is not properly being updated when the first favorite is set". :)

I'll take a look at that, should be a simple fix. I'm pretty sure I had added code to make that happen.

Can you clarify one thing, though: is your step 5 really saying "exit ES and restart it"? Or did you just mean exit the menus and go to the filtering menu and no favorites are there? I want to believe it is the latter, but if not then it is certainly intended behavior - if you're not saving metadata on exit, when restarting ES you're once again loading a library that has no favorites set. Please confirm what you mean, just so we're on the same page.

Hope that this also at least somehow gives you the workaround to get your library filtering properly - i.e. from the moment you start ES with at least one favorite, that value should certainly show there for that gamelist. 

Let me know, and thanks for reporting this.

**Comment by andrewvaughan** [comment]
Correct on the latter, Step **5** just means return to the game list and check the `FAVORITES` filter again.
