### ISSUE TITLE
Make saving gamelists on shutdown / exit optional by asking another question

### ISSUE THREAD

**Issue by joyrider3774** [RetroPie/EmulationStation#35]
Hi,

I have no need to save gamelist.xml data on shutdown / exit / reboot of the system since i don't make any adjustments to the data. Since i have a lot of roms emulationstation takes a long time to quit / save the gamelists.xml data. Since all that's changed is the play count with me i don't like having to wait for it when i want to shutdown the system.

I noticed this here https://github.com/RetroPie/EmulationStation/pull/17

Would it be feasable to ask the user another question upon choosing system reboot / system shutdown / emulationstation quit if he wants to save the gamelists or not (could be another simple yes / no question) and if not call sudo reboot / sudo poweroff etc immediatly without waiting for emulation station to quit gracefully / having written the gamelists.xml data like it was doing before the change above was made ?

This way users can choose having to wait till their gamelist.xml are saved or not, and it's a combination of the old system and the new system. Since not all users are making changes inside emulationstation to their gamelists and also users know when they changed it or not so asking a question for safe shutdown / reboot instead of Always doing a safe shutdown might be more logical ..

**Comment by joolswills** [comment]
we could yeh - I was considering that - but I wanted to look into other options first (such as only saving if there has been any edits)

**Comment by joyrider3774** [comment]
ah, it might be better if it only saved the lists if there were changes, yes. I'm not certain but there could be Always changes in some lists if the playcount changed. Having a configuration option is also a good way to do it. It's not that big of a deal for me since i created a "power off" and "reboot" (sh) script that calls "sudo poweroff" and "sudo reboot" and placed them in "ports" roms section. So i can still do it using that way as a workaround with the current retropie version

**Comment by zerojay** [comment]
Something I would like to see changed about how this works - if at all possible - is that currently, if boost does not have the ability to write to the gamelist files during, it simply crashes emulationstation completely. If it cannot write to the gamelist files when quitting, it doesn't care and closes out fine (and quickly).

Not having looked at the code myself or how boost works, what would be helpful would be if boost attempts to open a file for read/write and if that fails, fall back to open the file read-only. This would keep Emulationstation from crashing on boot and also would allow people who haven't changed their roms to keep their gamelists read-only and still boot quickly.
