### ISSUE TITLE
[EmulationStation-dev] UI Mode issues

### ISSUE THREAD

**Issue by LodanZark** [RetroPie/EmulationStation#350]
The konami code work as intended to switch back to Full UI mode in the stable build, but in dev build isn't working anymore, keep in mind I have the default UIMode_passkey settings: 
`<string name="UIMode_passkey" value="uuddlrlrba" />`

Another minor issue it's the pop warning message by switching Full  to Kiosk or Kid mode, more specifically the section where it is displayed the input command, in past builds did show up like this: ↑, ↑, ↓, ↓, ←, →, ←, →, B, A  and now it shows up like this , , , , , , , , B, A

**Comment by LodanZark** [comment]
uninstalled the emulationstation-dev and compiled again and it seems fixed all issues mentioned above.

**Comment by pjft** [comment]
When you say "compiled again" do you mean the latest EmulationStation dev version, or the latest main version?

**Comment by LodanZark** [comment]
the latest emustation dev version, i have the stable version uninstalled to avoid confusion
