### ISSUE TITLE
Scraper does not find any Game & Watch games from TheGamesDB

### ISSUE THREAD

**Issue by RoelerCoaster** [RetroPie/EmulationStation#360]
I just tried scraping a couple of Game & Watch games using the built-in scraper with TheGamesDB as source.
However, for every game the scraper reports that no results are found, yet TheGamesDB does have G&W titles in the system (for example: http://thegamesdb.net/browse/4950/)

The scraper appears to be using  `Game & Watch` as the name of the platform for querying the games. It seems, however, that TheGamesDB is expecting the platform as `Game &amp; Watch`.

Consider the following two urls:
- http://thegamesdb.net/api/GetGamesList.php?name=parachute&platform=Game%20%26%20Watch
gives the error:
```xml
<Error>The specified platform was not valid.</Error>
```

- http://thegamesdb.net/api/GetGamesList.php?name=parachute&platform=Game%20%26amp%3B%20Watch
gives the expected result:
```xml
<Data>
	<Game>
		<id>33459</id>
		<GameTitle>Parachute - Wide Screen</GameTitle>
		<ReleaseDate>06/19/1981</ReleaseDate>
		<Platform>Game &amp; Watch</Platform>
	</Game>
</Data>
```

**Comment by jrassa** [comment]
This should be a simple fix.  I will look into adding it soon.  Thanks for reporting.
