### ISSUE TITLE
Missing escapePath function in development

### ISSUE THREAD

**Issue by nintendontit** [RetroPie/EmulationStation#365]
with stable:
/opt/retropie/supplementary/runcommand/runcommand.sh 0 SYS mastersystem /home/pi/RetroPie/roms/mastersystem/Alex\ Kidd\ in\ Miracle\ World\ \\(USA,\ Europe\\).7z

with development:
/opt/retropie/supplementary/runcommand/runcommand.sh 0 SYS mastersystem /home/pi/RetroPie/roms/mastersystem/Alex\ Kidd\ in\ Miracle\ World\ (USA,\ Europe).7z

I start with wrong suppose that is comma character the problem, after few test find that the problem is relative to recent update to remove boost library

Discussion on forum: https://retropie.org.uk/forum/topic/16112/problem-run-roms-with-comma-character/

**Comment by tomaz82** [comment]
It's not missing, it's moved, I'll fix this when I get home from work. Seems to not properly escape the last ')' character at the end.

**Comment by tomaz82** [comment]
#366 fixes this once it's merged

**Comment by tomaz82** [comment]
This should be fixed now?
