### ISSUE TITLE
[emulationstation-dev] Unable to boot on stretch (build: b7679ba)

### ISSUE THREAD

**Issue by LodanZark** [RetroPie/EmulationStation#373]
error:
emulationstation: /home/pi/RetroPie-Setup/tmp/build/emulationstation-dev/es-core/src/resources/font.cpp:17: Font::FontFace::FontFace(ResourceData&&, int): Assertion "!err" failed. 
Abortion.

**Comment by joolswills** [comment]
You must have updated the dev version before updating RetroPie-Setup. Please use the forum for support.

**Comment by LodanZark** [comment]
I though I had the latest retropie-setup script, I was wrong.  It's working everything now, except the konami input go to fullUI mode. Thanks
