### ISSUE TITLE
put raspberry pi hdmi to sleep (turn backlight off)

### ISSUE THREAD

**Issue by grant2258** [RetroPie/EmulationStation#377]
for the raspberry pi you can execute

vcgencmd display_power 0
vcgencmd display_power 1

too turn the display signal on and off 

I think it would be more universal if a turn screen off-on script option could be added ie it runs a 
sh screen_status.sh on
sh screen_status.sh off

and you just add your custom commands to the bash script. Right now i just ssh and do it

**Comment by TheSIlentLink** [comment]
This would be a great feature for people using RetroPie on Monitors.

**Comment by grant2258** [comment]
See im not looking for a system specific option. Its just a kind of universal option to turn a monitor off.  It will change from system to system so a generic script to do the magic would be an ideal solution.
