### ISSUE TITLE
Freeze during menu navigation using Pi3 bluetooth controllers

### ISSUE THREAD

**Issue by MarkFinnigan** [RetroPie/EmulationStation#38]
I recently upgraded to a Pi3 and started using the integrated bluetooth receiver. I have paired a stock PS3 controller with it, but I find that using this controller to navigate will cause ES to freeze after a short period of time. I don't see this issue while using any emulators, just navigating the menu. If I don't pair/use the PS3 controller, everything works fine.

**Comment by joolswills** [comment]
This was a kernel issue causing lockups with the built in bluetooth. Is fixed on latest Raspbian Kernel.
