### ISSUE TITLE
zindex scroll bar gamelist

### ISSUE THREAD

**Issue by wfcarvalho** [RetroPie/EmulationStation#420]
I'm trying to implement zindex for the gamelist, I managed to make the image appear, but it does not follow the scroll bar, how do I fix it?

I put it this way

		<image name="background_gamelist" extra="true">
			<path>./misc/image/bg_gamelist.png</path>
			<pos>0.0525 0.100</pos>
			<size>0.300 0.040</size>			
		</image>
		
		<textlist name="gamelist">
			<selectorColor>9aff9f</selectorColor>
			<selectedColor>006f2b</selectedColor>
			<primaryColor>00ff62</primaryColor>
			<secondaryColor>0b2b14</secondaryColor>
			<fontPath>./misc/font/mono.TTF</fontPath>
			<pos>0.0525 0.100</pos>
		    <size>0.300 0.800</size> 
			<lineSpacing>1.5</lineSpacing>
			<alignment>left</alignment>
			<fontSize>0.0335</fontSize>
			<scrollSound>./misc/sound/scroll.wav</scrollSound>
		</textlist>

And at final code

		<feature supported="z-index">	
		<view name="basic, detailed, video">		
		<image name="background_gamelist" extra="true">
			<zIndex>20</zIndex>
		</image>
		</view>		
		</feature>

**Comment by jrassa** [comment]
@wfcarvalho I answered your question on the forums.  For future references, question like this should be asked on the forums, not github.
