### ISSUE TITLE
Raspberry Pi runtime error

### ISSUE THREAD

**Issue by Joemommasfat** [RetroPie/EmulationStation#427]
Commit 1a4d13b6b39256b1b01f13ead2e653f0bfd7d3ea "Remove builtin resources" causes an error when starting Emulation Station on  Raspberry Pi.

`lvl0: 	Error - File type unknown!
emulationstation: /home/pi/RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp:17: Font::FontFace::FontFace(ResourceData&&, int): Assertion `!err' failed.
Aborted`

**Comment by pjft** [comment]
You need to update RetroPie-Setup and install ES from there. It will copy the required files to the runtime folders.

**Comment by Joemommasfat** [comment]
Yup.  Sorry for the false alarm.

**Comment by Enverex** [comment]
What about other operating systems / distros? I'm getting this on Linux after having built from GIT.

**Comment by pszalanski** [comment]
I just tried building ES from source on Arch Linux, based on this repository here. It also fails with an assertion and simply creating the resources folder does not fix it.

Any suggestions on how to get it to run?

**Comment by bsinky** [comment]
Building from source on Fedora 26, I was running into the same issue.  What I did to fix it:

- build EmulationStation as usual
- `git checkout 3adadc9` (the parent commit of when data/resources was removed)
- `mkdir -p ~/.emulationstation/resources`
- `cp -r data/resources/ ~/.emulationstation/`

I don't know if this is the best way to get the needed resources (I'm guessing they're kept somewhere else for RetroPie Setup to use but I didn't look very hard), but this worked for me!

**Comment by goodjaerb** [comment]
Doesn't this mean the build instructions are moot now because it compiles a binary that fails? I get Retropie-Setup can install it but what about forks? I suppose I'll use bsinky's suggestion and keep the resources folder handy on my Google Drive.

**Comment by jrassa** [comment]
@pszalanski Just creating the resources folder is not enough.  You need to copy the resources folder and its contents from the source.

@bsinky You shouldn't need to checkout out an old commit to get the resources they are still included with the source.  They were moved from `data/resources` to `resources`. 

@goodjaerb ES will check 3 different locations for the resources directory.
 * %home%/.emulationstation/
 * executable path
 * current working directory

The build instructions aren't moot.  If you build it and run the executable from the build directory, it will run properly.  If you move the executable after building, you also need to move the resources to one of the supported locations.

**Comment by goodjaerb** [comment]
I'll try it out. I wish I found this issue thread before I spent all night figuring out which commit broke it (but at least i found this thread before reposting :)  and I don't know how I didn't notice the folder was still there for all the searching i was doing. But I wouldn't have known where to put it. Thanks. If nothing else shouldn't 'make install' place the resources in ~/.emulationstation? I noticed it worked if I ran it from the build directory but installing it puts it in /usr/local/bin and when you run it say on an autostart on login it would fail.

**Comment by jvalecillos** [comment]
I think this issue should be re-opened. The application just doesn't work without these resources in a custom directory that is not documented.

**Comment by Azelphur** [comment]
I agree with @jvalecillos and @Enverex and think this should be reopened, for Linux packages, the current setup cannot work. You've got three directories it looks in:


- %home%/.emulationstation/ - Package manager would be doing a system-wide installation, the users home directory is not known (And even if it was, bad practice)
- executable path - Would be /usr/bin, putting a resources folder in /usr/bin is bad practice
- current working directory - is completely variable and unknown at install time

/usr/share/emulationstation/resources is a very good suggestion, and it is in fact where a lot of applications put data like this, and it would make emulationstation able to be packaged for linux distros again.

**Comment by pszalanski** [comment]
@jrassa Please integrate a change which makes the app search in `/usr/share`, just like @Azelphur suggested. This has been common practice for all linux programs that I know of.

**Comment by bastianbeischer** [comment]
I have been running into this after updating retropie-setup and then updating all packages, which pulled the new (binary!) version 2.8.0 of emulationstation. Is this a packaging error?

**Comment by joolswills** [comment]
https://retropie.org.uk/forum/topic/21196/emulation-station-will-not-boot-after-update

Being worked on.

**Comment by joolswills** [comment]
(Please use the forum for support).

**Comment by EricFromCanada** [comment]
If you're using RetroPie, one thing to check is the output of `which emulationstation`to verify you're running the one from `/usr/bin` placed there by its installer, rather than from `/usr/local/bin` as generated by this repository if you were to run `make install`.
