### ISSUE TITLE
Adding systems to scraper??

### ISSUE THREAD

**Issue by dabonetn** [RetroPie/EmulationStation#43]
I've been trying for a couple of days trying to figure out the GamesDBScraper.cpp along with the PlatformID.cpp & PlatformID.h.

Adding in the coco works in the original emulation station at github.com/Aloshi/EmulationStation, but making the same changes in the retropie version has no effect.

In PlatformId.h I add  line 27 

COCO, 

In PlatformId.cpp I add line 27

"coco",

And in GamesDBScraper.cpp I add line 27

(COCO, "TRS-80 Color Computer")

Any suggestions???

**Comment by HerbFargus** [comment]
http://thegamesdb.net/api/GetPlatformsList.php

**Comment by dabonetn** [comment]
That's where I got the info from that's working in the mainline emulationstation

This is taken from the page.

<Platform>
<id>4941</id>
<name>TRS-80 Color Computer</name>
<alias>trs80-color</alias>
</Platform>

My question is why do the changes work in the mainline emulationstation, but not the retropie fork?

**Comment by dabonetn** [comment]
Ok, today I did fresh pulls and edits and the code works on the following versions of emulationstation.

https://github.com//Aloshi/EmulationStation
https://github.com/Herdinger/EmulationStation

But not in the retropie version.
I even tried just using the following files from the working versions I tried in the retropie build.
Just in case there were edits to the scrapers that weren't listed.

/es-app/src/PlatformId.h
/es-app/src/PlatformId.cpp
/es-app/src/scrapers/*

And still, no errors, it's just not getting game info from the gamesdb.

**Comment by joolswills** [comment]
I can't really advise, but if the current systems scrape correctly, it must be something you are doing. I am planning on adding some missing systems btw. Note that this issue tracker is not really for advice on how to modify the codebase etc :)

**Comment by joolswills** [comment]
note we don't use the unstable branch for retropie
