### ISSUE TITLE
Sometimes, the option arrow is pixelized. Sometimes, it is not.

### ISSUE THREAD

**Issue by hzulla** [RetroPie/EmulationStation#447]
This happens when testing on a hidpi monitor (3840x2160).

For some entries in this menu, the left arrow is pixelized ("UI MODE", "START ON SYSTEM").
For other entries, the left arrow is drawn as expected ("TRANSITION STYLE", "GAMELIST VIEW STYLE").

Same bug occurs in other menus as well.

![pixelized](https://user-images.githubusercontent.com/1705654/41097160-4f7d7986-6a57-11e8-92ca-eb2cc772c80c.png)

**Comment by hzulla** [comment]
Update: Was able to find this for a right arrow, as well.

![pixelized2](https://user-images.githubusercontent.com/1705654/41097859-bcd43f5e-6a59-11e8-989b-9ba0d27cea81.png)

**Comment by hzulla** [comment]
This occurs randomly and is not producible.

**Comment by pjft** [comment]
I observe this as well frequently. 1080p. No consistency here.

It's highly likely that it's related to SVG resizing, being rasterized at different sizes before being rendered. I never really looked into it, though.

A good place to start is looking into 

https://github.com/RetroPie/EmulationStation/blob/master/es-core/src/components/ImageComponent.cpp#L116

seeing what arguments are invoked here for different instances of those internal SVGs. That could shed some light into what may be happening there.

**Comment by hzulla** [comment]
It's weird that it's random. Can it be a concurrency issue in `OptionListComponent`'s resizing of the arrow images based on the text height?

**Comment by pjft** [comment]
Can't say that it can't be, though it's probably just a sequence of resize events that messes it up though.

**Comment by hzulla** [comment]
Yep, it's a concurrency issue. The reason appears to be [this test](https://github.com/RetroPie/EmulationStation/blob/master/es-core/src/resources/TextureData.cpp#L37) - for some reason, it appears that the next call to `setSourceSize()` is already done while `initSVGFromMemory()` hasn't finished yet. As a result, it renders the image with the older lo-res width/height value stored in the image while mSourceWidth/mSourceHeight have already been updated to the new values based on the screen size.

**Comment by hzulla** [comment]
So `OptionListComponent` isn't buggy. It rapidly fires off a number of resize events until the UI measurement has stabilized, which is suboptimal, but the bug is that `setSourceSize()` may not be called while `initSVGFromMemory()` is running.
