### ISSUE TITLE
Errors when using other soundcard than rpi's native one.

### ISSUE THREAD

**Issue by Melkoroth** [RetroPie/EmulationStation#46]
In my setup I'm using a [HifiBerry Digi+](https://www.hifiberry.com/digiplus/) to play sounds through my 5.1 speakers. Great for OpenElec!

First of all, everytime I launch or exit anything a console error message appears 

> lvl0: VolumeControl::init() - Failed to find mixer elements!

This won't be a big issue by itself but there are some systems that just don't want to run. 
Specifically neither NEO-GEO nor GBA or SCUMM run for me at all. SCUMM was tested and worked great before setting up the hat. All other systems I've tested work no problem with proper sound and all.

The problem was (partly) referenced in https://github.com/Aloshi/EmulationStation/issues/433 but not resolved. I infer that it should happen to most people using external soundcards.

As far as I understand it's caused by the initialization done [here](https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/VolumeControl.cpp#L8) which points to "PCM" or "Master" that are no longer present on my set-up.

Doing a "cat /proc/asound/cards" outputs:

> 0 [sndrpihifiberry]: snd_rpi_hifiber - snd_rpi_hifiberry_digi
>                       snd_rpi_hifiberry_digi

"aplay -l":

> ***\* List of PLAYBACK Hardware Devices ****
> card 0: sndrpihifiberry [snd_rpi_hifiberry_digi], device 0: HifiBerry Digi HiFi wm8804-spdif-0 []
>   Subdevices: 0/1
>   Subdevice #0: subdevice #0

"amixer":

> Simple mixer control 'Tx Source',0
>   Capabilities: enum
>   Items: 'S/PDIF RX' 'AIF'
>   Item0: 'AIF'

I'll gladly test and make a pull-request if someone can point me in the right direction.

**Comment by alexruffell** [comment]
Someone had mentioned that you can modify VolumeControl.cpp to use "Speakers" instead of the default "PCM" and after recompiling it will work however it is not ideal, and would be best if the sound card could be configured from within ES.

**Comment by hex007** [comment]
Kindly close this issue as it has been fixed

**Comment by hex007** [comment]
@Melkoroth Does this fix your issues?

**Comment by hex007** [comment]
@joolswills I think this can be closed due to no response from reporter
