### ISSUE TITLE
FileUtils: Error generating image path when $HOME ends with slash

### ISSUE THREAD

**Issue by cmitu** [RetroPie/EmulationStation#473]
First reported in https://retropie.org.uk/forum/topic/18924/metadata-being-changed-on-exit.

  When the $HOME/%HOME% variable ends with a trailing `/`, the `removeCommonPath` generates the wrong `image` path in the `gamelist.xml` file. The function is called, when metadata is saved, from `createRelativePath` with the input parameters:
 * `path` = C:/Portable/emulationstation//.emulationstation/downloaded_images/pcengine/Legendary Axe, The (USA)-image.jpg
* `common`  = C:/Portable/emulationstation/ (which is `%HOME%`)

 Subsequently, `removeCommonPath` returns the relative path for the `image` tag as **emulationstation/downloaded_images/pcengine/Legendary Axe, The (USA)-image.jpg**, to which `createRelativePath` is pre-pending **~**, resulting in a wrong image. 
The correct relative path should be **.emulationstation/downloaded_images/pcengine/Legendary Axe, The (USA)-image.jpg**, to which `createRelativePath` would prepend **~/** to generate the correct image path.

 A possible fix is to replace the `getGenericPath` inside `removeCommonPath` with `getGenericPath`, this will normalize the `common` parameter and remove the final `/` from the directory name.

**Comment by tomaz82** [comment]
I'll look into this

**Comment by cmitu** [comment]
Correcting my post: 
A possible fix is to replace the `getGenericPath` inside `removeCommonPath` with `getCanonicalPath`, this will normalize the common parameter and remove the final / from the directory name.

**Comment by tomaz82** [comment]
Ran several tests and I can't reproduce this bug.
getGenericPath does remove the double / so it returns the path `.emulationstation/downloaded_images/pcengine/Legendary Axe, The (USA)-image.jpg`

**Comment by cmitu** [comment]
No, it seems #413 didn't fix it. I've run the latest master today and reproduced it using the portable ES toolkit which starts ES with:
``` bat
SET HOME=%~dp0
emulationstation.exe
```

 `%HOME%` gets set to `C:/Portable/emulationstation/` and this is - seemingly - what generates the path problem.

**Comment by cmitu** [comment]
To reproduce the problem, I just scraped one game with the built-in scraper, then exited ES. The `gamelist.xml` was updated and the `image` was set to the wrong path.

**Comment by cmitu** [comment]
RE: `getGenericPath` - I guess it does the normalization, the problem is that the original path

**Comment by cmitu** [comment]
Sorry about the closing/reopening, wrong button to press. Can you try re-producing the problem starting ES with the `HOME` set (ending in `/`) and re-scraping one game to see how the `gamelist.xml` is saved ?
