### ISSUE TITLE
Error in font.cpp

### ISSUE THREAD

**Issue by billywade** [RetroPie/EmulationStation#477]
the latest AUR/git build doesn't launch for me, complaining
```
lvl0: 	Error - File type unknown!
lvl0: 	CECInput::mAdapter->DetectAdapters failed
emulationstation: /tmp/EmulationStation/es-core/src/resources/Font.cpp:17: Font::FontFace::FontFace(ResourceData&&, int): Assertion `!err' failed.
Aborted (core dumped)
```
The log files are empty, otherwise I'd include them. Let me know if you need anything else.

**Comment by cmitu** [comment]
Looks the same error as in #427, the packager didn't include the necessary resources with the package.

**Comment by billywade** [comment]
Yup, fixed. It even fixed an issue with me not being able to launch the app outside of the build directory. Thanks!
