### ISSUE TITLE
/opt/retropie/supplementary/emulationstation/emulationstation is always using 6-10% CPU when idle

### ISSUE THREAD

**Issue by loganmc10** [RetroPie/EmulationStation#48]
Looking at 'top' on my Raspberry Pi 3, I see that this process:

/opt/retropie/supplementary/emulationstation/emulationstation

Is always using 6-10% of the CPU, even when it's just sitting at the "pick a console" screen. Why is that?

**Comment by joolswills** [comment]
Please wait for a reply to your post on the forum.
