### ISSUE TITLE
[Segfault ]Remove trailing '/' in getGenericPath

### ISSUE THREAD

**Issue by 5schatten** [RetroPie/EmulationStation#488]
This patch https://github.com/RetroPie/EmulationStation/commit/15ccfc5a05ca82fe443c5844d57255563090479c results in a segfault for me when I try to launch ES by systemd through this script https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.0-rr/packages/oem/files/usr/bin/emulationstation-frontend.py

dmesg: 
[  467.492513] emulationstatio[1681]: segfault at 7ffff2e29fa0 ip 00007f96c3edd86e sp 00007ffff2e29fa0 error 6 in libc-2.28.so[7f96c3e7f000+13c000]
[  467.492518] Code: 00 48 83 f8 1f 0f 86 41 01 00 00 48 83 e0 f0 48 83 f8 bf 49 89 c6 0f 97 c0 49 39 f6 0f 82 9a 06 00 00 84 c0 0f 85 92 06 00 00 <48> 89 34 24 49 89 fd 48 85 ff 0f 84 9a 06 00 00 45 89 f7 41 c1 ef 

After reverting the patch and updating to latest commit https://github.com/RetroPie/EmulationStation/commit/4ce357c26761664c848fe5a245a1872c57c2f06c ES runs fine again.

**Comment by tomaz82** [comment]
Do you have custom collections?

**Comment by 5schatten** [comment]
Custom collection? Just the usual stuff ES scrapes or what do you mean? Anyway tried the latest version & still fails without reverting the patch.

**Comment by cmitu** [comment]
I found that starting _emulationstation_ from `/` leads to a crash (_Segmentation fault_) somewhere in `Utils:FileSystem:getCWDPath` when using the default Carbon theme. I didn't have time to debug this further, but maybe it's the same crash I encountered - will test and try to fix later.

**Comment by cmitu** [comment]
@5schatten I've added a small fix for the crash I reported earlier - can you try and see if it also solves your issue ?

**Comment by cmitu** [comment]
Should be fixed by https://github.com/RetroPie/EmulationStation/pull/622.
