### ISSUE TITLE
Controllers with analog L/R triggers don't configure properly

### ISSUE THREAD

**Issue by superjamie** [RetroPie/EmulationStation#49]
When using a controller with analog L/R triggers such as the Logitech F310 or F710 (in DirectInput mode), EmulationStation asks you to configure L2 as a button and recognises the "trigger in" as a button press. ES then moves onto the next button, which it recognises as the "trigger out" button press.

It's then required to go into the gamepad config (Retropie's `/opt/retropie/configs/all/retroarch-joypads/LogitechGamepadF310.cfg`) and change lines like:

~~~
# Triggers
input_l2_axis = "-2"
input_r2_axis = "-5"
~~~

to:

~~~
# Triggers
input_l2_minus_axis = "-2"
input_l2_plus_axis = "+2"
input_r2_minus_axis = "-5"
input_r2_plus_axis = "+5"
~~~

Ideally, ES should recognise when a button is analog, and configure the opposite axis when appropriate. This would need to not happen for the D-Pad or analog sticks.

References:
* <https://www.reddit.com/r/RetroPie/comments/4h1cqy/controller_unresponsive_after_game_launched/>
* <https://www.reddit.com/r/RetroPie/comments/4in1kh/been_having_trouble_getting_my_logitech_f310_to/>
* <https://www.reddit.com/r/RetroPie/comments/4kbh8m/i_have_a_really_silly_question_regarding/>

**Comment by joolswills** [comment]
Instead of edited the file, when you get to "OK", press whatever you configured for "up" and you should be able to reconfigure any trigger that configured incorrectly.

**Comment by superjamie** [comment]
Thanks for responding! Yes, you are correct, it is possible to re-map any missed buttons.

However, even after that is done, using the "in" motion of the axis to trigger the L2/R2 button press does not work reliably all the time. RetroArch sometimes ignores the button press, and sometimes the button press sticks down.

IIUC if ES properly mapped the in and out axis for the button press, this would not happen.

**Comment by superjamie** [comment]
Previously in RetroPie 3.7 it was possible to avoid this entirely by setting these controllers to DirectInput mode. That no longer works with RetroPie 3.8 and the XInput mode must be used, so the L2/R2 must be configured as analog axes.

However, without the `plus_axis` and `minus_axis` edit described above, it is required to press L2 and R2 before the emulators will recognise any button presses. If you just launch a libretro emulator and do not press the L2 R2 triggers then the controller never works.

Surely you must consider this a bug?

**Comment by joolswills** [comment]
The issue with the controller mode is probably related to a kernel update - so that is not something I can help with.

It sounds odd that the controller would not work at all without the additional edit though - and I can't see why that would be an ES issue (sure the way the configuration is set up isn't perfect, but that shouldn't stop other buttons from working I would have thought).

I would add I also don't have one of these controllers for testing - so patches are welcome.

**Comment by HerbFargus** [comment]
I have a few f310s which I assume are more or less the same as the f710  and I can confirm the issue as it has been an issue for a while, nobody has resolved it yet though and I lack the coding know how to implement it but I could look at it. We'd more or less have to add a little extra logic for triggers that register as axes. I think it's the same for the xbox360 controller if you don't use xboxdrv

**Comment by superjamie** [comment]
I agree the mode issue is probably upstream, I don't expect that can be fixed in ES.

I expect the controller needs the in-axis "reset" to minimum with a quick press, so that RetroArch then recognizes that the L2/R2 aren't being pressed.

As you'll accept a patch I'll have a try at fixing it. I work mostly in C but I've got workmates who can help me with Cpp.

**Comment by superjamie** [comment]
Don't pull this patch in yet, I need to test more. I think this has actually been resolved another way.

**Comment by superjamie** [comment]
OK, I figured this out.

When you configure the controller in ES and *quickly* press the analog trigger, you'll usually get one of the axes bound to `-2` or `-5`. The negative movement is the "outwards" movement on the axis, like you are releasing the trigger.

This is what causes the problem where RA won't recognise a button press, probably because the trigger is already at max negative axis when in resting state, so the button is always "pressed" and needs to be "unpressed" at least once to allow RA to accept other inputs.

If you are a bit more slow and gentle when configuring the controller, you end up with top left/right bound to `+2` or `+5` which are the "inwards" movement on the axis. The controller then works perfectly in RA and the other emulators, again because the resting state is at full negative so any inward movement registers the button press.

So, the `plus`/`minus` config change is not required (and actually doesn't work on latest RetroArch anyway).

This is resolved by gently pressing the analog trigger during configuration to get the correct inward axis. I am happy for this to close as not a software issue. I'll make a wiki page about these controllers to document this and the correct config.

**Comment by superjamie** [comment]
Also @HerbFargus could you please email me a copy of your `/opt/retropie/configs/all/retroarch-joypads/LogitechGamepadF310.cfg` so I can double check the button mappings? I expect they're the same as the F710 but I'll make sure.

**Comment by HerbFargus** [comment]
@superjamie here's the pastebin 

http://pastebin.com/LXBWa0XH

**Comment by superjamie** [comment]
Thanks dude!

Wrote wiki page detailing the controller features and configurations:

https://github.com/RetroPie/RetroPie-Setup/wiki/Logitech-controllers

This is resolved.

**Comment by joolswills** [comment]
thanks for that.
