### ISSUE TITLE
RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp:412: void Font::renderTextCache(TextCache*): Assertion `*it->textureIdPtr != 0' failed.

### ISSUE THREAD

**Issue by dsx724** [RetroPie/EmulationStation#490]
retroarch runs just fine but emulation station fails. I have tried both master and stable branches to no avail. I manually copied the resources files from es-core to .emulationstation/resources.

Anything else I should try? emulationstation --debug doesn't give much details.

**Comment by dsx724** [comment]
This is with SDL2 compiled with KMS DRM video driver.

**Comment by dsx724** [comment]
@cmitu ls ~/.emulationstation/resources/
arrow.svg   busy_1.svg  busy_3.svg         button.png            checkbox_unchecked.svg  fav_remove.svg  help     on.svg                               opensans_hebrew_condensed_regular.ttf  scroll_gradient.png  splash.svg       star_unfilled.svg               textinput_ninepatch.png
busy_0.svg  busy_2.svg  button_filled.png  checkbox_checked.svg  fav_add.svg             frame.png       off.svg  opensans_hebrew_condensed_light.ttf  option_arrow.svg                       slider_knob.svg      star_filled.svg  textinput_ninepatch_active.png  window_icon_256.png

We had already copied the resources and we still experience the error.

**Comment by cmitu** [comment]
> @cmitu ls ~/.emulationstation/resources/ [...]

I can't reproduce the issue. I run `emulationstation` from $HOME and crashed with the same error. As soon as I copied the `resources` folder in `~/.emulationstation`, the crash disappeared. Check the permissions on the folder and make sure you copied all the required files. 

Installing ES from the RetroPie-Setup script will produce a working installation also, you can take a look at how it's installed in with the `emulationstation` scriptmodule in that script - https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/emulationstation.sh.

**Comment by dsx724** [comment]
Can you give me the output of `ls -al ~/.emulationstation/resources/`? I am doing this on aarch64 with a custom SDL2 enabled for GLES2.

**Comment by dsx724** [comment]
The emulators run fine manually but this is preventing the emulators from launching.

**Comment by cmitu** [comment]
This is the contents of my `~/.emulationstation/resources`
```
total 3424
drwxr-xr-x 3 pi pi    4096 Aug 21 17:42 .
drwxr-xr-x 9 pi pi    4096 Oct  2 16:40 ..
-rw-r--r-- 1 pi pi     268 Aug 21 17:42 arrow.svg
-rw-r--r-- 1 pi pi     482 Aug 21 17:42 busy_0.svg
-rw-r--r-- 1 pi pi     482 Aug 21 17:42 busy_1.svg
-rw-r--r-- 1 pi pi     482 Aug 21 17:42 busy_2.svg
-rw-r--r-- 1 pi pi     483 Aug 21 17:42 busy_3.svg
-rw-r--r-- 1 pi pi    1231 Aug 21 17:42 button.png
-rw-r--r-- 1 pi pi    1168 Aug 21 17:42 button_filled.png
-rw-r--r-- 1 pi pi    1932 Aug 21 17:42 cartridge.svg
-rw-r--r-- 1 pi pi     479 Aug 21 17:42 checkbox_checked.svg
-rw-r--r-- 1 pi pi     335 Aug 21 17:42 checkbox_unchecked.svg
-rw-r--r-- 1 pi pi     286 Aug 21 17:42 fav_add.svg
-rw-r--r-- 1 pi pi     215 Aug 21 17:42 fav_remove.svg
-rw-r--r-- 1 pi pi     495 Aug 21 17:42 folder.svg
-rw-r--r-- 1 pi pi    1729 Aug 21 17:42 frame.png
drwxr-xr-x 2 pi pi    4096 Aug 21 17:42 help
-rw-r--r-- 1 pi pi 3217413 Aug 21 17:42 mamenames.xml
-rw-r--r-- 1 pi pi    1363 Aug 21 17:42 off.svg
-rw-r--r-- 1 pi pi    1736 Aug 21 17:42 on.svg
-rw-r--r-- 1 pi pi   32868 Aug 21 17:42 opensans_hebrew_condensed_light.ttf
-rw-r--r-- 1 pi pi   32364 Aug 21 17:42 opensans_hebrew_condensed_regular.ttf
-rw-r--r-- 1 pi pi     247 Aug 21 17:42 option_arrow.svg
-rw-r--r-- 1 pi pi   83384 Aug 21 17:42 scroll_gradient.png
-rw-r--r-- 1 pi pi     190 Aug 21 17:42 slider_knob.svg
-rw-r--r-- 1 pi pi   19024 Aug 21 17:42 splash.svg
-rw-r--r-- 1 pi pi     807 Aug 21 17:42 star_filled.svg
-rw-r--r-- 1 pi pi     807 Aug 21 17:42 star_unfilled.svg
-rw-r--r-- 1 pi pi    1275 Aug 21 17:42 textinput_ninepatch.png
-rw-r--r-- 1 pi pi    3084 Aug 21 17:42 textinput_ninepatch_active.png
-rw-r--r-- 1 pi pi    4870 Aug 21 17:42 window_icon_256.png
```

**Comment by dsx724** [comment]
I don't know why I was missing a few files before but I have re-copied the directory and added the missing files. The permissions are all correct with readability for everyone and ownership by the user.

.   arrow.svg   busy_1.svg  busy_3.svg         button.png     checkbox_checked.svg    fav_add.svg     folder.svg  help           off.svg  opensans_hebrew_condensed_light.ttf    option_arrow.svg     slider_knob.svg  star_filled.svg    textinput_ninepatch_active.png  window_icon_256.png
..  busy_0.svg  busy_2.svg  button_filled.png  cartridge.svg  checkbox_unchecked.svg  fav_remove.svg  frame.png   mamenames.xml  on.svg   opensans_hebrew_condensed_regular.ttf  scroll_gradient.png  splash.svg       star_unfilled.svg  textinput_ninepatch.png

I also did a clean bootstrap and still get the same issue. Are you sure without the resources folder your are getting an error on line 412 and not somewhere else? I will run some debugger and post an update.

**Comment by dsx724** [comment]
> Checking Resource Exist: /home/libre/.emulationstation/resources/window_icon_256.png
> Checking Resource Exist: :/window_icon_256.png
> Resource Exist: :/window_icon_256.png
> lvl0: 	CECInput::mAdapter->DetectAdapters failed
> Checking Resource Exist: /home/libre/.emulationstation/resources/opensans_hebrew_condensed_regular.ttf
> Checking Resource Exist: :/opensans_hebrew_condensed_regular.ttf
> Resource Exist: :/opensans_hebrew_condensed_regular.ttf
> Selected Resource: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Checking Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Checking Resource Exist: /home/libre/.emulationstation/resources/opensans_hebrew_condensed_regular.ttf
> Checking Resource Exist: :/opensans_hebrew_condensed_regular.ttf
> Resource Exist: :/opensans_hebrew_condensed_regular.ttf
> Selected Resource: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Checking Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Checking Resource Exist: /home/libre/.emulationstation/resources/opensans_hebrew_condensed_regular.ttf
> Checking Resource Exist: :/opensans_hebrew_condensed_regular.ttf
> Resource Exist: :/opensans_hebrew_condensed_regular.ttf
> Selected Resource: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Checking Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Selected Resource: /etc/emulationstation/themes/carbon/art/Cabin-Bold.ttf
> Checking Resource Exist: /etc/emulationstation/themes/carbon/art/Cabin-Bold.ttf
> Resource Exist: /etc/emulationstation/themes/carbon/art/Cabin-Bold.ttf
> Selected Resource: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Checking Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Selected Resource: /etc/emulationstation/themes/carbon/art/Cabin-Bold.ttf
> Checking Resource Exist: /etc/emulationstation/themes/carbon/art/Cabin-Bold.ttf
> Resource Exist: /etc/emulationstation/themes/carbon/art/Cabin-Bold.ttf
> Selected Resource: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Checking Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
> Selected Resource: /etc/emulationstation/themes/carbon/retropie/art/system.svg
> Checking Resource Exist: /etc/emulationstation/themes/carbon/retropie/art/system.svg
> Resource Exist: /etc/emulationstation/themes/carbon/retropie/art/system.svg
> Selected Resource: /etc/emulationstation/themes/carbon/snes/art/system.svg
> Checking Resource Exist: /etc/emulationstation/themes/carbon/snes/art/system.svg
> Resource Exist: /etc/emulationstation/themes/carbon/snes/art/system.svg
> Checking Resource Exist: /home/libre/.emulationstation/resources/scroll_gradient.png
> Checking Resource Exist: /home/libre/.emulationstation/resources/scroll_gradient.png
> Checking Resource Exist: :/scroll_gradient.png
> Resource Exist: :/scroll_gradient.png
> ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL 
> lvl0: 	VolumeControl::init() - Failed to attach to default card!
> Checking Resource Exist: /home/libre/.emulationstation/resources/scroll_gradient.png
> Selected Resource: /etc/emulationstation/themes/carbon/snes/../art/carbon_fiber.png
> Selected Resource: /etc/emulationstation/themes/carbon/snes/art/system.svg
> Selected Resource: /etc/emulationstation/themes/carbon/snes/art/system.svg
> Checking Resource Exist: /etc/emulationstation/themes/carbon/snes/art/system.svg
> Resource Exist: /etc/emulationstation/themes/carbon/snes/art/system.svg
> Selected Resource: /etc/emulationstation/themes/carbon/snes/../art/carbon_fiber.png
> Selected Resource: /etc/emulationstation/themes/carbon/snes/../art/bottom.png
> Selected Resource: /etc/emulationstation/themes/carbon/snes/../art/top.png
> Selected Resource: /etc/emulationstation/themes/carbon/snes/art/controller.svg
> Selected Resource: /etc/emulationstation/themes/carbon/snes/art/controller.svg
> Checking Resource Exist: /etc/emulationstation/themes/carbon/snes/art/controller.svg
> Resource Exist: /etc/emulationstation/themes/carbon/snes/art/controller.svg
> Selected Resource: /etc/emulationstation/themes/carbon/art/top.png
> Checking Resource Exist: /etc/emulationstation/themes/carbon/art/top.png
> Resource Exist: /etc/emulationstation/themes/carbon/art/top.png
> Selected Resource: /etc/emulationstation/themes/carbon/art/bottom.png
> Checking Resource Exist: /etc/emulationstation/themes/carbon/art/bottom.png
> Resource Exist: /etc/emulationstation/themes/carbon/art/bottom.png
> Selected Resource: /etc/emulationstation/themes/carbon/art/carbon_fiber.png
> Checking Resource Exist: /etc/emulationstation/themes/carbon/art/carbon_fiber.png
> Resource Exist: /etc/emulationstation/themes/carbon/art/carbon_fiber.png
> Selected Resource: /etc/emulationstation/themes/carbon/snes/art/system.svg
> Checking Resource Exist: /etc/emulationstation/themes/carbon/snes/art/system.svg
> Resource Exist: /etc/emulationstation/themes/carbon/snes/art/system.svg
> Checking Resource Exist: /home/libre/.emulationstation/resources/scroll_gradient.png
> Checking Resource Exist: :/scroll_gradient.png
> Resource Exist: :/scroll_gradient.png
> Checking Resource Exist: /home/libre/.emulationstation/resources/help/dpad_updown.svg
> Checking Resource Exist: :/help/dpad_updown.svg
> Resource Exist: :/help/dpad_updown.svg
> Checking Resource Exist: /home/libre/.emulationstation/resources/help/dpad_leftright.svg
> Checking Resource Exist: :/help/dpad_leftright.svg
> Resource Exist: :/help/dpad_leftright.svg
> Checking Resource Exist: /home/libre/.emulationstation/resources/help/button_a.svg
> Checking Resource Exist: :/help/button_a.svg
> Resource Exist: :/help/button_a.svg
> Checking Resource Exist: /home/libre/.emulationstation/resources/help/button_b.svg
> Checking Resource Exist: :/help/button_b.svg
> Resource Exist: :/help/button_b.svg
> Checking Resource Exist: /home/libre/.emulationstation/resources/help/button_x.svg
> Checking Resource Exist: :/help/button_x.svg
> Resource Exist: :/help/button_x.svg
> Checking Resource Exist: /home/libre/.emulationstation/resources/help/button_y.svg
> Checking Resource Exist: :/help/button_y.svg
> Resource Exist: :/help/button_y.svg
> Checking Resource Exist: /home/libre/.emulationstation/resources/help/button_start.svg
> Checking Resource Exist: :/help/button_start.svg
> Resource Exist: :/help/button_start.svg
> Checking Resource Exist: /home/libre/.emulationstation/resources/help/button_select.svg
> Checking Resource Exist: :/help/button_select.svg
> Resource Exist: :/help/button_select.svg
> Selected Resource: /etc/emulationstation/themes/carbon/snes/art/controller.svg
> Checking Resource Exist: /etc/emulationstation/themes/carbon/snes/art/controller.svg
> Resource Exist: /etc/emulationstation/themes/carbon/snes/art/controller.svg
> emulationstation: /home/libre/RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp:412: void Font::renderTextCache(TextCache*): Assertion `*it->textureIdPtr != 0' failed.
> Aborted

Everything exists. The issue is somewhere else.

**Comment by cmitu** [comment]
> The issue is somewhere else @cmitu.

Looks like it's indeed not related to the resources, but the problem seems to be somewhere in the GL library underneath - not in ES.

**Comment by pjft** [comment]
Let me venture another guess (which, like all guess, has a lot of chances of being completely off).
What the are you using, and do you confirm that it has the right fonts available in the theme folders? It is, after all, failing in a font-related assertion.

@cmitu 's suggestion is likely more on point, but just making sure that we're not overlooking something simpler.

**Comment by cmitu** [comment]
@pjft I think the log posted shows it checks for the theme's fonts and they're ok:

> Selected Resource: /etc/emulationstation/themes/carbon/art/Cabin-Bold.ttf
Checking Resource Exist: /etc/emulationstation/themes/carbon/art/Cabin-Bold.ttf
Resource Exist: /etc/emulationstation/themes/carbon/art/Cabin-Bold.ttf
Selected Resource: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
Checking Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
Resource Exist: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf

**Comment by pjft** [comment]
@cmitu you're right as usual. Likely (for GL reasons or others) it's unable to load/create the font texture in memory.

**Comment by dsx724** [comment]
I made some modifications to the build for GLES using Mali/KMS that could be the issue:

sed -i 's/GLES\/gl.h/SDL_opengles.h/' RetroPie-Setup/tmp/build/emulationstation/es-core/src/platform.h
cmake . -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype2/ -DGLES=ON -DOPENGLES_INCLUDE_DIR=/usr/include/mali/

The cmake completes fine. It may be that it is using some GL code instead of GLES code to render the font?

**Comment by cmitu** [comment]
> The cmake completes fine. It may be that it is using some GL code instead of GLES code to render the font?

Could be, does ES work if you're starting from an X session ?

**Comment by dsx724** [comment]
There's no X on the system. I'm trying to use KMS/DRM directly.

**Comment by dsx724** [comment]
DEBUG: KMSDRM_VideoInit()
DEBUG: Opened DRM FD (4)
DEBUG: Found connector 29 with 27 modes.
DEBUG: Found encoder 28.
DEBUG: Saved crtc_id 31, fb_id 49, (0,0), 1920x1080
DEBUG: Failed loading udev_device_get_action: /usr/lib/aarch64-linux-gnu/libSDL2-2.0.so.0: undefined symbol: _udev_device_get_action
DEBUG: Could not find a cursor size supported by the kernel driver
DEBUG: Couldn't find cursor to hide.
DEBUG: Couldn't find cursor to hide.
DEBUG: Could not hide display's cursor with drmModeSetCursor().
DEBUG: No mouse or current cursor.
DEBUG: Unable to make EGL context current (call to eglMakeCurrent failed, reporting an error of EGL_BAD_ALLOC)
DEBUG: Unable to make EGL context current (call to eglMakeCurrent failed, reporting an error of EGL_BAD_ALLOC)
DEBUG: No OpenGL context has been made current
DEBUG: No OpenGL context has been made current
lvl0: 	CECInput::mAdapter->DetectAdapters failed
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL 
lvl0: 	VolumeControl::init() - Failed to attach to default card!
emulationstation: /home/libre/RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp:412: void Font::renderTextCache(TextCache*): Assertion `*it->textureIdPtr != 0' failed.

**Comment by dsx724** [comment]
libEGL.so call trace: https://pastebin.com/g0gLuCzv

**Comment by cmitu** [comment]
I'm sorry, I'm not able to guide on errors related to GL and I'm not sure that ES is at fault here.

**Comment by dsx724** [comment]
Yeah it is difficult to tell. I am just posting information in case someone hits this problem as well or knows the solution.

The only time that function is called in emulationstation is in
./emulationstation/es-core/src/Renderer_draw_gl.cpp

When I do a grep for that function in SDL2 and emulationstation, the only thing I find is
 grep -r glLoadMatrixf .
./ppsspp/ppsspp/ext/glew/GL/glew.h:GLAPI void GLAPIENTRY glLoadMatrixf (const GLfloat *m);
./emulationstation/es-core/src/Renderer_draw_gl.cpp:		glLoadMatrixf((GLfloat*)&matrix);
Binary file ./emulationstation/es-core/CMakeFiles/es-core.dir/src/Renderer_draw_gl.cpp.o matches
Binary file ./emulationstation/libes-core.a matches
Binary file ./emulationstation/emulationstation matches
./sdl2/2.0.8+1/include/SDL_opengl.h:GLAPI void GLAPIENTRY glLoadMatrixf( const GLfloat *m );
./sdl2/2.0.8+1/src/render/opengl/SDL_glfuncs.h:SDL_PROC_UNUSED(void, glLoadMatrixf, (const GLfloat * m))

**Comment by evelikov** [comment]
Perhaps unrelated - the SDL messages look very suspicious.

Looking at the code in `Renderer_init_sdlgl.cpp` - building with GLES:
 - the version is requested (eek why are you guys using 1 ...)
 - yet the ES profile is not selected - do you end up with OpenGL?

See https://wiki.libsdl.org/SDL_GLprofile

Extra tidbits:
 - try GLES2 + updating the code
Some Linux distros are _not_ shipping libGLESv1_CM.so while others have a non functioning one :-\
 - if your OpenGL codepaths require version 3.1 (now or in the future)
Req. the version explicitly, use core profile + updating the code

**Comment by dsx724** [comment]
@evelikov I think Emulation Station uses GLESv1. The library binary for GLESv1 and GLESv2 are the same since Mali ships with only one binary. SDL is using EGL since this is all using DRM and not X11/Wayland.

**Comment by dsx724** [comment]
@evelikov OpenGL is disabled in SDL. I will retry by adding context to see if it fixes it.

**Comment by dsx724** [comment]
@evelikov You were right, major code changes are needed because Emutation Station still requires GL.

https://pastebin.com/wqjjahNB

@cmitu Should I close this ticket and create a new ticket for GLES only support?

**Comment by cmitu** [comment]
> @cmitu Should I close this ticket and create a new ticket for GLES2 only support?

You can do as you please, but I don't see the point in asking for GLES2 if there's nothing that really requiring this. Note that I'm not an ES dev, I was just trying to help diagnose and fix the issue.

**Comment by dsx724** [comment]
The issue is a problem with my setup. libMali.so only allows one context to be created so having retroarch running within EmulationStation is the most likely cause. Probably need to re-think how to launch retroarch in situations with DRM/KMS. The GLESv2 is a side issue. I hijacked runcommand.sh and retroarch will segfault. Meanwhile without EmulationStation running, the same retroarch commands will run just fine.

**Comment by dsx724** [comment]
@sigmaris Did you ever encounter this problem?

**Comment by sigmaris** [comment]
I've not encountered this problem, but I've not used EmulationStation with a Mali GPU; only with the VC4 GPU on Raspberry Pi. A wild guess is the problem might be related to EmulationStation not completely releasing the GPU when it launches an emulator. I found an issue (https://github.com/anholt/mesa/issues/33) in the vc4 driver where it kept an open file descriptor, and that prevented Retroarch from running when ES launched it.

**Comment by dsx724** [comment]
Thanks for the tip. You are right:
emulation 23922                  libre    0u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23922                  libre    1u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23922                  libre    2u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23929                  libre    0u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23929                  libre    1u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23929                  libre    2u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932                  libre    0u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932                  libre    1u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932                  libre    2u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932                  libre    5u      CHR              226,0      0t0       2786 /dev/dri/card0
emulation 23932 23933            libre    0u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932 23933            libre    1u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932 23933            libre    2u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932 23933            libre    5u      CHR              226,0      0t0       2786 /dev/dri/card0
emulation 23932 23934            libre    0u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932 23934            libre    1u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932 23934            libre    2u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932 23934            libre    5u      CHR              226,0      0t0       2786 /dev/dri/card0
emulation 23932 23936            libre    0u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932 23936            libre    1u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932 23936            libre    2u      CHR              136,0      0t0          3 /dev/pts/0
emulation 23932 23936            libre    5u      CHR              226,0      0t0       2786 /dev/dri/card0

**Comment by dsx724** [comment]
This is a Mali issue. I am closing.
