### ISSUE TITLE
[Request] Option to reset Retropie to stock

### ISSUE THREAD

**Issue by Cederick** [RetroPie/EmulationStation#497]
Hey I just wanted to quickly ask if there is any hope for an option to uninstall all additional packages I got without flashing the sd card and losing all my roms. Since I have so many experimental packages that I would like to get rid of and I don't remember what I did to my Retropie installation last year. Can weg get something like this in the future?

Sincerely
A really clumsy Retropi user

**Comment by joolswills** [comment]
Please use the forum - https://retropie.org.uk/forum/ thanks.
