### ISSUE TITLE
Update scraper to use new thegamesdb.net API

### ISSUE THREAD

**Issue by c0d3h4x0r** [RetroPie/EmulationStation#504]
EmulationStation v2.7.6rp (included in the latest available RetroPie release) uses the old API via http://legacy.thegamesdb.net, which is apparently backed by a completely different dB than https://thegamesdb.net, so the scraper can't find any of the new games I just added to https://thegamesdb.net.  Please update to use the new API instead so that RetroPie's scraper can actually find newly-added games.

**Comment by HerbFargus** [comment]
This has already been done...

**Comment by c0d3h4x0r** [comment]
How can I get my hands on it?  I already tried building emulationstation myself from the latest 'stable' branch, but it just crashes with an assertion failure on startup and doesn't appear to work.

**Comment by pjft** [comment]
It's likely in the dev branch for the time being. You can (should) install it via RetroPie-Setup, as some dependencies might have changed and the install script will copy them to the right place.

**Comment by c0d3h4x0r** [comment]
I ran RetroPie-Setup and updated everything less than a week ago, yet my installed version of EmulationStation is still self-reported as 2.7.6rp.  Sounds like the RetroPie-Setup script is not fetching all of the latest stuff.

**Comment by pjft** [comment]
It’s in the dev branch. You can get it in the experimental packages, as emulationstation-dev.

**Comment by c0d3h4x0r** [comment]
I see.  Thanks, I'll give that a shot!

**Comment by pjft** [comment]
By all means. I imagine that the audio menu also changed a bit, so if you have issues with audio you’ll need to go to that menu and explicitly select an audio output device from what will show as an empty list. If you go to the audio menu and don’t select an entry from that list, it will likely crash (it is lacking a proper upgrade path). 

If audio works well, stay away from the audio menu :)

**Comment by c0d3h4x0r** [comment]
Yikes!  Thanks for the warning.  I never would have been able to figure that out on my own :)

**Comment by pjft** [comment]
Well, if you end up changing the audio settings and then revert back to the main ES build, you’ll need to do it again - that’s why I’m mentioning it, as I run into that every now and then when I’m testing the development builds. If you don’t touch it, it’ll be just fine!

**Comment by cmitu** [comment]
I don't think the new APi for TheGamesDB.net has been integrated, it's just using the same api, but - as @c0d3h4x0r said - with a different endoint (https://legacy.thegamesdb.net). The new API requires a  API Key and is JSON based, plus it limits the no of requests at 1000/month (per IP) AFAIK.

See for instance [this recent discussion](https://forums.thegamesdb.net/viewtopic.php?f=11&t=330) on the forum or [this](https://forums.thegamesdb.net/viewtopic.php?t=70) topic started by @muldjord about the API usage. 

From the topic postings I get they'd like application to maintain their own cache rather that scraping directly, hence the limits on the number of requests.

**Comment by c0d3h4x0r** [comment]
Indeed, that appears to be the case, at least in 'master' -- it's still using the old API via http://legacy.thegamesdb.net (note that there's no SSL/https set up/working for that URL).

**Comment by cmitu** [comment]
@c0d3h4x0r He's referring to the `-dev` as in the `emulationstation-dev` package in the RetroPie-Script, which installs the `master` branch.

**Comment by muldjord** [comment]
The new tgdb API is a bit more difficult to implement than the old one since they've started using ID's for developer and publisher instead of their actual names. So there needs to be made several queries for each. On top of that it is limited to 1000 requests per user per month per API key. It works pretty well when the work is done (as I've done in Skyscraper), but it is a bit of a step down from the old API I'm afraid. I think the EmulationStation team would be better off implementing the vastly superior screenscraper database instead. Just my five cents after having worked with a lot of the API's out there.

**Comment by c0d3h4x0r** [comment]
@muldjord what is "the vastly superior screenscraper database"?

**Comment by cmitu** [comment]
@muldjord I have a prototype working for SS..

**Comment by muldjord** [comment]
@c0d3h4x0r It's a checksum based database. https://screenscraper.fr/

@cmitu I think that would be a great addition to ES.

**Comment by cmitu** [comment]
@muldjord I just used [this doc](https://screenscraper.fr/webapi.php) for tests, I'm not sure which version of the API it is.

**Comment by c0d3h4x0r** [comment]
That sounds awesome.

**Comment by muldjord** [comment]
@cmitu That's v1. v2 is still unofficial but stable. Can be reached at https://www.screenscraper.fr/api2
The calls are the same, it's the returned xml that's changed a bit.

**Comment by c0d3h4x0r** [comment]
Wow... https://screenscraper.fr/ is an unusable mess.  It doesn't work at all under Chrome (all the JavaScript-based buttons do nothing; I had to use Firefox to even just register an account there).  Its SSL certificate is invalid (according to Firefox), so I had to add a security exception for it to even get the page to load.  Clicking on the US flag for "preferred region" doesn't seem to do anything (just reloads the page with the preferred region still set to France) unless you're signed in with a user account.  And the site itself is extremely slow (like 10+ seconds to load each page).  Also, I tried using Skyscraper with ScreenScraper against my TG16 CD-ROM collection, and it only found matches for 27 games (couldn't match 117 others).  It sure doesn't seem like a very solid back-end service with any kind of user-friendly front-end web interface... would it be a huge mistake to invest work in adopting it as RetroPie's future primary built-in scraper?

**Comment by c0d3h4x0r** [comment]
It also looks like screenscraper.fr only stores/uses the hashes of the .cue files, which isn't even the important part (and which can change from person-to-person depending on the filename they choose to use for the .cue/.bin pair).  For CD images, the .bin file is what matters.

**Comment by muldjord** [comment]
@c0d3h4x0r Don't be fooled. SS is the best retro database out there. Their website might be a mess, but the database is stellar. I have no idea why it wouldn't find your roms. It finds pretty much all of mine with all media.

**Comment by c0d3h4x0r** [comment]
How about https://gamesdb.launchbox-app.com/?  That looks like a much better done web site, at least, and they seem to have entries for a bunch of my more obscure Japanese TG16 CD-ROM games.  Not sure if they are hash-based or not though.

**Comment by muldjord** [comment]
I don't know it so I couldn't tell you. It might be better for your use case. I'll check out if they have a sensible API. It might make sense to implement it in Skyscraper if it's not too limited or closed.

**Comment by c0d3h4x0r** [comment]
@muldjord Using hashes of .cue files is never going to reliably find matches because when people rip an original disc to a .cue/.bin pair, they can give the pair whatever name they want -- and the .cue file will always contain the .bin filename, because that's how .cue/.bin pairs work.  So the only thing that makes any sense to hash and scrape is the .bin file.

**Comment by muldjord** [comment]
Depends what cue files you have, but for lesser known cue files (ones
you've created yourself) you are absolutely right.

**Comment by c0d3h4x0r** [comment]
> Depends what cue files you have, but for lesser known cue files (ones you've created yourself) you are absolutely right.

If a user wants to rename a .cue/.bin pair and manually modify the .cue file to reflect the new .bin filename, that will also render the .cue file unusable for hash-matching.  I know I've renamed plenty of .cue/.bin pairs over the years.

**Comment by muldjord** [comment]
Yes, of course.

I think this has gone off-topic. I don't have further to add to the topic.

**Comment by cmitu** [comment]
Should be fixed now by #520
