### ISSUE TITLE
v2.7.6RP installs without CEC support

### ISSUE THREAD

**Issue by CookiePLMonster** [RetroPie/EmulationStation#508]
As per this commit: https://github.com/RetroPie/EmulationStation/commit/074e22ee37bec76327b36cd84a4425953ec7f880

ES is supposed to support CEC, however as far as I can tell whatever "Update from binary" obtains doesn't ship with that.

What I had to do to get CEC support was:
1) Install `libcec4-dev` (is `libcec-dev` an equivalent meta-package like `libcec` is to `libcec4`?)
2) Install `libp8-platform-dev`
3) `Update from source` on emulationstation

Is this intentional? Update from Binary doesn't seem to do any compilation/building on my end so I am assuming wherever it's getting the binaries from, they were built without libCEC.

**Comment by joolswills** [comment]
Currently it is. I wanted to do some testing before building with libCEC support.
