### ISSUE TITLE
Mayflash Dual N64 Adapter Continues to Give Problems

### ISSUE THREAD

**Issue by supercolom642** [RetroPie/EmulationStation#509]
For the last three days or so I have been tearing my hair out over trying to properly configure the embodiment of Satan for use with RetroPie, the Mayflash Dual N64 to USB adapter.

After looking at and attempting this https://retropie.org.uk/forum/topic/7959/mayflash-n64-controller-adapter-problems-all-buttons-configure-in-es-but-no-config-files-generated-or-saved/22
this https://www.reddit.com/r/RetroPie/comments/6vnori/cant_for_the_life_of_me_get_this_mayflash_n64/
this https://retropie.org.uk/forum/topic/2944/huijia-n64-usb-adaptor-setup/9
this https://retropie.org.uk/forum/topic/12836/guide-how-to-n64-controller-setup-with-micro-s-n64-pcb-converter-and-mayflash-usb-adapter
this https://raopinion.wordpress.com/2012/01/27/mayflash-n64-controller-adapter/
and most recently, this https://raopinion.wordpress.com/2012/01/27/mayflash-n64-controller-adapter/

my controller continues to not work properly.

Running jstest commands to test my N64 controllers indicate that they work perfectly, but upon controller configuration in EmulationStation, it will not read any of my left stick analogue inputs unless I get really lucky and then it only reads the -y axis.
Manually editing all of my controls in InputAutoCfg.ini, mupen64plus.cfg, and es_input.cfg results in things like Mario just barely even walking in Mario 64, and not being able to run in Super Smash Bros.

One of the github posts I linked allowed me to mimic my n64 inputs into Xbox pad inputs, and, like I said, testing the controller in the terminal outside of EmulationStation/RetroArch indicates that it works perfectly
I’ve been working on this for the last two or three days, and I feel like I’m the closest I’ve ever been to getting somewhere but I’ve hit a wall.

In dire need of help.

**Comment by pjft** [comment]
This is really something that should be posted in the forums, not here.

I imagine that you'd be able to address this with xboxdrv:

https://github.com/RetroPie/RetroPie-Setup/wiki/Universal-Controller-Calibration-&-Mapping-Using-xboxdrv

Or maybe xpad.

Best.
