### ISSUE TITLE
Compiling and using ES on Ubuntu (not Pi)

### ISSUE THREAD

**Issue by terzag** [RetroPie/EmulationStation#510]
Hello,
I'm looking at your fork of EmulationStation as it seems a bit more up to date compared to the original version. Though, I intend to use it on Ubuntu as a standalone app, not on a Pi with RetroPie.

I cloned the repo, compiled it, all went fine. When I run the bin from the compilation directory, it works well, but as soon as I move it elsewhere, I get the following error:

```
lvl0: 	Error - File type unknown!
emulationstation: /home/terzag/Dev/EmulationStation/es-core/src/resources/Font.cpp:17: Font::FontFace::FontFace(ResourceData&&, int): Assertion `!err' failed.
Abandon (core dumped)
```
(/home/terzag/Dev/EmulationStation is the directory cloned from GIT)

What am I doing wrong?

**Comment by 5schatten** [comment]
Do you mov/copy the `resources` folder  too?

**Comment by terzag** [comment]
No. As the version from Aloshi doesn't seem to have them installed, I thought they were "embedded" in the binary. Where should I put them for the bin to find them (assuming it'll be in /usr/bin)?

**Comment by terzag** [comment]
Thanks, it works. Has the suggestion to look for the resources in /usr/share (as in #427) been implemented or is planned?

**Comment by joolswills** [comment]
No I don't think it has been implemented, but it could be if someone contributes the changes (I don't have time currently). Note that this fork of ES is developed for use with RetroPie, not as a standalone project etc.
