### ISSUE TITLE
Screen Saver Environmental Friendly Option

### ISSUE THREAD

**Issue by moononournation** [RetroPie/EmulationStation#511]
There are no option to turn the screen off after idle a certain of time. It is very waste of power especially you choose black out the screen, you will not award the screen still turned on and waste tens or hundreds of Watts overnight. #377 is a good suggestion to add a custom script option to operate power saving stuff.

**Comment by Gemba** [comment]
Please close, it's implemented with PR #560 (v2.9.2 onwards).
