### ISSUE TITLE
Scraping is broken on Windows (in some cases)

### ISSUE THREAD

**Issue by herebcs** [RetroPie/EmulationStation#513]
ES on Windows sometimes detects totally independent files as equal because isEquivalent is not properly implemented. The stat64 based approache does not work for files with the same length and creation date, but this is a typical setup for certain emulators. In these cases you do not scrape the actual roms, but different files containing ids, descriptors, etc. Moreover these files are frequently generated by some tool or script, so it is not rare that many files have the same size and creation date.
Because of the bug and the way how the scraper works in these scenarios existing games are frequently overwritten and will appear as un-scraped after restart.
I fixed isEquivalent in #512 and tested the code successfully.

**Comment by jrassa** [comment]
Fixed in #549
