### ISSUE TITLE
Scraper no longer working

### ISSUE THREAD

**Issue by acrummyidea** [RetroPie/EmulationStation#516]
TheGamesDb offlined for good their legacy api endpoint so the default scraper no longer works. Possible solutions include supporting the new json api, or adapting one of the other available scrapers

**Comment by acrummyidea** [comment]
I’m taking a stab at modifying the scraper to use the new api

**Comment by 5schatten** [comment]
Just wondering if it would make sense & of course be possible to adopt the API to https://screenscraper.fr if you have to re-write it anyway...?

**Comment by acrummyidea** [comment]
I'll  take a look. I have a working version using thegamesdb. I should be able to send a PR it in a few days. The code supports multiple scrapers so it's possible to have both.

**Comment by acrummyidea** [comment]
@5schatten the PR is in. Any additional testing is welcome and appreciated :)

**Comment by Nikorasu95** [comment]
When will this be merged?

**Comment by tomaz82** [comment]
> When will this be merged?

When it's done

**Comment by Nikorasu95** [comment]
Jeez, I was just asking, Mr. Smart-Aleck. In case you didn't know, there are a lot of people who scrap their games with the built-in scraper because of its ease of use versus using other scrapers. At least have it where you can change the built-in scraper to a different one just like in RecalBox instead of having to enter the Retropie Setup or command line to scrap individual games.

**Comment by HerbFargus** [comment]
Nobody here works for you. Everything is open source so feel free to merge in the patches manually on your own build if you're too impatient for these blokes who do this in their free time. Their time is probably better spent coding than fielding requests on when they'll be done.

**Comment by joolswills** [comment]
Congratulations @Nikorasu95. You have made it to the blocked users list..

**Comment by Lumbeeslayer** [comment]
> Nobody here works for you. Everything is open source so feel free to merge in the patches manually on your own build if you're too impatient for these blokes who do this in their free time. Their time is probably better spent coding than fielding requests on when they'll be done." You people are so rude! Only thing this person asked was "when it will be merged" and then both @tomaz82 and you@joolwills had to attack him by being rude! And on top of that @joolswills had to block him. This person done nothing wrong. All he did was ask when this fix is going to be merged and instead y'all get hysterical. I as much want this issue fixed as much as @Nikorasu95. I have individual games to scrap and I can't get both skyscraper or Steven Selph's Scraper to work correctly. I followed the guides yet I get an error when trying scrape individual games which can only be done in command-line.

**Comment by joolswills** [comment]
He got blocked for making a personal attack. And use the forum not this ticket please. This is not the place for your thoughts and help on scraping.

**Comment by Lumbeeslayer** [comment]
> He got blocked for making a personal attack. And use the forum not this ticket please. This is not the place for your thoughts and asking for help on scraping.

Or that people are just so rude on Github and rather block someone instead of communicating. This article explains it all! https://www.zdnet.com/article/github-open-source-is-dominated-by-men-who-just-cant-communicate/

**Comment by dankcushions** [comment]
@Lumbeeslayer you're the same person as @Nikorasu95.

https://forums.dolphin-emu.org/Thread-unofficial-ishiiruka-dolphin-custom-version?page=562
https://github.com/RPCS3/rpcs3/issues/4341

i see you've made a bit of a habit out of creating extra accounts in order to pester those who do the work (for free) that you're not able to.

> You people are so rude.

**Comment by pjft** [comment]
@Lumbeeslayer this is getting a bit off track. @tomaz82 's and @HerbFargus 's answers might have been short or in a different direction, but they were far from attacks or being rude. They were just facts. And, in fact, @HerbFargus 's answer was actually productive in that it offered an alternative for anyone to start using the code in the meantime. 

Anything and everything here is a benefit, not a right.

**Comment by Lumbeeslayer** [comment]
> @Lumbeeslayer you're the same person as @Nikorasu95.
> 
> https://forums.dolphin-emu.org/Thread-unofficial-ishiiruka-dolphin-custom-version?page=562
> [RPCS3/rpcs3#4341](https://github.com/RPCS3/rpcs3/issues/4341)
> 
> i see you've made a bit of a habit out of creating extra accounts in order to pester those who do the work (for free) that you're not able to.
> 
> > You people are so rude.

https://www.zdnet.com/article/github-open-source-is-dominated-by-men-who-just-cant-communicate/
I don't know how you can come to an conclusion that person is also me. In case you didn't know there an estimate of more than 7.53 billion in the world. That can be anyone.

**Comment by dankcushions** [comment]
@Lumbeeslayer because you two are all over net saying "I think lumbeeslayer/Nikoraus95 is right. here's another

https://forums.dolphin-emu.org/Thread-unofficial-ishiiruka-dolphin-custom-version?pid=424184#pid424184

have a real hard think about how you conduct yourself.

**Comment by gilbertohasnofb** [comment]
I see that the PR with the fix for this has been merged but I am still having issues with the built-in scraper. I am on a Raspberry Pi 3 B+ and I updated my EmulationStation from source using RetroPie's setup script, launched as root. Am I trying to update it wrongly?

**Comment by acrummyidea** [comment]
When you select the scraper do you see one or two scrapers available? If you see 2 you’re in fact using the latest version. For the gamesdb scraper the first time you run it you may have to wait up to a minute and a half to download 3 resource files. After that it will be quick.
Can you tell us more precisely what problem are you observing?

**Comment by HerbFargus** [comment]
Ah that explains the initial delay. Works great for me as of compilation last night

**Comment by joolswills** [comment]
They are not running the -dev version - I've not yet merged this to the stable branch. @gilbertohasnofb you need to install emulationstation-dev to test this currently. Please use the RetroPie forum for further support. Will close this ticket now.

It will be merged to the stable branch when I have finalised some other changes.

**Comment by gilbertohasnofb** [comment]
> you need to install emulationstation-dev to test this currently.

That explains it. I will wait for this to be available on RetroPie and I am happy to report back here once it starts working again. Thanks a lot!

**Comment by retrorepair** [comment]
So some feedback on the new scraper code.

TheGamesDB was working great (aside from a few crashes) for a while but suddenly it stopped working (mid scrape) and won't work at all now. The log shows:

"lvl1: 	TheGamesDBJSONRequest - Response had no game data."

I tried removing the .json database files in /scrapers but that didn't help.

Screenscraper picks a random(?) game and applies it to every game, so for example for SNES it changed all the games to Jurassic Park Lost world for Genesis! The log says:

"lvl0: 	ScreenScraperRequest - Error parsing XML.
No document element found
lvl2: 	Added/Updated 1 entities in '/home/ra/.emulationstation/gamelists/snes/gamelist.xml'"

**Comment by retrorepair** [comment]
Also, is there a way to scrape Neo Geo CD games? Seems there is zero support for this system in RetroPie/ES.

So glad you guys are working on the built in scraper though, I can't use the external ones as my roms directory is on another drive and honestly they are a bit difficult to use!

**Comment by retrorepair** [comment]
Sorry, I can't edit my post for some reason, but when I delete the .json files in /scrapers ES doesn't create them again.

**Comment by retrorepair** [comment]
Ok, so I updated seeing the screenscraper issue was fixed and that source is now working :)

Every 10 or so scrapes though it'll say "Error saving resized image. Out of memory? Disk full?" Neither of these is true.

From the log:

"lvl0: 	Error - File type unknown!
lvl0: 	Could not initialize texture from memory, invalid data!  (file path: , data ptr: 85132224, reported size: 37)
lvl0: 	Could not resize image! (not enough memory? invalid bitdepth?)
lvl2: 	ScraperSearchComponent search error: Error saving resized image. Out of memory? Disk full?"

**Comment by retrorepair** [comment]
Also it skips about a hundred or so roms when it does that, sometimes it'll skip about a hundred roms on it's own.

**Comment by retrorepair** [comment]
file:///home/ra/.emulationstation/es_log.txt
Thought it'd be easier to just post the log here

**Comment by retrorepair** [comment]
Thought it'd be easier to just post the log here

**Comment by acrummyidea** [comment]
@retrorepair, both the initial description and the fact that the resource files are not being downloaded suggest that you may have used up all the allowed monthly API calls. I don't recall the monthly allowance but it should be around 1500 if you have  scanned 1000+ games I'd say that's the issue. I should have checked for that and printed an explicit warning I guess

**Comment by retrorepair** [comment]
@acrummyidea I didn't know that but to be fair, it will keep scraping after that so don't know that's the issue.

**Comment by cmitu** [comment]
I guess this issue can be closed now.

**Comment by joolswills** [comment]
Yep. Thanks.
