### ISSUE TITLE
New ES stable release

### ISSUE THREAD

**Issue by joolswills** [RetroPie/EmulationStation#518]
Hi all - @jrassa @psyke83 @@tomaz82  et al

Anyone know any major issues on the trunk version? - It's been a long time since a stable release with new features etc, and there are a bunch of bug fixes on master.

If people think the current dev version is stable, I would be happy to update the stable branch,

**Comment by joolswills** [comment]
Apart from the broken scraper of course. I'm planning on disabling that (at least until we have a replacement using screenscraper or something).

**Comment by pjft** [comment]
I am not aware of any meaningful issues on the dev branch. There's a small issue with the upgrade path for the new audio settings which I'm not fully comfortable with - it can lead to a crash when in the menu - but other than that all good.

I do wonder: is it still useful to have the two branches? 

Happy New Year everyone.

**Comment by joolswills** [comment]
Well, there was some major development before on master, which wasn't ready right away, so the stable branch is useful. I like having a stable branch so we don't have to worry too much if there is a bug with a new feature.

**Comment by joolswills** [comment]
There is this also 9ab5223d352e330fb9e9362ad39e156e111d1cfb - which I did only on stable, but I think I may do that on master also, until there is a better solution as it's a big performance hit.

**Comment by cmitu** [comment]
I am planning to submit a patch for the scraper, enabling scraping from ScreenScraper.fr (https://github.com/cmitu/EmulationStation/tree/screenscraper). 
The new addition works only `master`, since it uses some functions added after the Boost elimination, but can probably added to the `stable` with a few additions. 
If you plan to change the `stable` branch, it would be helpful to merge the changes in the `Utils` namespace to it. Should I wait for the `stable` switch or should I submit the PR before ?

**Comment by joolswills** [comment]
Thanks. Please submit PR for master. I'll merge and update stable for a new release (I might do a couple of minor things also).

**Comment by cmitu** [comment]
@joolswills Done - https://github.com/RetroPie/EmulationStation/pull/519.

**Comment by acrummyidea** [comment]
@joolswills  Updated TheGamesDB scraper PR is in: #520

**Comment by 5schatten** [comment]
@joolswills 
I've tried https://github.com/RetroPie/EmulationStation/pull/520 and LGTM. Scraping worked fine for my tested games (Doom/Doom2/Quake).

**Comment by acrummyidea** [comment]
@joolswills let me know if I can help in any way :)

**Comment by joolswills** [comment]
Testing es dev. Reproduced the crash in menu due to unset audio card. That definitely needs sorting. If unset we need to choose a default I guess. Not checked the code related to this.

**Comment by cmitu** [comment]
I can take a look. I guess the problem is caused by the https://github.com/RetroPie/EmulationStation/pull/460 ?

**Comment by pjft** [comment]
Yep. Happy to look into it either way, I suppose it's just a matter of, when losing the settings, if the value isn't recognized, selecting an appropriate new value for the pi (or the device).

**Comment by pjft** [comment]
I'll look into it tonight, likely.

**Comment by pjft** [comment]
#523 should actually do it.

**Comment by joolswills** [comment]
@tomaz82  I was thinking - rather than revert cd2f2ee4 would it be better to make it optional (but default to off). That way people can use it if they want. If so, what should the setting be called ? "Load matching art not in gamelist" ? hard to word this one.

**Comment by joolswills** [comment]
eg -https://github.com/RetroPie/EmulationStation/pull/526 - anyone have anything against this ?

**Comment by joolswills** [comment]
Stable branch is updated (to v2.8.0). Thanks all.

**Comment by 5schatten** [comment]
can you tag the release?

**Comment by joolswills** [comment]
I will later. Just build from the stable branch for now.
