### ISSUE TITLE
Jagged Font in Gamelist Basic View

### ISSUE THREAD

**Issue by dudleydes** [RetroPie/EmulationStation#538]
This relates to the jagged font bug that has been in EmulationStation since ES 2.0 was released in July 2014. There remains an [open ticket](https://github.com/Aloshi/EmulationStation/issues/176) at Aloshi's Github page. The issue was discussed recently at the [forum](https://retropie.org.uk/forum/topic/21426/distorted-font-font-not-rendering-correctly-in-certain-es-theme).

The bug is straightforward to replicate:- Select the vanilla Carbon theme that comes, by default, in the RetroPie image and change the Gamelist View Style to `Basic` in UI Settings.

I noticed it again recently when I was developing a custom theme for my Picade build. I believe the bug occurs when the `<alignment>` tag in the `<gamelist>` section of the theme XML is set to `center`, as it is in the [Carbon](https://github.com/RetroPie/es-theme-carbon/blob/master/carbon.xml#L79) theme as well as others.

Here are my findings using the CRT Centered theme by editing [these lines](https://github.com/anthonycaccese/es-theme-crt-centered/blob/master/_inc/templates/4x3.xml#L64) in the theme XML:

**Alignment `center`**
Theme XML excerpt
```
     <textlist name="gamelist">
         <pos>0.05 0.575</pos>
         <size>0.9 0.3277777777777778</size>
         <alignment>center</alignment>
      </textlist>
```
![centered](https://user-images.githubusercontent.com/8166945/53695150-d5613700-3daf-11e9-802f-fd4cecc5b21f.png)

**Alignment `left` and gamelist moved towards middle with `<pos>`**
Theme XML excerpt
```
      <textlist name="gamelist">
         <pos>0.425 0.575</pos>
         <size>0.9 0.3277777777777778</size>
         <alignment>left</alignment>
      </textlist>
```
![left](https://user-images.githubusercontent.com/8166945/53695183-15281e80-3db0-11e9-8c10-2d4bfed6fc58.png)

Setting the `<alignment>` tag to `left` instead of `center`, the text can occupy a similar central position without jagged edges.

**Comment by pjft** [comment]
Thanks. This had been a longstanding pet peeve for me, though to be honest I had never bothered to look into it. 

Your tests and description pretty much spelled out that it would be a rounding error, which seems to be the case.

I submitted #539 which should fix it, but would certainly appreciate your confirmation.
