### ISSUE TITLE
Can't open or execute ES in Xubuntu 18.10

### ISSUE THREAD

**Issue by CamJRP** [RetroPie/EmulationStation#543]
After trying to execute the program from terminal i get this error message:
lvl0: 	Error - File type unknown!
lvl0: 	CECInput::mAdapter->DetectAdapters failed
emulationstation: /home/camilo/EmulationStation/es-core/src/resources/Font.cpp:17: Font::FontFace::FontFace(ResourceData&&, int): Assertion `!err' failed.
Aborted (core dumped)

After compiling the program i used "cmake install" in order to install it.

Thanks in advance

**Comment by joolswills** [comment]
You didn't copy/install the resources folder. Please use the retropie forum for support though.

https://github.com/RetroPie/EmulationStation/issues/510#issuecomment-446288480
```
