### ISSUE TITLE
(Xbox 360) Controller configuration heavily broken.

### ISSUE THREAD

**Issue by MrJPGames** [RetroPie/EmulationStation#56]
It took me ~40 attempts to configure my Xbox 360 Controller correctly. The problem was always with the "bottom left/right triggers". It would not register the actual triggers, register the release axis or would swiftly skip them and set the top trigger to be the bottom trigger I was pressing at that time. Though you can technically still configure it correctly it should definitely not be this hard. A easy fix would be to allow you to after configuration go back and change specific buttons.

**Comment by joolswills** [comment]
If you press them slowly it shouldn't take so many attempts. You can go "up" after getting to ok and reconfigure them without having to reconfigure everything else also. 

https://github.com/retropie/retropie-setup/wiki/Logitech-controllers#l2r2-top-triggers

it is unlikely this will be looked at anytime soon unless someone provides a PR with a fix.

**Comment by MrJPGames** [comment]
It's good that you can go up, but how? I tried but I couldn't press the ok button or go up, I just had to wait. So just in case others with the same problem come here (or I have to reconfigure mine) could you tell me how you can go up, because the up button on my controller didn't do it (not did any other button).

Thank you.

And because you can go up I find it reasonable that this won't be looked at because it not too big of an issue in that case.

**Comment by joolswills** [comment]
You can change the settings when configuring just on the 360 controller. Configure all the controls skipping triggers if required - then when you get to "OK" use the dpad to navigate back up.

**Comment by MrJPGames** [comment]
This does not work for me. I need a second controller to go back up, after that the 360 controller does work but it does not allow me to enter it. Idk why though.

**Comment by joolswills** [comment]
Just tested here with a wired 360 and it worked ok. I configured everything except triggers, then when on OK I used the dpad to navigate up and configure the triggers.

**Comment by HerbFargus** [comment]
I can also confirm that it works with my wireless xbox360 controller

**Comment by joolswills** [comment]
Workaround for analogue trigger configuration issue https://github.com/RetroPie/EmulationStation/pull/58

**Comment by joolswills** [comment]
The workaround didn't go to well. I made an assumption regarding initial value from joypad, and it seems others also have an initial value the same (Which would explain when connecting an 8bitdo pad it starts moving on its own until something is pressed). 

I have now worked around it in the xpad driver available from retropie-setup (makes the trigger work as buttons as we did with the xboxdrv and problem is solved)
