### ISSUE TITLE
[feature request] "Beaten" and "Not working" metadata options.

### ISSUE THREAD

**Issue by Loquo** [RetroPie/EmulationStation#564]
Good afternoon.

I really would like to mark in any way what games can't be played properly (for example, that ones that should be played with periphericals like lightguns, keyboards type controllers, trackballs, spinners, NES power pad, ect., or... bad emulation), and in the other hand what games I have beaten.

I would be neat that we could mark any game as "not-working" or "beaten", in the same way you can mark any game as "favorite", "hidden" or "kidgame".

I would like this options work this way:

    Not working: The game in the game list has a "warning icon" or a "wrong icon". Other way could be attenuate the color of the font for the games marked as "not working".
    Beaten: I would be nice to mark games beaten with a medal icon or similar.

Thank you very much.

**Comment by pjft** [comment]
Thanks for the suggestion.

There's no current plan to add such icons to differentiate games for the moment. There was, at one time, an icon for favorite and kidgame, but that no longer exists as the specs for the layout side of things weren't further developed.

I imagine starting with those two would probably be the first step to even consider adding further icons, if even agreed upon.

But for the short term, the best alternative is to create a collection for those not-working and/or beaten if you want to keep track of them.

I know it's not the answer you're looking for, but I don't expect a different answer to come up in the short-to-medium-term.

For future reference, this type of ideas or requests would be better off in the forums as the idea can certainly be better fleshed out there, and/or alternatives or workarounds may come up. The "issues" section here is hardly a "feature request" list, though anyone is welcome to contribute with developments.

Best.

**Comment by Loquo** [comment]
Ok, thanks for the quick answer.
