### ISSUE TITLE
rpi 3 A+ hanging during input startup screen

### ISSUE THREAD

**Issue by r9guy** [RetroPie/EmulationStation#580]
I have tried to run retropie fresh installation on RPI 3 A+ model.
during keybinding screen then I need to press and hold button to detect controller and assign keys EmulationStation stucks, and the only way is to restart it with F4.
i removed the SD card and tried on RPI 3 B+ and everything worked great.

**Comment by joolswills** [comment]
Please use the RetroPie forum for support.
