### ISSUE TITLE
[Feature Request] More user-friendly UI for save/restore game state

### ISSUE THREAD

**Issue by hzulla** [RetroPie/EmulationStation#585]
Hi there.

It would be nice if it were easier to stop playing at any time and continue playing later.

For that, Retropie/EmulationStation could automatically save the state of a game when the player leaves it via [Select]+[Start] or when the player powers off the system via a shutdown script.

This could then be used together with #469 or alternatively EmulationStation could ask after it started _"do you want to continue playing where you stopped last time?"_

Gamer dad here.

I have an observation on gaming behaviour with my kid, who enjoys video games as much as I do. It's difficult to stop playing, especially for a kid. When gaming, we often get into arguments when it's time to finish. "I just want to finish that level" or ["just five more minutes"](https://www.picklestore.nl/de/play-five-more-minutes-by-nemimakeit-97204452.html) is probably a familiar refrain in every household where the kids play video games.

When you force your kid to drop that game controller because time's up or dinner is ready, most games will lose the player's progress. Some games even make it a point to not include enough savepoints in order to make the game "more challenging". When the game's progress is lost, I made the observation that my kid experiences this as a loss of achievement / a failure to finish the level on time.

I'm aware that you already can manually save/restore the state, but the user experience is clunky and not obvious to find when you begin using EmulationStation. We'd have a lot fewer arguments in our family if storing / restoring the game's state were easier and more straightforward for a kid user.

**Comment by dankcushions** [comment]
already possible :) see https://www.reddit.com/r/RetroPie/comments/6to1vh/comment/dlni6sf?utm_source=amp&utm_medium=&utm_content=comment_timestamp

**Comment by hzulla** [comment]
Thanks! Now I'd love to see a more user-friendly way to restore the game state, such as #469.

**Comment by dankcushions** [comment]
ok! so i guess this can be closed and discussion can continue over there?

**Comment by hzulla** [comment]
Yes, probably. Thanks.
