### ISSUE TITLE
Make it possible to disable logging, control log level, or change log location.

### ISSUE THREAD

**Issue by crocket** [RetroPie/EmulationStation#596]
Currently, even if I symlink a location in /tmp to ~/.emulationstation/es_log.txt, emulationstation replaces it with a regular file.

I want to disable logging to storage.

**Comment by shantigilbert** [comment]
I made a change to enable setting up the log path 

https://github.com/shantigilbert/EmulationStation/commit/189d73b2d1d51732546cb798d7630ec89e6b450b

if you can compile and test it I can open a PR

**Comment by crocket** [comment]
The build fails on gentoo linux.

[build.log](https://github.com/RetroPie/EmulationStation/files/3568163/build.log)

**Comment by shantigilbert** [comment]
It does but its not related to the change I made 

```
-- Could NOT find Rapidjson (missing: RAPIDJSON_INCLUDE_DIRS)
```

**Comment by crocket** [comment]
Of course, it's not related to your change.
But, someone needs to fix the build.

**Comment by cmitu** [comment]
@crocket this is not the correct repo to correct your build - you should report it to the Gentoo Linux package maintainer. Emulationstation requires now the `rapidjson` library to build and work - if it's not installed on the build system, of course the build will fail.

**Comment by crocket** [comment]
After installing rapidjson, I got the following error.

```
 * Detected file collision(s):
 *
 *      /usr/include/pugiconfig.hpp
 *      /usr/include/pugixml.hpp
 *      /usr/lib64/cmake/pugixml/pugixml-config-gentoo.cmake
 *      /usr/lib64/cmake/pugixml/pugixml-config.cmake
 *      /usr/lib64/libpugixml.so
 *      /usr/lib64/libpugixml.so.1
 *
 * Searching all installed packages for file collisions...
 *
 * Press Ctrl-C to Stop
 *
 * dev-libs/pugixml-1.9-r1:0::gentoo
 *      /usr/include/pugiconfig.hpp
 *      /usr/include/pugixml.hpp
 *      /usr/lib64/cmake/pugixml/pugixml-config-gentoo.cmake
 *      /usr/lib64/cmake/pugixml/pugixml-config.cmake
 *      /usr/lib64/libpugixml.so
 *      /usr/lib64/libpugixml.so.1
 *
 * Package 'games-emulation/emulationstation-9999' NOT merged due to file
 * collisions. If necessary, refer to your elog messages for the whole
 * content of the above message.

```

It seems that emulationstation is trying to install some files that pugixml already has.

**Comment by cmitu** [comment]
@crocket again, this is not the place to fix the Gentoo packages conflict - report it to distribution package maintainer.

**Comment by crocket** [comment]
@cmitu I'm the maintainer for my own local gentoo repository. Why does emulationstation install files that seem to belong to pugixml?

**Comment by cmitu** [comment]
@crocket - please look at the build instructions at https://github.com/RetroPie/EmulationStation. This issue is not about building ES and I think the instructions on the page are pretty clear.
If you're unable to create a Gentoo build to support ES, then ask the a Gentoo maintainer to help you create a proper ebuild configuration file.

**Comment by crocket** [comment]
There is an issue with building ES. It conflicts with pugixml since it comes with pugixml. I had to disable internal pugixml such that system pugixml takes place.

After patching and building emulationstation, I got this error.

```
> emulationstation
lvl0:   Error - File type unknown!
fish: “emulationstation” terminated by signal SIGSEGV (Address boundary error)
```

There is no relevant log in ~/.emulationstation/es_log.txt

**Comment by joolswills** [comment]
This is not an issue with Emulation Station. This is a packaging issue for Gentoo. It's designed to be built with our internal pugixml. We can't debug an issue due to changes you have made.
