### ISSUE TITLE
Allow internal pugixml to live alongside system pugixml.

### ISSUE THREAD

**Issue by crocket** [RetroPie/EmulationStation#607]
Some packages like openimageio require system pugixml which conflict with emulationstation.

I have two choices.

* Patch emulationstation to disable internal pugixml and make it use system pugixml which this project doesn't support.
* Make internal pugixml live alongside system pugixml.

Is it possible to make internal pugixml live alongside system pugixml?

**Comment by joolswills** [comment]
it compiles and works fine here with a system pugixml installed on Ubuntu. I suspect this is an issue with your setup. Your previous crash might have been related to not installing the resources folder btw. if there is a problem on your specific distro, you are going to have to work out a fix yourself I'm afraid. This project is primarily developed for RetroPie.
