### ISSUE TITLE
ES freezes and crashes in the gamelist view

### ISSUE THREAD

**Issue by hzio** [RetroPie/EmulationStation#610]
Hi there, recently I found a boring bug, there are 2000+ games in my arcade system, ES freezes and crashes after holding the joypad's DOWN button for about 30 seconds in gamelist view, this issue appears in both video UI mode and detail UI mode, please help :(

**Comment by joolswills** [comment]
Please can you start a topic on the retropie forum first. Providing details of config.

**Comment by joolswills** [comment]
Unable to reproduce on my set up. If it's confirmed an issue on the forum we can re-open. Thanks.
