### ISSUE TITLE
emulation station and strange resolutions

### ISSUE THREAD

**Issue by zanac** [RetroPie/EmulationStation#616]
Hi,

i'm running xorg using an ancient arcade cab machine monitor (15 khz), using that i use a strage resolution: using xorg (wayland cannot do that) i used xargs for switch to 1920x240:

#! /bin/bash
xrandr --newmode "cga_1920_240" 37.778 1920 1977 2154 2376 240 243 245 265 -hsync -vsync
xrandr --addmode DP-1 "cga_1920_240" 
xrandr --output DP-1 --mode "cga_1920_240"

Using these commands i can run emulation station but the fonts are unreadable, so i try to make a "virtual" resolution of 384x240, last command is therefore:
xrandr --output DP-1 --mode "cga_1920_240" --scale-from 384x240 --pos 1x1

When i start emulation it draw using 1920x240 inside a portion of 384x240.... also using --resolution 384 240 it don't draw well.

There is a workaround?

p.s. i cannot use a modeline of 384x240 'cause the graphic card don't want to use that!

**Comment by jrassa** [comment]
@zanac In the future, please post in the RetroPie forums, as requested, for support.  Github is intended for development use and only a select few people see the issues here.

The screensize/screenoffset options might help.  Below is a guess at what might work.  You may need to tweek the numbers.

`emulationstation --screensize 384 240 --screenoffset 768 0`

**Comment by zanac** [comment]
Hi,
thank for the tip, i know that this is a developer forum.... i'm the original author of the "rotate" patch of emulation station (see https://github.com/RetroPie/EmulationStation/pull/348 ), indeed i thought that this was an issue but... i will try your parameters, but if don't work we will need a way to force it (so i will try to develop a patch as i done with rotate ;))
