### ISSUE TITLE
PNG transparency trouble

### ISSUE THREAD

**Issue by sergiopoverony** [RetroPie/EmulationStation#629]
Pi3A+, PI3B, PI3B+
EmulationStation 2.9.0RP after update (in theme Picade maybe any) transparency background not transparency, him simple GRAY color but BLACK in preview version EmulationStation.

**Comment by tomaz82** [comment]
Will be fixed by https://github.com/RetroPie/EmulationStation/pull/626

**Comment by cmitu** [comment]
Probably fixed in https://github.com/RetroPie/EmulationStation/commit/b6f0f5c2c7af79dd421db83b3b952764603be897.
