### ISSUE TITLE
Screen rotation of emulationstation doesn't work on v.2.9.0

### ISSUE THREAD

**Issue by krahsdevil** [RetroPie/EmulationStation#636]
Hi.
In this emulationstation version v.2.9.0RP, flag **--screenrotate** doesn't work as expected...
When launched **--screenrotate** flag with **_0_** (0 degrees, horizontal default) or **_2_** (180 degrees) all is fine but, when **--screenrotate** is setted with **_1_** (90 degrees) or **_3_** (270 or -90 degrees) that's means... in vertical mode, emulationstation interface rotates but doesn't fit the full screen.

On emulationstation v.2.8.4RP works perfect...

Thanks!

**Comment by jrassa** [comment]
When using **--screenrotate** set to **1** or **3** you now have to explicitly set **--screensize** as well.  For example, if you are rotating a monitor with a resolution 1920x1080, you would have to set `--screenrotate 1 --screensize 1080 1920`.

Also, where did you get v.3.8.4RP?  The current stable version for RetroPie's ES is v.2.9.0RP and the current dev version is v.2.10.0RP.

**Comment by krahsdevil** [comment]
I'm sorry it was a misprint, version is v.2.8.4RP ... (previous stable release of retropie's emulationstation).
Would be nice if it works as it did, without detailing resolution ... could it be possible?
For CRT devices is highly demanded...

**Comment by krahsdevil** [comment]
Hi, effectively it works perfect if —screenresolution is specified. Finally I’ve found a way to handle it for my situation.
I close the issue...
Thanks!
