### ISSUE TITLE
latest update v.2.9.0 not opening in Manjaro Linux

### ISSUE THREAD

**Issue by m1s3rys1gn4l** [RetroPie/EmulationStation#637]
i am having problem with v.2.9.0.1 in Manjaro Linux,
its not opening :( everything was perfect till todays update.

**Comment by cmitu** [comment]
There is no v2.9.0.1 version tagged in this repository - maybe the issue is with the distro's package.

**Comment by m1s3rys1gn4l** [comment]
> There is no v2.9.0.1 version tagged in this repository - maybe the issue is with the distro's package.

ahh ok.

**Comment by m1s3rys1gn4l** [comment]
i got this error from terminal.
`[m1s3ry@HyperX ~]$ emulationstation
lvl0: 	Error - File type unknown!
emulationstation: /var/tmp/pamac-build-m1s3ry/emulationstation/src/EmulationStation-2.9.0/es-core/src/resources/Font.cpp:21: Font::FontFace::FontFace(ResourceData&&, int): Assertion `!err' failed.
Aborted (core dumped)`

**Comment by cmitu** [comment]
Looks like a packaging error - package doesn't include the necessary resources. Often reported - if you would have searched the issue tracker, you'd have found it: https://github.com/retropie/EmulationStation/issues?q=is%3Aissue+Font%3A%3AFontFace%3A%3AFontFace+is%3Aclosed.
