### ISSUE TITLE
Occasionally slow menus on RPi 4

### ISSUE THREAD

**Issue by atylmo** [RetroPie/EmulationStation#638]
I noticed that, at least with the Pi 4, the menu animations randomly switch between 30 and 60 FPS. When I flip through the main screen's list of consoles, the transition animation between them feels slow and not smooth. When I turn on the frame counter I can see that the main menu runs at 30 FPS, but once I enter into a console's game list it switches to 60. The style of animation doesn't matter. Whether it's set to fade, slide, or instant, the frame rate still drops.

The thing is, this doesn't happen all the time. Sometimes, when I come out of a script menu or out of a game the issue is fixed (the main menu runs at 60 too), but not always. I don't think it's necessarily a performance problem because the drop is always to a stable 30 and then back to a stable 60. It isn't caused by thermal throttling, either.

I think it has something to do with background images or console images, because if I have a custom console added that doesn't have theme art then the animation switching to it is fine, but switching to the others that do have art slows down.

I'm suspicious of it accidentally running at 4K, even though it's hooked up to a 1080p monitor. That's something I need to look into more. Still, the fact that it's occasionally smooth makes me suspect something else.

**Comment by cmitu** [comment]
This is not an EmulationStation issue, but something related to the KMSDRM video driver in SDL2. Make sure you're fully updated, Raspbian and RetroPie, then try again.

**Comment by atylmo** [comment]
Ah, sorry. Will do, thank you :)

**Comment by atylmo** [comment]
I am fully updated now but it still exhibits the same behavior.

**Comment by joolswills** [comment]
It's not an ES issue. But you should use the forum as requested when opening a ticket.

**Comment by atylmo** [comment]
I planned on it but they say not to post RPi 4 issues there.
