### ISSUE TITLE
Add scraper for OpenVGDB

### ISSUE THREAD

**Issue by dorianmuthig** [RetroPie/EmulationStation#64]
The current scraper uses the file name, which is quite unreliable and a pain to work with when you initially add several thousand ROMs. Especially so, if you have numbers and Roman numerals confused. [OpenVGDB](https://github.com/OpenVGDB/OpenVGDB/releases) uses ROM hashes or their internal CRC checksums to identify game ROMs. This is the most exacting method there is and can work fully autonomously without any user intervention. Do you guys think it's possible to have a look at [OpenVGDB/Parser](https://github.com/OpenVGDB/Parser) and adding it as a scraper method? Would improve the application/system much. :)

**Comment by HerbFargus** [comment]
https://github.com/retropie/retropie-setup/wiki/scraper

**Comment by dorianmuthig** [comment]
Yes, um, I read all that. But the options described do not exist anymore. In the current RetroPie Raspberry Pi image the scrapers which are installed are "TheArchive" and "TheGamesDB", with the latter being set as default.
The built-in scraper is working with the file *name* only, but you should instead work with the file *hash* and file *size*. That would, provided it has been read correctly from the cartridge or disk and not been tampered with, work with the greatest reliability, no matter what you called your files.
Yes, I know, I can just download the OpenVGDB sqlite file myself, write a little code and then attach a scraper to the script, but that would still only use the file name, which to me is irrelevant. I want the hash. Can you get me the file hash and file size for database searching please? :) 

PS: There's also this thing about sensible defaults, I'm sure you've heard about... not that I want to poop on your parade or anything...

**Comment by zigurana** [comment]
What I think @HerbFargus meant, is that basically nobody uses the build-in scraper, but uses the option provided by [Stephen Selph](https://github.com/sselph/scraper) (which supports openVGDB btw). 
Using an external tool allows Stephen to maintain it much easier than if it would be incorporated in ES. 

Bare in mind that this fork of ES is not under active development, but serves as a basket to pull in essential fixes only.

PS: If you are volunteering to update EmulationStation's default values to better reflect the current status-quo, I am sure the good people at RetroPie are willing to consider your pull-requests.

**Comment by zigurana** [comment]
See also #50
