### ISSUE TITLE
Wrong positioning of videos when OMX Player enabled in rotate mode

### ISSUE THREAD

**Issue by krahsdevil** [RetroPie/EmulationStation#649]
Hi.
I realize when emulationstation is rotated and OMX player enabled for HW acceleration videos are not well positioned as per theme configuration.
If I disable OMX Player (OFF) and restart ES then videos are well showed

**Comment by pjft** [comment]
Need a few more details - rotation parameters, ES version, theme, etc. I recall @tomaz82 and I spent a fair bit testing those, so that would help.

**Comment by krahsdevil** [comment]
Sure.
EmulationStation version: V.2.9.0.RP
Rotation Launch parameters: --screenrotate 1 --screensize 240 320
Theme: custom theme <formatVersion>4</formatVersion>

System resolution is already at 320x240@60hz

It happens with any theme, let me know if you want to test mine.

**Comment by pjft** [comment]
Thanks. Can you check if this fixes it? https://github.com/RetroPie/EmulationStation/pull/650

By the way, OMXPlayer seems to render things wrong when rotated on the Pi4 at least. FYI.

**Comment by krahsdevil** [comment]
Thanks a lot, how can i test it? installing from source will compile the new changes?
Also thanks for the info in regard of OMX & PI4, i will keep it in mind and also by the way, It's weird because some versions ago of emulationstation some videos are no showing (wheter OMX enabled or not) only sound and seems to be related with the codec. If you recode one of these videos with a different codec then it is shown properly... I don't know if emulationstations depends of any external codec for playing... or something changed and it's controlled.

Thanks!

**Comment by pjft** [comment]
I don't think it's codec related - I know exactly what you're referring to, but this is not it. It literally renders visual artifacts on top of the video. It might be related to https://github.com/raspberrypi/firmware/issues/1334 but I don't know.

As for how to test it, if you're not on a Pi4, go to the terminal or SSH into it and run: 

git clone --recursive https://github.com/pjft/EmulationStation es-pjft
cd es-pjft
git checkout fix-rotation-omx
cmake .
make
./emulationstation --screenrotate 1 --screensize 240 320

Or similar, but at least these should help you go in the right direction.

On the Pi4 there are some weirder compilation flags that I don't know by heart, so I kind of hijack the emulationstation-dev RetroPie-Setup script for those builds for the time being.

**Comment by krahsdevil** [comment]
I've just tried the new change and works great, it fixed the problem!
This means we will have this fix on next emulationstation release?

Thanks!!

**Comment by pjft** [comment]
Likely only in experimental. But as soon as it's accepted, should be good to go.

Thanks for flagging!

**Comment by pjft** [comment]
Should be in experimental now. Hope it works!
