### ISSUE TITLE
Cannot compile on a Pi 4 // "failed to add service - already in use?" error

### ISSUE THREAD

**Issue by alinke** [RetroPie/EmulationStation#653]
I can compile ES just fine on a Pi 3B+ but getting this error when compiling on a Pi 4.

"failed to add service - already in use?"

As background, I make a LED marquee called Pixelcade https://youtu.be/WizU4eX6M5A?t=539 and have a quite a few Pi 4 asking for the integration. I have a fork done already for the Pi 3B+ , just need to be able to compile for the Pi 4. I have tried both on a vanilla ES compile and my own fork but get this message when running ES in both cases on a Pi 4. Given ES does run on the Pi 4 images out there, I'm assuming there is a way to compile successfully. Any help would be great, thanks.

**Comment by cmitu** [comment]
You need to run `cmake` with the `-DGL=On` options, otherwise the legacy BRCM GLES drivers are used. 

See https://github.com/RetroPie/RetroPie-Setup/blob/21a099a766c40c1725316f9859921fea9ed61368/scriptmodules/supplementary/emulationstation.sh#L154.

**Comment by alinke** [comment]
Yes!!!!!! that worked, thanks so much! was pulling my hair out over that one. Got my LED marquee with ES modded working now on the Pi 4 ==>https://youtu.be/KfEMrcfgm8E

**Comment by alinke** [comment]
If you happen to know how to compile AttractMode for Pi 4 , that would be helpful too.

**Comment by joolswills** [comment]
Might be possible to run it under X. However not from terminal without changes to the GUI library it uses which was modified for VC4 on RPI.

**Comment by joolswills** [comment]
Check their GitHub. There's a ticket open.

**Comment by alinke** [comment]
yes did get it to compile under X and will get their GitHub, thanks much
