### ISSUE TITLE
Grid view image ratio is not respected after selection

### ISSUE THREAD

**Issue by benjdero** [RetroPie/EmulationStation#667]
Because of the changes made to the grid view here #623, the aspect ratio of the image of the selected tile is set to 1x1.

It come from this [line](https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/views/gamelist/GridGameListView.cpp#L322) specifically. I think the same texture from the grid is reused and the size is overrode.

![Capture d’écran de 2020-06-30 23-34-39](https://user-images.githubusercontent.com/24305945/86179530-be109600-bb2a-11ea-9437-642a00ed8ac1.png)

**Comment by tomaz82** [comment]
Fixed by https://github.com/RetroPie/EmulationStation/pull/705
