### ISSUE TITLE
Publishing Internal state of EmulationStation

### ISSUE THREAD

**Issue by PhatHub** [RetroPie/EmulationStation#668]
A Feature Request:

Is there a way for Emulation Station have a debug mode or a way for it to publish its internal state so that other applications/daemons can read it? For example: somehow communicate to a daemon to say that you're at the NES menu, and that you're highlighting Metroid, and here's a list of the ROMS in the current directory you're browsing.

Currently it's easy to figure out which game you're playing because a process list (filtered by grepping for `runcommand.sh` and `/Retropie/roms/`) will display which rom file you're using. However, the internal state when you're not playing is more difficult.

This could be useful for external daemons that control/interact with peripheral hardware. The Pixelcade is one example where they had to build a custom ES just to display what game you're viewing, or which console's game list you're scrolling through.

Obvious suggestions would be to open a local port to read from, or dumping the data or a json/xml into a file in `/dev/shm`

**Comment by joolswills** [comment]
Please use the forum first as requested. This includes feature requests.

**Comment by PhatHub** [comment]
Will do! Sorry about that!
