### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by Power535** [RetroPie/EmulationStation#670]
1) Minimum dependencies in CMakeLists ?
2) Possible without vlc or without others dependencies ?
I want try not pi system gles 2.0 without x11

**Comment by cmitu** [comment]
> 
> 
>     1. Minimum dependencies in CMakeLists ?

 They're outlined in the project's README.md page.

>     2. Possible without vlc or without others dependencies ?
>        I want try not pi system gles 2.0 without x11

Without VLC it's not possible, you'll need to modify the source for it and you'll lose the video support. 
GLES2 build support is pending https://github.com/RetroPie/EmulationStation/pull/656, but you should be able to use the GLES1 renderer right now. 

As requested in the issue template, please use the RetroPie forum for support or questions.

**Comment by Power535** [comment]
How to disable Desktop OpenGL ?
Need only GLES or GLES2
Thank you

**Comment by cmitu** [comment]
>     1. How to disable VLC ?

 See my previou reply - VLC cannot be disabled.
 
>     2. VLC for video files . not for games ?

EmulationStation is not an emulator, just a front-end.

>        I want try GLES2 not for pi

Then you have to look to see if `CMakeLists.txt` can be used to detect your GLES2 libs (once build support is merged), possibly you'd need to modify it to have support for your platform.
