### ISSUE TITLE
Not works emulation station

### ISSUE THREAD

**Issue by Zaryob** [RetroPie/EmulationStation#678]
Hi all,
I installed retropie via raspberry pi imager application. There was emulation station on it but it doen't work and gives me error.

```
Aug 04 11:40:55 lvl0:   Error creating SDL window!
        Could not initialize EGL
Aug 04 11:40:55 lvl0:   Renderer failed to initialize!
Aug 04 11:40:55 lvl0:   Window failed to initialize!
```

**What I do?**
-------------------

I tried all the steps below but the output has not changed

* I take upgrade and it didn't work.
* I rebuild core and main packages and it didn't work.
* I install dependencies again (including both sdl1 and sdl2) and it didnt work.

Im trying to see screen output but it wasn't possible. Is there any way to fix it?

Bests, regards

**Comment by joolswills** [comment]
Please use the retropie forum as requested.

**Comment by Zaryob** [comment]
> Please use the retropie forum as requested.

I found the cause of the problem. It was experienced due to the use of GL, which changed with the Raspberry pi4. In any of the documentation, can you suggest TFT screen users to change their GL settings via raspi-config with the "Enable Fake GL" option?

Bests, regards.

**Comment by Zaryob** [comment]
![image](https://user-images.githubusercontent.com/22801690/89928558-ab50ad00-dc10-11ea-9e3b-dcc8b6cd46c8.png)
![image](https://user-images.githubusercontent.com/22801690/89928572-b0156100-dc10-11ea-95b0-35c25eb6190c.png)

This is for raspberry pi3+
![image](https://user-images.githubusercontent.com/22801690/89928589-b60b4200-dc10-11ea-9c71-782be59e1829.png)

This is for raspberry pi 4
![image](https://user-images.githubusercontent.com/22801690/89928689-df2bd280-dc10-11ea-9479-e33abdf26273.png)
