### ISSUE TITLE
Build linking error from Emulation Station on x86_64 Linux when linking against pugixml.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [RetroPie/EmulationStation#692]
I get the following error on pugixml when running it as a system binary and not with the built in pugixml library compiled in.

emulationstation: EmulationStation-2.9.0/es-core/src/resources/Font.cpp:21: Font::FontFace::FontFace(ResourceData&&, int): Assertion `!err' failed.

This does not happen when run from the EmulationStation Build directory where pugixml is present.

**Comment by cmitu** [comment]
The error is not related to linking, nor to `pugixml` - see a list of similar issues [here](https://github.com/RetroPie/EmulationStation/issues?q=is%3Aissue+Font%3A%3AFontFace%3A%3AFontFace+is%3Aclosed). 
Make sure EmulationStation can access the proper resource files (font/images/etc.) and you'll not get this error.
