### ISSUE TITLE
Scraping issue in XML

### ISSUE THREAD

**Issue by Zombie-Ryushu** [RetroPie/EmulationStation#694]
I got this error.

lvl0:   TheGamesDBJSONRequest - Error parsing JSON. 
        Invalid value.
lvl0:   TheGamesDBJSONRequest - Error parsing JSON. 
        Invalid value.

**Comment by joolswills** [comment]
Please follow the instructions in the text you removed when opening the issue:

>Please start a topic on the RetroPie forum before opening an issue - https://retropie.org.uk/forum/
