### ISSUE TITLE
Skip controller config page if configured controller is plugged in after startup.

### ISSUE THREAD

**Issue by gizmo98** [RetroPie/EmulationStation#7]
If emulationstation starts without any controller configuration screen pops up. If a configured controller is connected (bluetooth or wire) configuration screen stays. It is necessary to reconfigure the controller or restart es. It would be nice if the configuration screen tests if new connected controllers are already configured. It should be only necessary to reconfigure a controller if you open menu and select controller configuration.
 
1. Pass a "known controller reconfiguration" bool variable to GUIDetectDevice class. (startup = no, menu = yes)
2. GuiDetectDevice::input: If "known controller reconfiguration" = false close device detect GUI if comparison between known configured controller and mDeviceHeld->setText(strToUpper(config->getDeviceName())) is true: 
https://github.com/RetroPie/EmulationStation/blob/master/es-core/src/guis/GuiDetectDevice.cpp#L81

**Comment by gizmo98** [comment]
@petrockblog, @joolswills I modified GUIDetectDevice.cpp to get the right behavior:
https://github.com/gizmo98/EmulationStation/commit/cdda6f6dc1c443dff1345d32e3f1ca3ded130cb5

Tested with a PS3 controller. Skips input config menu if known input devices are connected after startup. Reconfiguration is possible if input configuration is selected from menu.

**Comment by joolswills** [comment]
nice job - please can you submit it as a pull request and I'll give it a test. thanks.

**Comment by gizmo98** [comment]
I just wanted to here your opinion beforehand. ;-)
I will do some more testing and do a PR then.

**Comment by joolswills** [comment]
Sure thing - looks good to me and thanks :)

**Comment by gizmo98** [comment]
@joolswills  
Can be closed?!
