### ISSUE TITLE
Feature Request: option to make filters persist between sessions

### ISSUE THREAD

**Issue by gomisensei** [RetroPie/EmulationStation#702]
for example, i especially want to make files ALWAYS hidden when i start up Emulationstation... maybe have an icon letting you know filters are active, or just make hidden roms filter persist.

**Comment by gomisensei** [comment]
for example, i especially want to make <hidden> files ALWAYS hidden when i start up Emulationstation... maybe have an icon letting you know filters are active, or just make hidden roms filter persist.

**Comment by cmitu** [comment]
Duplicate of https://github.com/RetroPie/EmulationStation/issues/321
