### ISSUE TITLE
Feature Request: I would like it to be an option with the screen Scraper, to be able to specify that local Screenshot archives of games already exist based on ROM Title.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [RetroPie/EmulationStation#719]
I would like it to be an option with the screen Scraper, to be able to specify that local Screenshot archives of games already exist based on ROM Title.

I have my own locally hosted screenshot collection that are partly a collection downloaded from a now Defunct group called EmuChrist, and some that I simply made using my Emulator's Screenshot Tools. In Spite of this, I have tried using XML generators to a limited amount of  success. Some Screenshots display, but only very few, and often only after hand editing.

So I request there to be a way to audit screenshots based on Rom File name.

**Comment by cmitu** [comment]
This option already exists - https://github.com/RetroPie/EmulationStation/pull/266 and https://github.com/RetroPie/EmulationStation/pull/526/
