### ISSUE TITLE
HDMI Audio does not work with Raspberry Pi OS (64bit)

### ISSUE THREAD

**Issue by ioogithub** [RetroPie/EmulationStation#736]
Pi Model or other hardware: 4b 8GB
Power Supply used: Official Power Supply
RetroPie Version Used (eg 3.6, 3.8.1, 4.1 - do not write latest):
Built From: https://retropie.org.uk/docs/Manual-Installation/
USB Devices connected:
Controller used: SN30Pro+
Error messages received: I do not see any errors in the journalctl logs.
In the terminal window:

`VolumeControl::init() - Failed to find mixer elements!`

```
$ uname -a
$ Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT aarch64 GNU/Linux
```

```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
```

```
pi@raspberrypi:~ $ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
jack
    JACK Audio Connection Kit
pulse
    PulseAudio Sound Server
default
    Playback/recording through the PulseAudio sound server
output
sysdefault:CARD=b1
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Default Audio Device
dmix:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct sample mixing device
dsnoop:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct sample snooping device
hw:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Direct hardware device without any conversions
plughw:CARD=b1,DEV=0
    bcm2835 HDMI 1, bcm2835 HDMI 1
    Hardware device with all software conversions
usbstream:CARD=b1
    bcm2835 HDMI 1
    USB Stream Output
sysdefault:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
dmix:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample mixing device
dsnoop:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample snooping device
hw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct hardware device without any conversions
plughw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Hardware device with all software conversions
usbstream:CARD=Headphones
    bcm2835 Headphones
    USB Stream Output
```

Every combination of settings does not product audio in eumlationstation with the 64bit version. Audio works as expected with the same setup/installation on the 32bit version.

Forum discussion: `https://retropie.org.uk/forum/topic/30128/no-audio-using-raspberry-pi-os-64bit/7`

**Comment by cmitu** [comment]
Please use the forum for support.

**Comment by ioogithub** [comment]
Yes I have and I have also linked the form discussion however we have been troubleshooting the issue for a while now and I do not see any solutions.

**Comment by cmitu** [comment]
It's not an EmulationStation issue and the issue template specifically asks to direct support questions in the forum.
You already have the topic opened there, so please continue on the forum.

**Comment by ioogithub** [comment]
I appreciate you taking the time to reply. I will continue seeking help in the forum thread and I did read the template completely before posting but I am unclear as to why this is not an EmulationStation issue.

I installed EmulationStation directly from the Retropie build script cloned from this repo and followed the instructions which resulted in audio that doesn't work only in EmulationStation.

I repeated the same steps with the 32bit version and it works as expected. Wouldn't this be considered an issue with the audio in the 64bit version of EmulationStation?

**Comment by cmitu** [comment]
> I repeated the same steps with the 32bit version and it works as expected. Wouldn't this be considered an issue with the audio in the 64bit version of EmulationStation?

Correlation does not imply causation. 
As users in the forums already reported (and myself have tested), audio works on Raspberry Pi OS 64, it just a matter of configuration. There are no 32bit vs. 64bit code paths for the audio system in EmulationStation and 64bit is already a common configuration when installing RetroPie on a Linux PC.
