### ISSUE TITLE
[feature request] Confirmation before enter the actual Configure Input screen

### ISSUE THREAD

**Issue by meleu** [RetroPie/EmulationStation#75]
If the user accidentally select "Configure Input" in emulationstation, he/she is forced to configure the input. Reconfigure the input doesn't hurt that much, but the problem is when the user has a custom `retroarch-joypads/Joypad.cfg`. I know that a `.bak` file is created, but it requires a keyboard/SSH connection to recover it.

It would be nice if after the user select "Configure Input" in the Main Menu there was a confirmation like "Do you want to configure input?" or something.

BTW, another user posted about this issue on the forum a couple of months ago https://retropie.org.uk/forum/topic/3788/disable-configure-input-menu

**Comment by joolswills** [comment]
Will be added as I am going to do some input improvements (There is a PR open for the first feature to configure hotkey). The input menu will be a submenu with some other options, as I would like to be able to have a "configure player 2" option (which would set up player 2 on retroarch for those with keyboards, and configure some non retroarch emulators).

I could possibly add a confirmation first though as some of the stuff above isn't ready yet.

**Comment by joolswills** [comment]
https://github.com/RetroPie/EmulationStation/pull/76 (If you want to give it a test first).

**Comment by meleu** [comment]
Yeah. Tested here and it's working just fine. I'm closing this issue.
