### ISSUE TITLE
Error in FontFace when not running from source directory

### ISSUE THREAD

**Issue by arbourp** [RetroPie/EmulationStation#759]
On Linux Mint 20.1

Fresh build and install from the repo and I am getting an asert from this line in the Font.cpp file
	int err = FT_New_Memory_Face(sLibrary, data.ptr.get(), (FT_Long)data.length, 0, &face);
	assert(!err);

Jul 23 10:44:10 lvl0: 	Error - File type unknown!

If I run the program from within the source directory I don't get any errors, but if I run it from outside the source directory I do.

Something to do with a relative or absolute path perhaps?

**Comment by cmitu** [comment]
Probably the same as https://github.com/RetroPie/EmulationStation/issues/427 or https://github.com/RetroPie/EmulationStation/issues/490. EmulationStation has some pre-defined paths where it looks for resources, running without it is not supported yet.
