### ISSUE TITLE
Raspberry Pi 4B - 4k60p - Menu performance

### ISSUE THREAD

**Issue by Balkoth** [RetroPie/EmulationStation#760]
In a default installation, with just enabling 4k60p mode on the pi, the emulationsation menu performance is really bad with about 10-15 fps.

**Comment by dankcushions** [comment]
Right, and it's similarly bad in most emulators - the pi4 is not really capable of 4k rendering, which is why we recommend switching to a 1080p mode: https://retropie.org.uk/docs/Pi4/#4k-video-display

**Comment by Balkoth** [comment]
Is this information accessible through the menu on left side of the site? I could and can not find it.
