### ISSUE TITLE
System Marquees Will Not Render if No Videos Are Referenced

### ISSUE THREAD

**Issue by roslof** [RetroPie/EmulationStation#763]
Discussed in forum [here](https://retropie.org.uk/forum/topic/31172/emulationstation-marquee-bug-with-work-around?_=1629658151623).

**ES Version(s) tested:** Latest stable and latest es-dev from master (62fd08c)
**Hardware Tested:** Raspberry Pi4B 2GB
**Noteworthy** Issue occurs if GAMELIST VIEW STYLE is set for anything other than "Video"

The Bug: For any system that does not reference at least one (1) video file in its gamelist.xml, all marquees for that system will not render.

A work-around that validates the bug: Add at least one (1) video reference to the gamelist.xml file, and all marquees for the system will correctly display.

**Comment by cmitu** [comment]
It's because the theme (_Carbon_) doesn't have marquee support in the _Detailed_ view style. Not a bug in EmulationStation.
