### ISSUE TITLE
Show the status of favorites, hidden and kid metadata fields in the theme directly with an icon

### ISSUE THREAD

**Issue by jean-paulschouwstraortec-financecom** [RetroPie/EmulationStation#765]
As the wiki states
https://retropie.org.uk/docs/Child-friendly-EmulationStation/
this functionality has been removed. It was implemented in the mid 2016 version. See also
https://github.com/Aloshi/EmulationStation/issues/112

Is it possible this can be activated again (I still have the left overs in my theme), because if you have many games this is really helpful if you scroll down your list and you can see if it has been already added to your favorites or not, instead of checking the metadata or just add it again.

**Comment by pjft** [comment]
This functionality was available on a fork of EmulationStation. Alas, that fork stopped development, though it probably can be installed from source if needed. I believe it is here: https://github.com/zigurana/EmulationStation

When the UI modes were brought over to the RetroPie EmulationStation, the whole thing was rearchitected, and we had to redevelop the features from the ground up for the most part. The theming components were never implemented here, and there are no plans for making it so at this stage.

That being said, if your use case is adding games to favorites, you can probably use filters to accomplish that for now. I know it's not optimal, but I hope it helps.

I recommend bringing these discussions up in the forums if possible, though, for the broader community to be able to discuss and even potentially decide to develop them.

Thanks.

**Comment by jean-paulschouwstraortec-financecom** [comment]
Thank you very much for the clear explanation how and why.
