### ISSUE TITLE
"Hidden" filter fails at system level after entering a subfolder and returning

### ISSUE THREAD

**Issue by roslof** [RetroPie/EmulationStation#775]
"Hidden" filter fails at system level after entering a subfolder and returning to system folder
Reproducibility: 100%

**Test System:**

- Raspberry Pi 4B / Latest RetroPie Sync
- ES-Dev Version: V2.11.0RP-DEV
- ES Commit: 8675f38 (2021 JAN 18)

**Date Issue Started:** Unknown. Never tested filters until recently

**Test Setup:**

1. Create system folder that contains a subfolder (eg. ```roms/amiga/demos```)
2. ROMs should exist in system folder and subfolder(s)
3. With ES (or manually editing gamelist.xml) tag ```<hidden>true</hidden>``` for a ROM at system level
4. Set UI to "KIOSK" mode and restart ES (automatic)

**Steps to Reproduce:**

1. From ES, enter system (eg. ```roms/amiga```) from top menu
2. Observe ROM with <hidden> filter does not appear (correct behavior)
3. Enter a subfolder (eg. ```roms/amiga/demos```)
4. Exit back to system level (eg. ```roms/amiga```)
5. Observe ROM with <hidden> filter now appears (incorrect behavior)

**Expected Results:** Hidden files should remain hidden regardless of user flow through ES

**Comment by pjft** [comment]
Thanks for sending this over.
