### ISSUE TITLE
ScreenScraperRequest - Error parsing XML. No document element found

### ISSUE THREAD

**Issue by Zombie-Ryushu** [RetroPie/EmulationStation#788]
Once again, the Screen Scraper is broken.
ScreenScraperRequest - Error parsing XML.
No document element found

**Comment by cmitu** [comment]
Please use the forum for support issues, as indicated in the template.

The scraper works fine, the error you're getting usually means their servers are overloaded and anonymouse access is not allowed. If you check their site, it will let you know if scraping is allowed or not without an account.
