### ISSUE TITLE
Gamelist: very short descriptions don't wrap.

### ISSUE THREAD

**Issue by s1eve-mcdichae1** [RetroPie/EmulationStation#796]
I am using theme **ruckage/snes-mini**, (slightly modified to correct gamelist alignment, but this occurs also in the unmodified theme.) Very short game descriptions do not wrap:

![20220621_172546](https://user-images.githubusercontent.com/92833764/175424200-f3715469-6502-49f0-877e-6e9f12977680.png)

"Sonic Boom is a vertically scrolling shooter from Sega."

If it's just a little bit longer, it will wrap properly:

![20220621_173306](https://user-images.githubusercontent.com/92833764/175424357-4eca21ee-3d6f-42a2-b9d0-96c22be5cce0.png)

"Ryu, the Dragon Ninja, travels the world to defeat evil wherever he finds it."

Does not occur in theme **RetroPie/carbon** but these both fit on one line without wrapping, there.

Does also occur in branch **emulationstation-dev** (v2.11.0rp-dev):

![20220623_152223](https://user-images.githubusercontent.com/92833764/175425139-1e39b331-3867-4739-b2e9-3d741fa56959.png)

**Comment by Gemba** [comment]
FTR, this can also happen in the carbon theme on descriptions on one line that slightly exceed the textcomponent dimension.


Sunny day case (with deliberately added "1 " chars):

![01b_shortdesc_wrapped--marked--scaled](https://user-images.githubusercontent.com/418292/184713082-e555f848-39e1-4694-b20d-422886ea8929.jpg)


Now the case that exposes the bug (chars "1 " removed again):

![01a_short_desc_not_wrapped--marked--scaled](https://user-images.githubusercontent.com/418292/184713321-1491fbdf-4e5b-4100-985f-a74abe43c021.jpg)
