### ISSUE TITLE
How to disable menu options

### ISSUE THREAD

**Issue by majerle9** [RetroPie/EmulationStation#8]
I have a Raspberry Pi 2 B running RetroPie and EmulationStation Simple Theme and it works perfectly. My emulators are all set right, my roms are all scraped, and my PS3 controllers are configured perfectly. My only issue is that allowing a friend or a child to use my system leaves me open to the possibility of them destroying my settings because they accidentally went into a menu and started changing things.

I would really like to be able to have my system all set and then disable the menu options so they can't be accessed by everyone all the time. In the EmulationStation menus I have to worry about:

   1. Edit This Game's Metadata
   2. Scraper
   3. Sound Settings
   4. UI Settings
   5. Configure Input
   6. Press a key (or joypad button 0) to configure launch options for emulator/port ($emulator).

If there was a way to disable these options no one would cause any accidental damage while playing.

I also have a Kodi setup on a PC and it has a Kiosk Mode setting which locks the menu options for users. Would something like that be possible in EmulationStation?

If anyone knows how to disable any of those settings manually please let me know. I don't even need to remove them, just stop them from being functional.

**Comment by gizmo98** [comment]
You could comment out every menu item listed here and recompile:
https://github.com/Aloshi/EmulationStation/blob/646bede3d9ec0acf0ae378415edac136774a66c5/es-app/src/guis/GuiMenu.cpp#L36

Or you could add a option to show up menu item if there config file option is set or button combo is present. I don't think there is a ready to use function atm.

**Comment by smartroad** [comment]
Maybe they could be activated by an optional code? Using a gamepad having to press up up down down left right (configurable to the setup obviously ;))

**Comment by joolswills** [comment]
Also https://github.com/RetroPie/RetroPie-Setup/pull/1127

Closing as not something we are going to implement.
