### ISSUE TITLE
Can't take a screenshot with Amiberry (Amiga emulator)

### ISSUE THREAD

**Issue by simulant-systems** [RetroPie/EmulationStation#810]
Hi sorry if this is posted in the wrong place, but I'm using Retropie with Emulation Station.

I can take screenshots with any problems on all systems except for the Amiga (with Amiberry emulator).

I've mapped the overall hotkey and screenshot button for retropie, yet it won't capture anything in Amiberry.

I also can't find any option to take a screenshot or map the feature to a button anywhere in Amiberry settings too.

It seems strange having to hook up a capture card to take screenshots rather than just taking them direct.

I hope someone can help.

**Comment by joolswills** [comment]
This is the wrong place, sorry. Please use the forum https://retropie.org.uk/forum/
