### ISSUE TITLE
ScreenSaver audio dont stop when starting game during screensaver

### ISSUE THREAD

**Issue by apison** [RetroPie/EmulationStation#812]
On my linux board The audio dont stop when the game is launched during screensaver, this cause the audio dont work in the game itself.
I've fixed the problem closing screensaver before launch the game in file EmulationStation-master\es-app\src\SystemScreenSaver.cpp  

void SystemScreenSaver::launchGame()
{
	if (mCurrentGame != NULL)
	{
		//Stop screensaver
		mStopBackgroundAudio = true;
		stopScreenSaver();
	
		// launching Game
		ViewController::get()->goToGameList(mCurrentGame->getSystem());
		IGameListView* view = ViewController::get()->getGameListView(mCurrentGame->getSystem()).get();
		view->setCursor(mCurrentGame);
		view->launch(mCurrentGame);
	}
}

**Comment by pjft** [comment]
Thank you! Used this to fix recent reports of the same behavior. In hindsight, it's a surprise it worked as intended so far.

Best.
