### ISSUE TITLE
[feature request] make emulationstation say which controller chose a game

### ISSUE THREAD

**Issue by meleu** [RetroPie/EmulationStation#82]
It would be useful if emulationstation said which controller chose a game. I mean, save the `deviceName` from `es_input.cfg` in some file or shell variable.

And then the functions used to start joy2key in `runcommand.sh` and `helpers.sh` could get this info to make the respective device control the dialog menus.

**Comment by joolswills** [comment]
I don't want to incorporate this into ES as I want RetroPie to be frontend agnostic. You can switch RetroArch controllers with your script or via the configuration editor. More work is planned for the joy2key script, but it won't be part of ES.

I will be improving the control configuration though, as mentioned https://github.com/RetroPie/EmulationStation/issues/4 but I may also split this out into "inputstation" so again it's separate from the frontend.

**Comment by joolswills** [comment]
I may incorporate more into runcommand also (which is available when launching from all frontends).

**Comment by meleu** [comment]
The feature request is only make emulationstation "say", in some way, which device chose a game (which device pressed "A" to launch the game). Only this. The use of this info would be done by other programs/scripts. I think it can be done in a way that doesn't violate the frontend agnostic's principle.

What I envisioned is making the device used to launch the game control the runcommand/retropie_setup dialog menus. Nothing to do with RetroArch and players1-4. Only control the dialog menus.

But let's wait the new version of joy2key. :-)

I'm closing this request.

Cheers!

**Comment by joolswills** [comment]
OK - misunderstood. Initially my plan was to allow joy2key to be controlled from all joysticks (and not choke if one is unplugged). I'm looking into it now (since someone keeps bringing it up ;-) )

**Comment by joolswills** [comment]
https://github.com/RetroPie/RetroPie-Setup/pull/1797
