### ISSUE TITLE
Launching games direct from IAGL

### ISSUE THREAD

**Issue by GFoley83** [RetroPie/EmulationStation#877]
Apologies if this isn't the correct place to ask.

I use [Internet Archive Game Launcher](https://github.com/zach-morris/plugin.program.iagl) with RetroPie on OSMC. It places ROMs in the folder:
`/home/osmc/.kodi/userdata/addon_data/plugin.program.iagl/game_cache`

Is there any way to have EmulationStation looking in that location automatically to then be able to launch the ROMs? Removing the need to copy then into a location that RetroPie/EmulationStation expects?

Thanks.

**Comment by pjft** [comment]
Please start a topic on the RetroPie forum for questions such as these - https://retropie.org.uk/forum/
There are more people to help on the forum.

To answer briefly: I suspect it is doable, but you'd have to edit the paths in the systems.cfg file at least, and see what else breaks from there. Maybe not much more, but between the info in the wiki and folks in the forums this should point you in the right direction. Nonetheless, this will become a setup that's not very easily supported by others, so proceed at your own risk. 

Best of luck.

**Comment by GFoley83** [comment]
Thank you!
