### ISSUE TITLE
Automatically hide various BIOS/non-game files

### ISSUE THREAD

**Issue by dankcushions** [RetroPie/EmulationStation#89]
This has been done in Recalbox via this commit: https://github.com/Aloshi/EmulationStation/commit/a8273e74b24556838cf65627bb8af3d3fb3b2ae1 thanks to @gillg

This seems really neat. I tried porting the patch but FileData.cpp has a bunch of other changes in Recalbox from our fork, so needs more thought.

**Comment by Darknior** [comment]
If it can be possible to add this option or the <hidden> tag it will be a dream for many systems :)
For bios, multi-CD games, Dos games with multi exe file ...

**Comment by dankcushions** [comment]
@Darknior I agree, although for me I think a 'hidden' tag is a separate feature. For these bios files there's no reason to ever show them, so I think it's  better they are hidden automatically and permanently.

**Comment by Darknior** [comment]
@dankcushions Yes for sure if it is possible it is the best solution ;)

**Comment by jrassa** [comment]
@dankcushions It looks like they moved populateFolder method from SystemData.cpp to FileData.cpp.  The change would need to be made in SystemData.cpp.  If no one else does so first, I can try to integrate it this weekend.  Should be fairly straight forward.

**Comment by joolswills** [comment]
I don't know if I'm keen on this change - gamelists can be used to show only certain things (with parse gamelists only on). I actually like to see everything I have copied across - also a hardcoded list for mame in the source is not ideal - might be better to perhaps have some configurable exclusion list.

For now at least I'm not sold on this change.

**Comment by joolswills** [comment]
I would add I don't like the current mame game name mapping either - would also be better with something more flexible / configurable so it could work better with different romset versions.

**Comment by dankcushions** [comment]
@joolswills that makes sense - I suppose having the list as an editable text file, and having an option in the UI options to 'Hide BIOS files' would be a more elegant solution.

**Comment by gillg** [comment]
Hi ! I told in pr about a potential improvement, which could consist to init vector with a new config file. But also, as @dankcushions said before, on mame no one need to view roms and devices. You could extend the "basic" ignorelist with a external config file, by platform or system (what is more logic ?). I could port this commit on retropie, but at the start I would to use retropie, but in reality recalbox branch is more active. So now, my wich is to port recalbox to a generic emelationstation branch, like retropie. In fact it could be easy and I am near of this goal. I made a SettingsManager to use es_settings.cfg or recalbox.conf, or any other conf mechanism. And y have separated "standard" guimenu and recalboxguimenu. If you are not on recalbox os, you have no linux system settings, like wifi, updates, kodi, etc...

**Comment by joolswills** [comment]
RetroPie and recalbox have some different aims/goals and target audiences - I do not want to include system configuration stuff into Emulation Station (which would be platform specific too). We include wifi settings and updated from our text based gui separate from the frontends.

**Comment by gillg** [comment]
Yes i'm totally according with you. For this reason I think recalbox has missed to think "generic" or reusable code. Retropie or recalbox have some particularity, but at the start the awsome emulationstation is a good game platform, wich could be improved and used both with retropie or recalbox. Each system can code some specific intefaces/menu but the basics are same.

**Comment by jrassa** [comment]
implemented in #432
