### ISSUE TITLE
Ability to control USB audio volume

### ISSUE THREAD

**Issue by hex007** [RetroPie/EmulationStation#90]
Using alsa config file sound can be defaulted to USB audio/sound card rather than PWM (on Raspberry pi zero). The volume control in emulation station does not support changing volume of this and resets to zero.

**Comment by alexruffell** [comment]
I have this issue too. I was trying to configure a USB-Audio card on my RPI for use in ES and on top of the  bug described above, MAME4ALL will not run ANY ROMS while before the change it did. Please make the sound card used in ES configurable!

**Comment by hex007** [comment]
Any updates on this?

**Comment by hex007** [comment]
Duplicates #46
