### ISSUE TITLE
Rank alphabetically by file name.

### ISSUE THREAD

**Issue by DjBlades** [RetroPie/EmulationStation#95]
A few games don't have numbers defining their place in their series. This changes the order at which they appear in the game list, and can be mildly irritating or confusing when you're trying to play a through whole series. As an example, the spyro series is ranked:

Spyro 2: Ripto's Rage
Spyro The Dragon
Spyro: Year of the Dragon

The Phoenix Wright series is also all over the place, due to several of the games in the series having completely different names. This could be fixed by listing each title alphabetically by it's file name, rather than the scraped game name. In your folder you could title each entry "Phoenix Wright 1, Phoenix Wright 2, Phoenix Wright 3..." to make them list in the correct order, and the scraped game names would keep them displayed with their original names.

**Comment by MotaDan** [comment]
Sorting by file name would cause more mix ups than it would fix. If you're going to manually rename the files, I suggest just changing the scrapped names to enforce the order you want.
Spyro 1: Spyro The Dragon
Spyro 2: Ripto's Rage
Spyro 3: Year of the Dragon

**Comment by meleu** [comment]
I think this will be solved when/if #240 is merged.
