### ISSUE TITLE
Official Ubuntu PPA?

### ISSUE THREAD

**Issue by clara2g** [RetroPie/EmulationStation#98]
Hi! EmulationStation .deb file won't install in my Ubuntu 16.10 due to dependency problems. I've found this PPA for binary installing EmulationStation in Ubuntu:[https://launchpad.net/~emulationstation/+archive/ubuntu/ppa
]( https://launchpad.net/~emulationstation/+archive/ubuntu/ppa)

But I can't make sure if it is official. Do you know who is maintaining it? Is it yours?

Thanks!

**Comment by joolswills** [comment]
Not ours.

**Comment by clara2g** [comment]
Ok thank you.

**Comment by clara2g** [comment]
Ok thank you.
